import { defineQuestions } from "../helpers/create-question";

/**
 * Grade 3 ICAS-style Spelling — 36 hand-authored questions. ICAS-only:
 * NAPLAN folds spelling into Language Conventions rather than setting it
 * as its own paper.
 */
export const grade3IcasSpelling = defineQuestions([
  {
    id: "icas-y3-spelling-a-001",
    type: "fill_blank",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "One vowel is missing from the middle of the word. Write the single letter that fills the gap so the sentence makes sense and the word is spelt correctly.",
    instructions: "Type just the one missing letter.",
    options: [],
    interaction: {
      type: "fill_blank",
      segments: ["The sun is very h", "t today."],
      blanks: [
        {
          id: "b1",
          label: "missing vowel",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "fill_blank",
      blanks: [
        {
          id: "b1",
          acceptedAnswers: ["o"],
        },
      ],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation: "Say the word slowly: /h/ /o/ /t/. The short vowel sound in the middle is the letter 'o', which gives 'hot'. No other vowel fits the sentence.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Short vowel sounds",
      skill: "Choosing the correct short vowel in a one-syllable word",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["spelling", "short vowels", "phonics", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-002",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "smiel", text: "smiel" },
      { id: "smyle", text: "smyle" },
      { id: "smille", text: "smille" },
      { id: "smile", text: "smile" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "smile",
    },
    explanation: "The long 'i' sound comes from the silent 'e' at the end: smi-l-e. The 'e' is not spoken but makes the 'i' say its name. 'smiel' and 'smyle' use the wrong letters for that sound.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Long vowel sounds",
      skill: "Spelling a long vowel with the silent 'e' (magic e) pattern",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 35,
      tags: ["spelling", "long vowels", "magic e", "silent e", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-003",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "shovel", text: "shovel" },
      { id: "shuvel", text: "shuvel" },
      { id: "shovle", text: "shovle" },
      { id: "shovval", text: "shovval" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "shovel",
    },
    explanation: "It starts with the 'sh' digraph and reads in two beats: sho-vel, ending '-vel'. 'shuvel' swaps the first vowel and 'shovle' turns the ending letters around.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Digraph sh",
      skill: "Spelling words that begin with the 'sh' digraph",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["spelling", "digraph", "sh", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-004",
    type: "fill_blank",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Two letters are missing from the end of the word. Write the two letters that complete it correctly.",
    instructions: "Type just the two missing letters.",
    options: [],
    interaction: {
      type: "fill_blank",
      segments: ["We ate our lun", " in the park."],
      blanks: [
        {
          id: "b1",
          label: "missing letters",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "fill_blank",
      blanks: [
        {
          id: "b1",
          acceptedAnswers: ["ch"],
        },
      ],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation: "The word ends with the 'ch' sound you hear in 'chip' and 'much'. 'lun' plus 'ch' spells 'lunch'.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Digraph ch",
      skill: "Spelling the 'ch' digraph at the end of a word",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["spelling", "digraph", "ch", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-005",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Choose the correctly spelt word to complete the sentence: The sky turned dark just before the loud ___.",
    options: [],
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "f1",
          label: "the word",
          options: [
            { id: "thonder", text: "thonder" },
            { id: "thunder", text: "thunder" },
            { id: "thunda", text: "thunda" },
          ],
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "dropdown",
      fields: [
        {
          id: "f1",
          correctOptionId: "thunder",
        },
      ],
    },
    explanation: "It begins with the 'th' digraph and the middle says short 'u': thun-der. 'thonder' uses the wrong vowel and 'thunda' drops the '-er' ending.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Digraph th",
      skill: "Spelling words that begin with the 'th' digraph",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["spelling", "digraph", "th", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-006",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "blankit", text: "blankit" },
      { id: "blanket", text: "blanket" },
      { id: "blancet", text: "blancet" },
      { id: "blankut", text: "blankut" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "blanket",
    },
    explanation: "Break it into two parts: blan-ket. The 'bl' blend starts it and the ending is spelt '-ket' with an 'e'. 'blankit' and 'blankut' use the wrong vowel in the second part.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Blend bl",
      skill: "Spelling words that begin with the 'bl' blend",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["spelling", "blend", "bl", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-007",
    type: "fill_blank",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Three letters are missing from the start of the word. Write the letters that complete it so the sentence makes sense.",
    instructions: "Type just the three missing letters.",
    options: [],
    interaction: {
      type: "fill_blank",
      segments: ["We walked down the busy ", "eet."],
      blanks: [
        {
          id: "b1",
          label: "missing letters",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "fill_blank",
      blanks: [
        {
          id: "b1",
          acceptedAnswers: ["str"],
        },
      ],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation: "The word 'street' begins with the three-letter blend 'str', where you hear /s/ /t/ /r/ run together, and then 'eet' makes the long 'e' sound.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Blend str",
      skill: "Spelling the three-letter blend 'str' at the start of a word",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["spelling", "blend", "str", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-008",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "jumpping", text: "jumpping" },
      { id: "jumpeing", text: "jumpeing" },
      { id: "jumping", text: "jumping" },
      { id: "jumbing", text: "jumbing" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "jumping",
    },
    explanation: "'jump' already ends in two consonants (m and p), so you just add '-ing' with no changes: jump + ing = jumping. You do not double a letter or add an extra 'e'.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Adding -ing",
      skill: "Adding -ing to a base word with no spelling change",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["spelling", "suffix", "ing", "word building", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-009",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "swiming", text: "swiming" },
      { id: "swimmming", text: "swimmming" },
      { id: "swimeing", text: "swimeing" },
      { id: "swimming", text: "swimming" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "swimming",
    },
    explanation: "'swim' has one short vowel and ends in a single 'm', so you double the 'm' before '-ing': swim + m + ing = swimming. 'swiming' forgets to double the 'm'.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Adding -ing with doubling",
      skill: "Doubling the final consonant before adding -ing",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["spelling", "suffix", "ing", "doubling", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-010",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Choose the correctly spelt word to complete the sentence: We are ___ a sandcastle on the beach.",
    options: [],
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "f1",
          label: "the word",
          options: [
            { id: "making", text: "making" },
            { id: "makeing", text: "makeing" },
            { id: "makking", text: "makking" },
          ],
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "dropdown",
      fields: [
        {
          id: "f1",
          correctOptionId: "making",
        },
      ],
    },
    explanation: "'make' ends in a silent 'e', so you drop the 'e' before adding '-ing': mak(e) + ing = making. 'makeing' keeps the 'e' by mistake.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Adding -ing after dropping e",
      skill: "Dropping the silent 'e' before adding -ing",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["spelling", "suffix", "ing", "drop e", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-011",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "jumped", text: "jumped" },
      { id: "jumpt", text: "jumpt" },
      { id: "jumpped", text: "jumpped" },
      { id: "jumpd", text: "jumpd" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "jumped",
    },
    explanation: "Even though the ending here sounds like 't', the past tense is spelt with '-ed': jump + ed = jumped. 'jumpt' spells it the way it sounds, which is wrong.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Adding -ed",
      skill: "Adding -ed to a base word with no spelling change",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 35,
      tags: ["spelling", "suffix", "ed", "past tense", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-012",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "stoped", text: "stoped" },
      { id: "stopped", text: "stopped" },
      { id: "stopt", text: "stopt" },
      { id: "stoppped", text: "stoppped" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "stopped",
    },
    explanation: "'stop' has one short vowel and one final consonant, so you double the 'p' before '-ed': stop + p + ed = stopped. 'stoped' forgets to double and 'stoppped' doubles too much.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Adding -ed with doubling",
      skill: "Doubling the final consonant before adding -ed",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["spelling", "suffix", "ed", "doubling", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-013",
    type: "short_answer",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Add the ending '-ed' to the word 'bake' to make its past tense. Write the one new word.",
    instructions: "Write only the single new word, with no other words.",
    options: [],
    visuals: [],
    answerKey: {
      kind: "text",
      acceptableAnswers: ["baked"],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation: "'bake' ends in a silent 'e'. You drop the 'e' before adding '-ed': bak(e) + ed = baked. You do not write 'bakeed'.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Adding -ed after dropping e",
      skill: "Dropping the silent 'e' before adding -ed",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["spelling", "suffix", "ed", "drop e", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-014",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is the correct plural of 'chair' (more than one chair)?",
    options: [
      { id: "chaires", text: "chaires" },
      { id: "chairies", text: "chairies" },
      { id: "chairs", text: "chairs" },
      { id: "chaers", text: "chaers" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "chairs",
    },
    explanation: "'chair' is a plain noun, so you make it plural by just adding 's': chair + s = chairs. You do not add 'es' or change any letters.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Plurals with -s",
      skill: "Making a plural by adding -s",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 35,
      tags: ["spelling", "plurals", "s", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-015",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is the correct plural of 'box' (more than one box)?",
    options: [
      { id: "boxs", text: "boxs" },
      { id: "boxies", text: "boxies" },
      { id: "boxses", text: "boxses" },
      { id: "boxes", text: "boxes" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "boxes",
    },
    explanation: "Words that end in 'x' add '-es' to become plural so you can hear the extra sound: box + es = boxes. 'boxs' is too hard to say and 'boxies' changes the wrong letters.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Plurals with -es",
      skill: "Making a plural by adding -es after x, s, sh or ch",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["spelling", "plurals", "es", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-016",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is the correct plural of 'baby' (more than one baby)?",
    options: [
      { id: "babies", text: "babies" },
      { id: "babys", text: "babys" },
      { id: "babyies", text: "babyies" },
      { id: "babbies", text: "babbies" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "babies",
    },
    explanation: "When a word ends in a consonant then 'y', change the 'y' to 'i' and add '-es': bab(y) becomes babi + es = babies. 'babys' forgets to change the 'y'.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Plurals with -ies",
      skill: "Making a plural by changing y to -ies",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["spelling", "plurals", "ies", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-017",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which TWO words are spelt correctly? Choose two.",
    options: [
      { id: "tabel", text: "tabel" },
      { id: "rabbit", text: "rabbit" },
      { id: "kichen", text: "kichen" },
      { id: "garden", text: "garden" },
    ],
    visuals: [],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["garden", "rabbit"],
    },
    explanation: "'garden' (gar-den) and 'rabbit' (rab-bit, with a double b) are both correct. 'tabel' should be 'table', and 'kichen' is missing the 't' in 'kitchen'.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Two-syllable words",
      skill: "Recognising correctly spelt two-syllable words",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 55,
      tags: ["spelling", "syllables", "two syllable", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-a-018",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word is spelt correctly?",
    options: [
      { id: "trane", text: "trane" },
      { id: "trian", text: "trian" },
      { id: "train", text: "train" },
      { id: "traine", text: "traine" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "train",
    },
    explanation: "The long 'a' sound in the middle is spelt with the vowel team 'ai': tr-ai-n = train. 'trane' uses a silent 'e' instead, and 'trian' swaps the two vowels around.",
    metadata: {
      subject: "spelling",
      strand: "Phonics and word building",
      topic: "Long vowel with ai team",
      skill: "Spelling the long 'a' sound with the 'ai' vowel team",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 35,
      tags: ["spelling", "long vowels", "ai", "vowel team", "year 3", "icas"],
    },
  },
  {
    id: "icas-y3-spelling-b-001",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Choose the word that correctly completes the sentence: The girls waved to ___ grandmother at the gate.",
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "f1",
          label: "___ grandmother",
          options: [
            { id: "opt-their", text: "their" },
            { id: "opt-there", text: "there" },
            { id: "opt-theyre", text: "they're" },
          ],
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "dropdown",
      fields: [
        {
          id: "f1",
          correctOptionId: "opt-their",
        },
      ],
    },
    explanation: "'Their' shows that something belongs to them, and the grandmother belongs to the girls' family. 'There' points to a place, and 'they're' is short for 'they are', so neither of those fits before 'grandmother'.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Homophones",
      skill: "Homophones: their vs there",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["homophones", "their", "there", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-002",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Choose the word that correctly completes the sentence: By the end of the race we were ___ tired to walk home.",
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "f1",
          label: "___ tired",
          options: [
            { id: "opt-to", text: "to" },
            { id: "opt-too", text: "too" },
            { id: "opt-two", text: "two" },
          ],
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "dropdown",
      fields: [
        {
          id: "f1",
          correctOptionId: "opt-too",
        },
      ],
    },
    explanation: "'Too' means 'more than enough' or 'also', and here it means more than enough tired. 'To' shows direction, like 'walk home', and 'two' is the number 2. The extra 'o' in 'too' is like having too many o's.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Homophones",
      skill: "Homophones: to vs too",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["homophones", "to", "too", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-003",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word correctly completes the sentence? Please come ___ and sit next to me on the mat.",
    options: [
      { id: "opt-hear", text: "hear" },
      { id: "opt-here", text: "here" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-here",
    },
    explanation: "'Here' means in this place, which is where the person is asked to sit. 'Hear' is what you do with your ears. A handy tip: the word 'here' is hiding inside 't-here' and 'w-here', which are also places.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Homophones",
      skill: "Homophones: hear vs here",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 30,
      tags: ["homophones", "hear", "here", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-004",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word correctly completes the sentence? Do you ___ the way to the new library?",
    options: [
      { id: "opt-know", text: "know" },
      { id: "opt-no", text: "no" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-know",
    },
    explanation: "'Know' means to have something in your head, like knowing the way somewhere. 'No' is the opposite of yes. 'Know' begins with a silent k, so you cannot hear it but you must still write it.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Homophones",
      skill: "Homophones: no vs know",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 30,
      tags: ["homophones", "no", "know", "silent k", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-005",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which word correctly completes the sentence? At the wildlife park we watched a big brown ___ climb a tree.",
    options: [
      { id: "opt-bare", text: "bare" },
      { id: "opt-bear", text: "bear" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-bear",
    },
    explanation: "'Bear' is the large animal. 'Bare' means empty or uncovered, like bare feet. To remember the animal, picture it: a 'bEAR' has big 'EARs'.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Homophones",
      skill: "Homophones: bare vs bear",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 30,
      tags: ["homophones", "bare", "bear", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-006",
    type: "fill_blank",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Fill in the two missing letters to spell the small animal that hops and has long ears: ra__it.",
    interaction: {
      type: "fill_blank",
      segments: ["ra", "it"],
      blanks: [
        {
          id: "b1",
          label: "two missing letters",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "fill_blank",
      blanks: [
        {
          id: "b1",
          acceptedAnswers: ["bb"],
        },
      ],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation: "'Rabbit' has a double b in the middle: ra-bb-it. Say the word slowly and listen for the short 'a' sound near the start; a short vowel is usually followed by two consonants, so you need two b's.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Double consonants",
      skill: "Double consonant (bb) in 'rabbit'",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 35,
      tags: ["double letters", "rabbit", "short vowel", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-007",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling correctly completes the sentence? The little frog was ___ across the lily pads.",
    options: [
      { id: "opt-hoping", text: "hoping" },
      { id: "opt-hopeing", text: "hopeing" },
      { id: "opt-hopin", text: "hopin" },
      { id: "opt-hopping", text: "hopping" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-hopping",
    },
    explanation: "'Hop' has one short vowel and one final consonant, so you double the p before adding -ing: hop becomes hopping. 'Hoping' with one p comes from 'hope' and means wishing for something, which does not fit a frog jumping.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Suffixes",
      skill: "Doubling the final consonant before -ing (hopping)",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["suffix", "-ing", "doubling", "hopping", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-008",
    type: "fill_blank",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Fill in the two missing letters to complete the word: We sit down together to eat di__er every evening.",
    interaction: {
      type: "fill_blank",
      segments: ["di", "er"],
      blanks: [
        {
          id: "b1",
          label: "two missing letters",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "fill_blank",
      blanks: [
        {
          id: "b1",
          acceptedAnswers: ["nn"],
        },
      ],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation: "'Dinner', the evening meal, has a double n: din-ner. With only one n you get 'diner', which is a place where you buy food, not the meal itself.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Double consonants",
      skill: "Double consonant (nn) in 'dinner'",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["double letters", "dinner", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-009",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? I stayed inside at lunchtime ___ it was raining hard.",
    options: [
      { id: "opt-because", text: "because" },
      { id: "opt-becuase", text: "becuase" },
      { id: "opt-becos", text: "becos" },
      { id: "opt-becaus", text: "becaus" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-because",
    },
    explanation: "'Because' is spelt be-cause, ending in the whole word 'cause'. Break it into those two chunks to get the order right, and remember it finishes with -se, not just -s.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Tricky high-frequency words",
      skill: "Spelling the tricky word 'because'",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["tricky words", "because", "high frequency", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-010",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? My best ___ lives in the house next door.",
    options: [
      { id: "opt-freind", text: "freind" },
      { id: "opt-friend", text: "friend" },
      { id: "opt-frend", text: "frend" },
      { id: "opt-frind", text: "frind" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-friend",
    },
    explanation: "'Friend' is spelt fri-end, with the i before the e. Remember the saying 'a friend is there to the END', because the word finishes with 'end'.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Tricky high-frequency words",
      skill: "Spelling the tricky word 'friend'",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["tricky words", "friend", "ie", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-011",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? \"Please line up quietly,\" ___ the teacher.",
    options: [
      { id: "opt-sed", text: "sed" },
      { id: "opt-saed", text: "saed" },
      { id: "opt-said", text: "said" },
      { id: "opt-siad", text: "siad" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-said",
    },
    explanation: "'Said' is the past tense of 'say' and is spelt s-a-i-d, even though it sounds like 'sed'. The 'ai' keeps the link to its base word 'say'.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Tricky high-frequency words",
      skill: "Spelling the tricky word 'said'",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["tricky words", "said", "high frequency", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-012",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? After they finished lunch, ___ went outside to play.",
    options: [
      { id: "opt-thay", text: "thay" },
      { id: "opt-thei", text: "thei" },
      { id: "opt-dey", text: "dey" },
      { id: "opt-they", text: "they" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-they",
    },
    explanation: "'They' is spelt t-h-e-y. The 'ey' at the end makes the long 'a' sound, just like in 'grey', 'obey' and 'prey'.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Tricky high-frequency words",
      skill: "Spelling the tricky word 'they'",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["tricky words", "they", "ey", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-013",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? The old dog ___ fast asleep on the warm mat.",
    options: [
      { id: "opt-was", text: "was" },
      { id: "opt-wos", text: "wos" },
      { id: "opt-wuz", text: "wuz" },
      { id: "opt-waz", text: "waz" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-was",
    },
    explanation: "'Was' is spelt w-a-s, even though it sounds like 'woz'. It is the past tense of 'is', and the 'a' in the middle is the letter to remember.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Tricky high-frequency words",
      skill: "Spelling the tricky word 'was'",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 30,
      tags: ["tricky words", "was", "high frequency", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-014",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? The teacher drew a big ___ on the whiteboard.",
    options: [
      { id: "opt-circel", text: "circel" },
      { id: "opt-circle", text: "circle" },
      { id: "opt-sircle", text: "sircle" },
      { id: "opt-curcle", text: "curcle" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-circle",
    },
    explanation: "In 'circle' the first c is a soft c and sounds like 's', because it comes before the letter i. It still begins with c, not s: c-i-r-c-l-e, and ends in -cle.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Soft c",
      skill: "Soft c (c sounding like s) in 'circle'",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["soft c", "circle", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-015",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? Please be very ___ when you hold the baby chick.",
    options: [
      { id: "opt-jentle", text: "jentle" },
      { id: "opt-gentel", text: "gentel" },
      { id: "opt-gentle", text: "gentle" },
      { id: "opt-gentl", text: "gentl" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-gentle",
    },
    explanation: "In 'gentle' the g is a soft g and sounds like 'j', because it comes before the letter e. It still begins with g, not j: g-e-n-t-l-e, ending in -tle.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Soft g",
      skill: "Soft g (g sounding like j) in 'gentle'",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["soft g", "gentle", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-016",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which spelling is correct? The children love to ___ the big gum tree in the yard.",
    options: [
      { id: "opt-clime", text: "clime" },
      { id: "opt-climbe", text: "climbe" },
      { id: "opt-clim", text: "clim" },
      { id: "opt-climb", text: "climb" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-climb",
    },
    explanation: "'Climb' ends with a silent b: c-l-i-m-b. You cannot hear the b when you say it, but it must be written, just like the silent b in 'thumb', 'lamb' and 'comb'.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Silent letters",
      skill: "Silent letter b in 'climb'",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["silent letters", "silent b", "climb", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-017",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "One word in this sentence is spelt incorrectly. Which one is it? \"The children were verry happy at the party.\"",
    options: [
      { id: "opt-verry", text: "verry" },
      { id: "opt-children", text: "children" },
      { id: "opt-happy", text: "happy" },
      { id: "opt-party", text: "party" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-verry",
    },
    explanation: "Read each word on its own. 'Verry' has an extra r; the correct spelling is 'very' with just one r. 'Children', 'happy' and 'party' are all spelt correctly.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Proofreading",
      skill: "Proofreading: find the one misspelt word",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["proofreading", "editing", "very", "year 3"],
    },
  },
  {
    id: "icas-y3-spelling-b-018",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "This sentence has TWO words that are spelt incorrectly: \"The elefant is a very big anmal.\" Select the two misspelt words.",
    options: [
      { id: "opt-big", text: "big" },
      { id: "opt-very", text: "very" },
      { id: "opt-anmal", text: "anmal" },
      { id: "opt-elefant", text: "elefant" },
    ],
    visuals: [],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["opt-elefant", "opt-anmal"],
    },
    explanation: "'Elefant' should be 'elephant', because the 'f' sound in this word is spelt with ph. 'Anmal' is missing an i and should be 'animal'. 'Big' and 'very' are both spelt correctly.",
    metadata: {
      subject: "spelling",
      strand: "Spelling",
      topic: "Proofreading",
      skill: "Proofreading: select the two misspelt words",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 55,
      tags: ["proofreading", "editing", "elephant", "animal", "year 3"],
    },
  },
]);
