import { defineQuestions } from "../helpers/create-question";

/**
 * Grade 3 ICAS-style Numeracy — 30 hand-authored questions, independently
 * blind re-solved before ingest. Curated-bank content: authored and
 * reviewed directly rather than generated, so it carries no
 * question-factory provenance and no gate chain.
 */
export const grade3IcasNumeracy = defineQuestions([
  {
    id: "icas-y3-num-measure-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A gardener wants to write down how long her garden hose is. The hose stretches from the tap all the way to the back fence. Which unit should she use to record the length of the hose?",
    options: [
      { id: "metres", text: "metres" },
      { id: "millimetres", text: "millimetres" },
      { id: "centimetres", text: "centimetres" },
      { id: "kilometres", text: "kilometres" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "metres",
    },
    explanation: "Match the unit to the size of the thing you are measuring. A hose that reaches across a backyard is a few big steps long, and one big step is about one metre, so metres give a sensible number like 20. Millimetres and centimetres are for small things you could hold, so the hose would come out as a huge number such as 2000 cm. Kilometres are for distances you travel, like the trip to school, so a hose would be a tiny fraction of one. Metres is the only unit that gives an easy, sensible number here.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Units of length",
      skill: "Choosing a sensible metric unit for a length",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["length", "metric units", "metres", "garden"],
    },
  },
  {
    id: "icas-y3-num-measure-002",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A market stall weighed four pumpkins and put the results in the chart. What is the total mass of the two heaviest pumpkins, in kilograms?",
    instructions: "Write just the number of kilograms, without the unit.",
    visuals: [
      {
        id: "visual-icas-y3-num-measure-002",
        type: "bar_chart",
        title: "Mass of Pumpkins at the Market Stall",
        altText: "Bar chart of pumpkin masses in kilograms: Grey 7, Butternut 4, Jap 6, Golden 5.",
        data: {
          labels: ["Grey", "Butternut", "Jap", "Golden"],
          values: [7, 4, 6, 5],
          xAxisLabel: "Pumpkin",
          yAxisLabel: "Mass (kg)",
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 13,
      tolerance: 0,
      unit: "kg",
    },
    explanation: "Two jobs here: first sort, then add. Read each bar against the scale and list the masses in order from largest to smallest: 7, 6, 5, 4. The two heaviest are the Grey pumpkin at 7 kg and the Jap pumpkin at 6 kg. Now add just those two: 7 + 6 = 13. The Golden and Butternut pumpkins are not needed at all, so leave them out. The total mass is 13 kg.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Mass",
      skill: "Reading masses from a bar chart and combining them",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["mass", "kilograms", "bar chart", "market"],
    },
  },
  {
    id: "icas-y3-num-measure-003",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A cafe listed how much each of its containers holds. Which container holds more than 1 litre?",
    options: [
      { id: "sports-bottle", text: "the sports bottle" },
      { id: "cordial-jug", text: "the cordial jug" },
      { id: "milk-carton", text: "the milk carton" },
      { id: "soup-thermos", text: "the soup thermos" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-num-measure-003",
        type: "table",
        title: "How Much Each Container Holds",
        altText: "Table of capacities: sports bottle 800 mL, milk carton 600 mL, cordial jug 1500 mL, soup thermos 450 mL.",
        data: {
          headers: ["Container", "Capacity"],
          rows: [
            ["Sports bottle", "800 mL"],
            ["Milk carton", "600 mL"],
            ["Cordial jug", "1500 mL"],
            ["Soup thermos", "450 mL"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "cordial-jug",
    },
    explanation: "Turn the litre into millilitres so everything is in the same unit: 1 litre = 1000 mL. Now compare each number in the table with 1000. The cordial jug holds 1500 mL, and 1500 is bigger than 1000, so it holds more than 1 litre. The sports bottle (800 mL), the milk carton (600 mL) and the soup thermos (450 mL) are all smaller than 1000 mL, so each of them holds less than 1 litre. Only the jug passes the test.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Capacity",
      skill: "Comparing capacities in millilitres and litres",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["capacity", "millilitres", "litres", "table"],
    },
  },
  {
    id: "icas-y3-num-measure-004",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A netball game begins at quarter past four in the afternoon. Which digital clock shows the starting time?",
    options: [
      { id: "t-403", text: "4:03 pm" },
      { id: "t-445", text: "4:45 pm" },
      { id: "t-415", text: "4:15 pm" },
      { id: "t-315", text: "3:15 pm" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "t-415",
    },
    explanation: "Split the phrase into two parts. 'Four' tells you the hour, so the first number is 4. 'Quarter past' means one quarter of the way round the hour, and a quarter of 60 minutes is 15 minutes past, so the second number is 15. That gives 4:15 pm. 4:03 pm comes from reading the big hand pointing at the 3 as '3 minutes' instead of counting in fives. 4:45 pm is quarter TO five, not quarter past four. 3:15 pm has the right minutes but the hour before the one named.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Time",
      skill: "Matching spoken time to digital time",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["time", "digital clock", "quarter past", "sport"],
    },
  },
  {
    id: "icas-y3-num-measure-005",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A baker wrote down when each tray went into the oven and when it came out. How many minutes were the pumpkin scones in the oven?",
    instructions: "Write just the number of minutes, without the unit.",
    visuals: [
      {
        id: "visual-icas-y3-num-measure-005",
        type: "table",
        title: "Baking Times",
        altText: "Table of baking times: pumpkin scones 3:45 pm to 4:20 pm, bread rolls 2:10 pm to 3:05 pm, banana muffins 4:30 pm to 4:55 pm.",
        data: {
          headers: ["Tray", "Into the oven", "Out of the oven"],
          rows: [
            ["Pumpkin scones", "3:45 pm", "4:20 pm"],
            ["Bread rolls", "2:10 pm", "3:05 pm"],
            ["Banana muffins", "4:30 pm", "4:55 pm"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 35,
      tolerance: 0,
      unit: "minutes",
    },
    explanation: "Find the scones row first and read across it: in at 3:45 pm, out at 4:20 pm. Now do not subtract 45 from 20, because time is not counted in hundreds. Hop to the next o'clock instead. From 3:45 pm to 4:00 pm is 15 minutes. From 4:00 pm to 4:20 pm is another 20 minutes. Add the two hops: 15 + 20 = 35. The scones were in the oven for 35 minutes. The other two rows belong to different trays, so ignore them.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Elapsed time",
      skill: "Finding elapsed time by counting on to the next hour",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["elapsed time", "minutes", "cooking"],
    },
  },
  {
    id: "icas-y3-num-measure-006",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The community garden club meets on the third Wednesday of May. Use the calendar to work out the date of that meeting.",
    options: [
      { id: "d8", text: "8 May" },
      { id: "d17", text: "17 May" },
      { id: "d22", text: "22 May" },
      { id: "d15", text: "15 May" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-num-measure-006",
        type: "table",
        title: "May Calendar",
        altText: "A May calendar with columns Monday to Sunday. May begins on Wednesday the 1st and ends on Friday the 31st.",
        data: {
          headers: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
          rows: [
            ["", "", "1", "2", "3", "4", "5"],
            ["6", "7", "8", "9", "10", "11", "12"],
            ["13", "14", "15", "16", "17", "18", "19"],
            ["20", "21", "22", "23", "24", "25", "26"],
            ["27", "28", "29", "30", "31", "", ""],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "d15",
    },
    explanation: "Find the Wednesday column first, then run your finger straight down it and count the dates as you go: 1 is the first Wednesday, 8 is the second, 15 is the third. So the club meets on 15 May. 8 May is only the second Wednesday, and 22 May is the fourth. 17 May sits in the Friday column, so it is a Friday, not a Wednesday at all. Counting down the column stops you slipping sideways into the wrong day.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Calendars",
      skill: "Locating a named weekday and date on a calendar",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["calendar", "months", "days of the week", "garden"],
    },
  },
  {
    id: "icas-y3-num-measure-007",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A bean plant was measured twice. The number line shows its height in April at the lower dot and its height in May at the higher dot, both in centimetres. How many centimetres did the bean plant grow between April and May?",
    instructions: "Write just the number of centimetres, without the unit.",
    visuals: [
      {
        id: "visual-icas-y3-num-measure-007",
        type: "number_line",
        title: "Height of the Bean Plant (cm)",
        altText: "Number line from 0 to 50 with ticks every 5. Point A is at 15 and point B is at 35.",
        data: {
          min: 0,
          max: 50,
          step: 5,
          highlightedValues: [15, 35],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 20,
      tolerance: 0,
      unit: "cm",
    },
    explanation: "Read each dot before you calculate. The ticks go up in fives, so the lower dot sits three ticks past 0, at 15 cm, and the higher dot sits seven ticks past 0, at 35 cm. Growth means the difference between the two, so count on from 15 to 35: that is 20 cm.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Length",
      skill: "Reading a scale and finding the difference between two points",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["number line", "length", "centimetres", "growth"],
    },
  },
  {
    id: "icas-y3-num-measure-008",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A vegetable patch is marked out with rope. It has four straight sides. Two of the sides are long and the other two are short, and every corner is a square corner. What shape is the vegetable patch?",
    options: [
      { id: "rectangle", text: "a rectangle" },
      { id: "square", text: "a square" },
      { id: "triangle", text: "a triangle" },
      { id: "trapezium", text: "a trapezium" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "rectangle",
    },
    explanation: "Tick off the clues one at a time. Four straight sides rules out the triangle, which has only three. Every corner being a square corner rules out the trapezium, whose sloping side makes corners that are not square. That leaves the square and the rectangle, and the clue 'two long sides and two short sides' decides between them: a square must have all four sides the same length, so it cannot be a square. A rectangle fits every clue.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "2D shapes",
      skill: "Identifying a 2D shape from its properties",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["2D shapes", "rectangle", "properties", "garden"],
    },
  },
  {
    id: "icas-y3-num-measure-009",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A cricket club paints capital letters on its equipment shed. Which letter has exactly one line of symmetry?",
    options: [
      { id: "letter-h", text: "H" },
      { id: "letter-a", text: "A" },
      { id: "letter-x", text: "X" },
      { id: "letter-s", text: "S" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "letter-a",
    },
    explanation: "A line of symmetry is a fold line where the two halves land exactly on top of each other. Test each letter by imagining folds. A folds down the middle from top to bottom and the two halves match, but a sideways fold does not match, so A has exactly one line. H matches on a top-to-bottom fold AND on a side-to-side fold, so it has two lines, which is too many. X matches on both of those folds as well, so it also has more than one. S matches on no fold at all; it only looks the same when you spin it around, which is turning, not folding. So A is the only letter with exactly one.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "Symmetry",
      skill: "Counting lines of symmetry in a figure",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["symmetry", "lines of symmetry", "letters", "sport"],
    },
  },
  {
    id: "icas-y3-num-measure-010",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A cheese stall packs its cheese in boxes shaped like a solid with 5 flat faces. Two of those faces are triangles and the other three are rectangles. Which solid are the boxes shaped like?",
    options: [
      { id: "cube", text: "a cube" },
      { id: "square-pyramid", text: "a square pyramid" },
      { id: "triangular-prism", text: "a triangular prism" },
      { id: "triangular-pyramid", text: "a triangular pyramid" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "triangular-prism",
    },
    explanation: "Count the faces of each solid and check their shapes. A triangular prism is a triangle at each end joined by three rectangles, which is 2 + 3 = 5 faces, exactly matching the clues. A cube has 6 faces and every one is a square, so it has no triangles at all. A square pyramid does have 5 faces, but they are 1 square and 4 triangles, so the numbers of triangles and rectangles are wrong. A triangular pyramid has only 4 faces, all triangles. Only the triangular prism has two triangles and three rectangles.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement and Geometry",
      topic: "3D objects",
      skill: "Identifying a 3D solid from the number and shape of its faces",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["3D objects", "faces", "prism", "market"],
    },
  },
  {
    id: "icas-y3-num-measure-012",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The chart shows the rainfall recorded at a weather station for four months. Which two months together had exactly 100 millimetres of rain?",
    options: [
      { id: "april-may", text: "April and May" },
      { id: "march-june", text: "March and June" },
      { id: "april-june", text: "April and June" },
      { id: "march-may", text: "March and May" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-num-measure-012",
        type: "bar_chart",
        title: "Rainfall at the Weather Station",
        altText: "Bar chart of rainfall in millimetres: March 40, April 25, May 60, June 35.",
        data: {
          labels: ["March", "April", "May", "June"],
          values: [40, 25, 60, 35],
          xAxisLabel: "Month",
          yAxisLabel: "Rainfall (mm)",
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "march-may",
    },
    explanation: "Read all four bars first and write the numbers down: March 40, April 25, May 60, June 35. Then test each pair by adding. March and May give 40 + 60 = 100, which is the target. April and May give 25 + 60 = 85, too little. March and June give 40 + 35 = 75. April and June give 25 + 35 = 60, the smallest pair of all. Only March and May reach exactly 100 mm.",
    metadata: {
      subject: "numeracy",
      strand: "Statistics and Probability",
      topic: "Data interpretation",
      skill: "Combining values read from a bar chart to match a total",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["bar chart", "data", "rainfall", "weather", "addition"],
    },
  },
  {
    id: "icas-y3-num-number-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A three-digit number has 4 hundreds. Its tens digit is 3 more than its hundreds digit. Its ones digit is 0. What is the number?",
    options: [
      { id: "opt-470", text: "470" },
      { id: "opt-430", text: "430" },
      { id: "opt-740", text: "740" },
      { id: "opt-407", text: "407" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-470",
    },
    explanation: "Build the number one place at a time and write the digits down as you go. Hundreds digit: 4. Tens digit: 3 more than 4, so 4 + 3 = 7. Ones digit: 0. Reading the places in order gives 4 hundreds, 7 tens, 0 ones, which is 470. If you chose 430 you used the 3 straight from the clue instead of adding it to 4. If you chose 740 you put the digits in the wrong places. If you chose 407 you gave the 7 to the ones column, but the clue describes the tens digit.",
    metadata: {
      subject: "numeracy",
      strand: "Number and place value",
      topic: "Place value to 1000",
      skill: "Building a three-digit number from place value clues",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["place value", "three-digit numbers", "reasoning"],
    },
  },
  {
    id: "icas-y3-num-number-002",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The school library shelf held 246 books on Monday morning. During the week 175 borrowed books were returned to the shelf and none were borrowed again. How many books are on the shelf at the end of the week?",
    visuals: [],
    answerKey: {
      kind: "number",
      value: 421,
      tolerance: 0,
    },
    explanation: "Returned books go back onto the shelf, so this is an addition: 246 + 175. Add one column at a time, starting from the ones. Ones: 6 + 5 = 11, so write 1 and carry 1 ten. Tens: 4 + 7 + 1 = 12 tens, so write 2 and carry 1 hundred. Hundreds: 2 + 1 + 1 = 4. The answer is 421. The two carries are where slips happen, so check that each carried digit was written into the next column before you add it.",
    metadata: {
      subject: "numeracy",
      strand: "Number and place value",
      topic: "Addition with regrouping",
      skill: "Adding three-digit numbers with two regroupings",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["addition", "regrouping", "library"],
    },
  },
  {
    id: "icas-y3-num-number-003",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The table shows how many people visited the community garden on three days. How many more people visited on the busiest day than on the quietest day?",
    visuals: [
      {
        id: "asset-icas-y3-num-number-003",
        type: "table",
        title: "Visitors to the community garden",
        altText: "A table showing visitors to the community garden: Monday 402, Tuesday 268, Wednesday 315.",
        data: {
          headers: ["Day", "Visitors"],
          rows: [
            ["Monday", "402"],
            ["Tuesday", "268"],
            ["Wednesday", "315"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 134,
      tolerance: 0,
    },
    explanation: "First decide which days you actually need. The busiest day is the largest number, 402 on Monday, and the quietest is the smallest, 268 on Tuesday, so Wednesday is not used at all. Now subtract: 402 - 268. There are no ones and no tens to take from, so regroup twice: 402 becomes 3 hundreds, 9 tens and 12 ones. Then 12 - 8 = 4 ones, 9 - 6 = 3 tens, 3 - 2 = 1 hundred, giving 134. Check by adding back: 268 + 134 = 402.",
    metadata: {
      subject: "numeracy",
      strand: "Number and place value",
      topic: "Subtraction with regrouping",
      skill: "Comparing table data using subtraction across a zero",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["subtraction", "regrouping", "table", "data"],
    },
  },
  {
    id: "icas-y3-num-number-004",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A fruit stall has 56 mangoes. The stallholder packs them into boxes with exactly 8 mangoes in each box, using all the mangoes. Before lunch she sells 3 of the boxes. How many boxes are left?",
    visuals: [],
    answerKey: {
      kind: "number",
      value: 4,
      tolerance: 0,
    },
    explanation: "This question has two steps, and the second one is easy to forget. Step 1: find how many boxes were packed by dividing, 56 divided by 8. Think of the times table: 8 times 7 is 56, so there are 7 boxes. Step 2: 3 boxes are sold, so take them away: 7 - 3 = 4. The answer is 4 boxes. Answering 7 means you stopped after the division; answering 53 means you subtracted from the mangoes instead of the boxes.",
    metadata: {
      subject: "numeracy",
      strand: "Number and algebra",
      topic: "Division facts in context",
      skill: "Using a division fact then subtracting in a two-step problem",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 80,
      tags: ["division", "two-step", "market"],
    },
  },
  {
    id: "icas-y3-num-number-005",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A baker cools 24 muffins on a rack. One quarter of them are blueberry muffins and the rest are banana muffins. How many banana muffins are there?",
    options: [
      { id: "opt-6", text: "6" },
      { id: "opt-18", text: "18" },
      { id: "opt-12", text: "12" },
      { id: "opt-20", text: "20" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "opt-18",
    },
    explanation: "A quarter means share the group into 4 equal parts, so 24 divided by 4 = 6 blueberry muffins. The question asks for the rest, so take that part away from the whole: 24 - 6 = 18 banana muffins. Underline the words 'the rest' before you start, because 6 is the answer to a question that was not asked. 12 is a half rather than a quarter, and 20 comes from subtracting the 4 in 'quarter' instead of sharing by it.",
    metadata: {
      subject: "numeracy",
      strand: "Fractions",
      topic: "Fractions of a group",
      skill: "Finding a quarter of a group and the remaining part",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["fractions", "quarter", "cooking"],
    },
  },
  {
    id: "icas-y3-num-number-007",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Two boxes of apples have exactly the same mass. When the two boxes are weighed together with a 15 kg bag of potatoes, the total mass is 41 kg. What is the mass of one box of apples?",
    instructions: "Write just the number of kilograms, without the unit.",
    visuals: [],
    answerKey: {
      kind: "number",
      value: 13,
      tolerance: 0,
      unit: "kg",
    },
    explanation: "Peel the problem back one step at a time. Take the potatoes off the scale first: 41 - 15 = 26 kg, and that 26 kg is the two boxes together. The boxes have the same mass, so share the 26 kg equally between them: 26 divided by 2 = 13 kg. Check it forwards: 13 + 13 + 15 = 41. Halving before subtracting would give the wrong answer, so always remove the odd item first.",
    metadata: {
      subject: "numeracy",
      strand: "Number and algebra",
      topic: "Missing-number reasoning",
      skill: "Working backwards to find an unknown that appears twice",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["missing number", "working backwards", "mass"],
    },
  },
  {
    id: "icas-y3-num-number-008",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The table shows the price list at the school canteen. A student has exactly $4.00 and wants to spend all of it on two different items. Which two items should the student choose?",
    options: [
      { id: "opt-sandwich-muffin", text: "a sandwich and a muffin" },
      { id: "opt-muffin-milk", text: "a muffin and a milk" },
      { id: "opt-sandwich-milk", text: "a sandwich and a milk" },
      { id: "opt-muffin-apple", text: "a muffin and an apple" },
    ],
    visuals: [
      {
        id: "asset-icas-y3-num-number-008",
        type: "table",
        title: "Canteen price list",
        altText: "A canteen price list: sandwich $2.50, muffin $2.00, milk $1.50, apple $1.00.",
        data: {
          headers: ["Item", "Price"],
          rows: [
            ["Sandwich", "$2.50"],
            ["Muffin", "$2.00"],
            ["Milk", "$1.50"],
            ["Apple", "$1.00"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "opt-sandwich-milk",
    },
    explanation: "The word 'exactly' means you must test the totals rather than guess. Add each pair from the price list: sandwich and milk is $2.50 + $1.50 = $4.00, which is exactly right because the 50c parts join to make a whole dollar. Sandwich and muffin is $4.50, which is too much. Muffin and milk is $3.50 and muffin and apple is $3.00, so both leave money unspent. Only the sandwich and milk pair uses all $4.00.",
    metadata: {
      subject: "numeracy",
      strand: "Money and financial mathematics",
      topic: "Adding amounts of money",
      skill: "Choosing items that total an exact amount of money",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["money", "table", "addition", "canteen"],
    },
  },
  {
    id: "icas-y3-num-number-009",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Four classes collected packs of stickers for a swap day, as shown in the graph. Every pack holds 5 stickers. How many more stickers did Koala class collect than Possum class?",
    visuals: [
      {
        id: "asset-icas-y3-num-number-009",
        type: "bar_chart",
        title: "Packs of stickers collected",
        altText: "A bar chart of packs collected: Emu 4, Koala 7, Possum 3, Rosella 6.",
        data: {
          labels: ["Emu", "Koala", "Possum", "Rosella"],
          values: [4, 7, 3, 6],
          xAxisLabel: "Class",
          yAxisLabel: "Packs collected",
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 20,
      tolerance: 0,
    },
    explanation: "The bars count packs, not stickers, so read the bars first and convert afterwards. Koala has 7 packs and Possum has 3 packs, a difference of 7 - 3 = 4 packs. Each pack holds 5 stickers, so the difference in stickers is 4 groups of 5, which is 4 x 5 = 20. You can also multiply first: Koala 7 x 5 = 35 and Possum 3 x 5 = 15, and 35 - 15 = 20, which is the same answer. Stopping at 4 answers the question in packs instead of stickers.",
    metadata: {
      subject: "numeracy",
      strand: "Statistics",
      topic: "Multiplication from graph data",
      skill: "Reading a bar chart and multiplying to compare totals",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 100,
      tags: ["bar chart", "multiplication", "data", "difference"],
    },
  },
  {
    id: "icas-y3-num-number-010",
    type: "ordering",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Four number cards were made for a maths game. Each card shows a number in a different way. Put the cards in order from the smallest number to the largest number.",
    interaction: {
      type: "ordering",
      items: [
        {
          id: "card-460",
          text: "460",
        },
        {
          id: "card-forty-six",
          text: "forty-six",
        },
        {
          id: "card-six-hundreds-four-tens",
          text: "6 hundreds and 4 tens",
        },
        {
          id: "card-four-hundred-and-six",
          text: "four hundred and six",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["card-forty-six", "card-four-hundred-and-six", "card-460", "card-six-hundreds-four-tens"],
    },
    explanation: "Turn every card into digits before comparing anything. 'Forty-six' is 46, 'four hundred and six' is 406 with a zero holding the empty tens place, '460' is already digits, and '6 hundreds and 4 tens' is 640. Now compare: 46 has only two digits so it is smallest. The other three all have 4, 4 and 6 hundreds, so 406 and 460 come before 640, and between those two the tens decide, since 0 tens is less than 6 tens. The order is 46, 406, 460, 640.",
    metadata: {
      subject: "numeracy",
      strand: "Number and place value",
      topic: "Ordering numbers to 1000",
      skill: "Ordering numbers written in words, digits and place-value form",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 110,
      tags: ["ordering", "place value", "number words"],
    },
  },
  {
    id: "icas-y3-num-number-011",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The graph shows how many eggs were collected from the school chicken coop each school day. Which THREE statements about the graph are true?",
    options: [
      { id: "opt-two-days-under-nine", text: "Exactly two days had fewer than 9 eggs." },
      { id: "opt-wed-most", text: "More eggs were collected on Wednesday than on any other day." },
      { id: "opt-mon-thu-equals-wed", text: "Monday and Thursday together give the same number of eggs as Wednesday." },
      { id: "opt-fifty-total", text: "Fifty eggs were collected in the whole week." },
      { id: "opt-tue-double-thu", text: "Tuesday's number of eggs is double Thursday's number." },
    ],
    visuals: [
      {
        id: "asset-icas-y3-num-number-011",
        type: "bar_chart",
        title: "Eggs collected each school day",
        altText: "A bar chart of eggs collected: Monday 12, Tuesday 8, Wednesday 15, Thursday 6, Friday 9.",
        data: {
          labels: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
          values: [12, 8, 15, 6, 9],
          xAxisLabel: "Day",
          yAxisLabel: "Eggs collected",
        },
      },
    ],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["opt-wed-most", "opt-fifty-total", "opt-two-days-under-nine"],
    },
    explanation: "Test each statement against the bars instead of judging by eye. Wednesday's bar reaches 15, higher than 12, 8, 6 and 9, so that statement is true. Monday and Thursday give 12 + 6 = 18, which is more than 15, so that one is false. The whole week is 12 + 8 + 15 + 6 + 9; pair the friendly numbers, 12 + 8 = 20 and 15 + 6 + 9 = 30, making 50, so that is true. Double Thursday's 6 is 12, not Tuesday's 8, so that is false. Fewer than 9 means 8 and 6 only, since Friday's 9 is not fewer than 9, so exactly two days qualify and that statement is true.",
    metadata: {
      subject: "numeracy",
      strand: "Statistics",
      topic: "Interpreting a bar chart",
      skill: "Checking statements about graph data by calculating",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 150,
      tags: ["bar chart", "addition", "doubling", "comparison"],
    },
  },
  {
    id: "icas-y3-num-number-012",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A hardware shop sells pegs in packets. A sign says: '3 packets of 9 pegs give you more pegs than 4 packets of 7 pegs.' Is the sign correct?",
    visuals: [],
    answerKey: {
      kind: "boolean",
      value: false,
    },
    explanation: "Do not compare the packet numbers on their own; work out both totals. Three packets of 9 is 3 x 9 = 27 pegs. Four packets of 7 is 4 x 7 = 28 pegs. Since 28 is greater than 27, the second choice gives more pegs, so the sign is wrong and the answer is false. It is close, only one peg apart, which is why the totals must be calculated rather than guessed from the bigger packet size.",
    metadata: {
      subject: "numeracy",
      strand: "Number and algebra",
      topic: "Multiplication facts in context",
      skill: "Comparing two multiplication totals to judge a claim",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["multiplication", "comparison", "true or false", "shop"],
    },
  },
  {
    id: "icas-y3-numeracy-c-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Ben has 24 stickers. His sister has half as many stickers as Ben. His friend has double the number the sister has. How many stickers does the friend have?",
    instructions: "Choose one answer.",
    options: [
      { id: "n12", text: "12" },
      { id: "n48", text: "48" },
      { id: "n6", text: "6" },
      { id: "n24", text: "24" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "n24",
    },
    explanation: "Do it in two steps. Half of 24 is 12, so the sister has 12. Double 12 is 24, so the friend has 24. Halving and then doubling the same amount brings you back to where you started, which is why the friend matches Ben.",
    metadata: {
      subject: "numeracy",
      strand: "Number and Algebra",
      topic: "Doubling and halving",
      skill: "Doubling and halving to solve problems",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["doubling", "halving", "two-step"],
    },
  },
  {
    id: "icas-y3-numeracy-c-002",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A farmer packs eggs into cartons. Each carton holds exactly 6 eggs. She has 27 eggs and fills as many cartons as she can. How many cartons end up completely full?",
    instructions: "Choose one answer.",
    options: [
      { id: "n4", text: "4" },
      { id: "n5", text: "5" },
      { id: "n3", text: "3" },
      { id: "n6", text: "6" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "n4",
    },
    explanation: "Share 27 into groups of 6: 6, 12, 18, 24 uses four cartons and 24 eggs. That leaves 3 eggs, which is not enough to fill a fifth carton. So only 4 cartons are completely full. The 3 leftover eggs are the remainder, not a full carton.",
    metadata: {
      subject: "numeracy",
      strand: "Number and Algebra",
      topic: "Division with remainders",
      skill: "Sharing with a remainder and interpreting what is left",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["division", "remainder", "grouping"],
    },
  },
  {
    id: "icas-y3-numeracy-c-003",
    type: "ordering",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Put these three-digit numbers in order from the smallest to the largest.",
    instructions: "Drag the numbers into order, smallest first.",
    interaction: {
      type: "ordering",
      items: [
        {
          id: "n219",
          text: "219",
        },
        {
          id: "n291",
          text: "291",
        },
        {
          id: "n129",
          text: "129",
        },
        {
          id: "n192",
          text: "192",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["n129", "n192", "n219", "n291"],
    },
    explanation: "Look at the hundreds digit first: 129 and 192 both start with 1, so they are smaller than 219 and 291 which start with 2. Between 129 and 192, compare the tens: 2 tens is less than 9 tens, so 129 comes first. Between 219 and 291, 1 ten is less than 9 tens, so 219 comes before 291. The order is 129, 192, 219, 291.",
    metadata: {
      subject: "numeracy",
      strand: "Number and Algebra",
      topic: "Place value",
      skill: "Ordering three-digit numbers",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["ordering", "place value", "three-digit"],
    },
  },
  {
    id: "icas-y3-numeracy-c-004",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Use the price list at the school fair stall. Priya buys 2 sausages and 1 drink. How much does she spend altogether?",
    instructions: "Write just the number of dollars, without the unit.",
    visuals: [
      {
        id: "visual-icas-y3-numeracy-c-004-1",
        type: "table",
        altText: "Price list: Drink $3, Sausage $4, Cupcake $2, Popcorn $5.",
        data: {
          headers: ["Item", "Price"],
          rows: [
            ["Drink", "$3"],
            ["Sausage", "$4"],
            ["Cupcake", "$2"],
            ["Popcorn", "$5"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 11,
      tolerance: 0,
      unit: "dollars",
    },
    explanation: "This takes two steps. First the sausages: 2 sausages at $4 each is 2 x 4 = $8. Then add the drink: $8 + $3 = $11. Read the price list carefully, because the sausage is not the dearest item, so you must use its own price of $4.",
    metadata: {
      subject: "numeracy",
      strand: "Number and Algebra",
      topic: "Money and two-step problems",
      skill: "Two-step word problems with money",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 100,
      tags: ["money", "two-step", "table"],
    },
  },
  {
    id: "icas-y3-numeracy-c-005",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A shelf holds 76 books. Rounded to the nearest ten, about how many books is that?",
    instructions: "Choose one answer.",
    options: [
      { id: "n70", text: "70" },
      { id: "n80", text: "80" },
      { id: "n76", text: "76" },
      { id: "n100", text: "100" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "n80",
    },
    explanation: "76 sits between 70 and 80. Count the gap each way: from 76 to 70 is 6, but from 76 to 80 is only 4. Because 76 is closer to 80, it rounds up to 80 when rounding to the nearest ten.",
    metadata: {
      subject: "numeracy",
      strand: "Number and Algebra",
      topic: "Rounding and estimation",
      skill: "Rounding a two-digit number to the nearest ten",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["rounding", "estimation", "nearest ten"],
    },
  },
  {
    id: "icas-y3-numeracy-c-006",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The column graph shows how many shells four friends collected at the beach. How many more shells did the friend who collected the most collect than the friend who collected the least?",
    instructions: "Choose one answer.",
    options: [
      { id: "n15", text: "15" },
      { id: "n22", text: "22" },
      { id: "n8", text: "8" },
      { id: "n7", text: "7" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-numeracy-c-006-1",
        type: "bar_chart",
        altText: "Column graph of shells collected: Tom 12, Bea 7, Sam 15, Ivy 9.",
        data: {
          labels: ["Tom", "Bea", "Sam", "Ivy"],
          values: [12, 7, 15, 9],
          xAxisLabel: "Friend",
          yAxisLabel: "Shells collected",
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "n8",
    },
    explanation: "First find the most and the least from the columns: Sam has the tallest column at 15 and Bea has the shortest at 7. 'How many more' means subtract: 15 - 7 = 8. Be careful not to add them (that gives 22) or to read off just one column.",
    metadata: {
      subject: "numeracy",
      strand: "Statistics and Probability",
      topic: "Interpreting column graphs",
      skill: "Comparing values on a column graph",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["column graph", "difference", "data"],
    },
  },
  {
    id: "icas-y3-numeracy-c-007",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The table shows how many laps four children ran on Monday and Tuesday. Who ran the most laps altogether across the two days?",
    instructions: "Choose one answer.",
    options: [
      { id: "zoe", text: "Zoe" },
      { id: "leo", text: "Leo" },
      { id: "ava", text: "Ava" },
      { id: "kai", text: "Kai" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-numeracy-c-007-1",
        type: "table",
        altText: "Laps run. Ava: Mon 8, Tue 5. Kai: Mon 6, Tue 9. Leo: Mon 7, Tue 7. Zoe: Mon 9, Tue 4.",
        data: {
          headers: ["Child", "Monday", "Tuesday"],
          rows: [
            ["Ava", "8", "5"],
            ["Kai", "6", "9"],
            ["Leo", "7", "7"],
            ["Zoe", "9", "4"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "kai",
    },
    explanation: "You must add each child's two days, not just look at one column. Ava: 8 + 5 = 13. Kai: 6 + 9 = 15. Leo: 7 + 7 = 14. Zoe: 9 + 4 = 13. Kai has the biggest total with 15. Zoe ran the most on Monday, but her small Tuesday means she is not the overall winner.",
    metadata: {
      subject: "numeracy",
      strand: "Statistics and Probability",
      topic: "Interpreting tables",
      skill: "Reasoning with two-way data in a table",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["table", "totals", "reasoning"],
    },
  },
  {
    id: "icas-y3-numeracy-c-008",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The number line below is marked with a tick every 5. Two dots are shown on the line. How many steps of 5 are there from the left dot to the right dot?",
    instructions: "Write your answer as a number.",
    visuals: [
      {
        id: "visual-icas-y3-numeracy-c-008-1",
        type: "number_line",
        altText: "A number line from 0 to 40 with a tick every 5. Dots are marked at 10 and 30.",
        data: {
          min: 0,
          max: 40,
          step: 5,
          highlightedValues: [10, 30],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 4,
      tolerance: 0,
    },
    explanation: "Find where each dot sits by counting ticks of 5 from 0: the left dot is on 10 and the right dot is on 30. To get from 10 to 30 you count the gaps of 5 between them: 10 to 15, 15 to 20, 20 to 25, 25 to 30. That is 4 steps. You can also work it out as 30 - 10 = 20, and 20 divided into steps of 5 is 4.",
    metadata: {
      subject: "numeracy",
      strand: "Number and Algebra",
      topic: "Number lines",
      skill: "Reading positions and steps on a number line",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 110,
      tags: ["number line", "skip counting", "steps"],
    },
  },
]);
