import { defineQuestions } from "../helpers/create-question";

/**
 * Grade 3 ICAS-style Science — 35 hand-authored questions across the
 * Biological, Chemical, Physical and Earth and Space strands. NAPLAN does
 * not assess Science, so this programme is ICAS-only.
 */
export const grade3IcasScience = defineQuestions([
  {
    id: "icas-y3-science-b-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Meera is making an umbrella to keep the rain off her head. Which material is the best choice for the top of the umbrella?",
    options: [
      { id: "plastic", text: "thin waterproof plastic" },
      { id: "paper", text: "a piece of thin dry paper" },
      { id: "wool", text: "a woollen jumper" },
      { id: "metal", text: "a sheet of metal" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "plastic",
    },
    explanation: "An umbrella top must stop water and still be light and bendy so it can open and close. Waterproof plastic keeps the water out, while paper and wool both soak the rain up, and a metal sheet is too heavy and stiff to fold.",
    metadata: {
      subject: "science",
      strand: "Chemical sciences",
      topic: "Properties of everyday materials",
      skill: "Choosing a suitable material for a job",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["materials", "properties", "waterproof"],
    },
  },
  {
    id: "icas-y3-science-b-002",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A wooden building block keeps the same shape when you lift it out of a box and put it on a table. Is this statement true or false?",
    options: [],
    visuals: [],
    answerKey: {
      kind: "boolean",
      value: true,
    },
    explanation: "Solids like a wooden block hold their own shape wherever you put them. Only liquids and gases change shape to fit their container, so the block stays the same shape on the table as it was in the box.",
    metadata: {
      subject: "science",
      strand: "Chemical sciences",
      topic: "States of matter",
      skill: "Recognising that solids keep their shape",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["solids", "liquids", "shape"],
    },
  },
  {
    id: "icas-y3-science-b-003",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Ravi leaves a hard chocolate bar on a sunny windowsill. After an hour it has turned soft and runny. What made the chocolate change?",
    options: [
      { id: "cold", text: "Cold from the window froze it" },
      { id: "heat", text: "Heat from the sun melted it" },
      { id: "dried", text: "The sun dried the water out of it" },
      { id: "soaked", text: "It soaked up rain from the air" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "heat",
    },
    explanation: "Melting is when heat turns a solid into a liquid. The sun warmed the chocolate until the solid turned runny. Cold would make it harder, not softer, and drying or soaking up rain would not turn a solid into liquid.",
    metadata: {
      subject: "science",
      strand: "Chemical sciences",
      topic: "Changes caused by heating",
      skill: "Melting: solids turning to liquid when heated",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["melting", "heat", "change"],
    },
  },
  {
    id: "icas-y3-science-b-004",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Tom stirs a spoon of sugar into a glass of warm water. The sugar seems to disappear, but the water tastes sweet. What has happened to the sugar?",
    options: [
      { id: "melted", text: "It has melted away" },
      { id: "floated", text: "It floated to the top" },
      { id: "dissolved", text: "It has dissolved in the water" },
      { id: "gone", text: "It has vanished" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "dissolved",
    },
    explanation: "When sugar dissolves it breaks into tiny bits that spread all through the water, so you cannot see it, but you can still taste it. The sugar is still there. Melting needs heat and is different, and the sugar has not floated or truly vanished.",
    metadata: {
      subject: "science",
      strand: "Chemical sciences",
      topic: "Mixing and dissolving",
      skill: "Dissolving a solid in water",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["dissolving", "mixing", "water"],
    },
  },
  {
    id: "icas-y3-science-b-005",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A push moves something away from you. Which of these actions use a PUSH force? Choose all that are correct.",
    options: [
      { id: "open-drawer", text: "Sliding a drawer towards you" },
      { id: "press-doorbell", text: "Pressing a doorbell button" },
      { id: "kick-football", text: "Kicking a football forwards" },
      { id: "pull-wagon", text: "Pulling a wagon by its handle" },
    ],
    visuals: [],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["press-doorbell", "kick-football"],
    },
    explanation: "A push moves something away from you. Pressing a doorbell pushes the button in, and kicking pushes the ball forwards. Pulling a wagon and sliding a drawer towards you both bring things closer, so those are pulls, not pushes.",
    metadata: {
      subject: "science",
      strand: "Physical sciences",
      topic: "Forces",
      skill: "Identifying pushes and pulls",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["forces", "push", "pull"],
    },
  },
  {
    id: "icas-y3-science-b-006",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Priya rolled the same toy car down a ramp. Each time she raised the ramp higher and measured how far the car rolled. Look at her results table. How far did the car roll when the ramp was 30 cm high?",
    instructions: "Write just the number of centimetres, without the unit.",
    options: [],
    visuals: [
      {
        id: "visual-icas-y3-science-b-006-1",
        type: "table",
        altText: "Results table: ramp 10 cm rolled 40 cm, ramp 20 cm rolled 75 cm, ramp 30 cm rolled 110 cm, ramp 40 cm rolled 150 cm.",
        data: {
          headers: ["Ramp height (cm)", "Distance rolled (cm)"],
          rows: [
            ["10", "40"],
            ["20", "75"],
            ["30", "110"],
            ["40", "150"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 110,
      tolerance: 0,
      unit: "cm",
    },
    explanation: "Find the row where the ramp height is 30 cm, then read across to the distance column. The car rolled 110 cm from that ramp height.",
    metadata: {
      subject: "science",
      strand: "Physical sciences",
      topic: "Movement on ramps",
      skill: "Reading a value from a ramp results table",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["ramps", "movement", "table"],
    },
  },
  {
    id: "icas-y3-science-b-007",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Kai put four objects into a tub of water and wrote down what happened to each one. Look at the table. Which object sank?",
    options: [
      { id: "spoon", text: "Metal spoon" },
      { id: "cork", text: "Cork" },
      { id: "peg", text: "Wooden peg" },
      { id: "lid", text: "Plastic lid" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-science-b-007-1",
        type: "table",
        altText: "Table of what happened in water: Cork floated, Plastic lid floated, Metal spoon sank, Wooden peg floated.",
        data: {
          headers: ["Object", "What happened"],
          rows: [
            ["Cork", "Floated"],
            ["Plastic lid", "Floated"],
            ["Metal spoon", "Sank"],
            ["Wooden peg", "Floated"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "spoon",
    },
    explanation: "Read down the 'What happened' column and find the object marked 'Sank'. Only the metal spoon sank; the cork, plastic lid and wooden peg all floated.",
    metadata: {
      subject: "science",
      strand: "Physical sciences",
      topic: "Floating and sinking",
      skill: "Reading float and sink results from a table",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["floating", "sinking", "table"],
    },
  },
  {
    id: "icas-y3-science-b-008",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Lin holds a magnet close to four objects, one at a time. Which object will the magnet pull towards itself?",
    options: [
      { id: "button", text: "A plastic coat button" },
      { id: "clip", text: "A steel paperclip" },
      { id: "block", text: "A wooden block" },
      { id: "band", text: "A rubber band" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "clip",
    },
    explanation: "Magnets pull on things made of iron or steel. The paperclip is steel, so the magnet attracts it. Plastic, wood and rubber are not magnetic, so the magnet does not pull them at all.",
    metadata: {
      subject: "science",
      strand: "Physical sciences",
      topic: "Magnets",
      skill: "Knowing which materials a magnet attracts",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["magnets", "materials", "attract"],
    },
  },
  {
    id: "icas-y3-science-b-009",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Sam plucks a guitar string. He hears a sound and sees the string shaking quickly. What makes the sound?",
    options: [
      { id: "colour", text: "The colour of the string" },
      { id: "still", text: "The string staying perfectly still" },
      { id: "vibrate", text: "The string vibrating quickly" },
      { id: "light", text: "The light shining on it" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "vibrate",
    },
    explanation: "Sounds are made when something vibrates, which means it shakes quickly back and forth. The shaking string pushes the air and carries the sound to Sam's ears. Colour, light and a still string do not make any sound.",
    metadata: {
      subject: "science",
      strand: "Physical sciences",
      topic: "Sound",
      skill: "Understanding that vibrations make sound",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["sound", "vibration", "energy"],
    },
  },
  {
    id: "icas-y3-science-b-010",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "On a sunny day Ava stands in the playground and sees a dark shadow on the ground behind her. Why does the shadow appear?",
    options: [
      { id: "moved", text: "The sun moved away" },
      { id: "makes", text: "Her body makes light" },
      { id: "paint", text: "The ground is dark paint" },
      { id: "blocks", text: "Her body blocks the sunlight" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "blocks",
    },
    explanation: "A shadow forms where an object stops light from reaching a surface. Ava's body blocks the sun's light, so the ground behind her stays dark. Her body does not make its own light, and the dark patch is a shadow, not paint.",
    metadata: {
      subject: "science",
      strand: "Physical sciences",
      topic: "Light and shadows",
      skill: "Explaining how shadows are formed",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["light", "shadow", "sun"],
    },
  },
  {
    id: "icas-y3-science-b-011",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Noah grew two bean plants to test whether light helps them grow. The table shows how he set each plant up. What did Noah change between the two plants?",
    options: [
      { id: "light", text: "The amount of light" },
      { id: "water", text: "The amount of water" },
      { id: "soil", text: "The type of soil" },
      { id: "pot", text: "The size of the pot" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-science-b-011-1",
        type: "table",
        altText: "Setup table: Light row shows Plant 1 on the windowsill and Plant 2 in a dark cupboard; water is 1 cup for both; soil is the same for both.",
        data: {
          headers: ["What we set up", "Plant 1", "Plant 2"],
          rows: [
            ["Light", "On the windowsill", "In a dark cupboard"],
            ["Water each day", "1 cup", "1 cup"],
            ["Soil", "Same soil", "Same soil"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "light",
    },
    explanation: "Look along each row for the thing that is different between Plant 1 and Plant 2. The water and the soil are the same for both plants; only the light is different (windowsill versus dark cupboard). That is the one thing Noah changed.",
    metadata: {
      subject: "science",
      strand: "Science inquiry",
      topic: "Fair testing",
      skill: "Identifying the variable that was changed",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["experiment", "variable", "fair test"],
    },
  },
  {
    id: "icas-y3-science-b-012",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Zara tested which paper towel soaks up the most water. She poured the same amount of water on each towel and used towels of the same size. Why did she keep those things the same?",
    options: [
      { id: "useup", text: "To use up all the water" },
      { id: "fair", text: "To make the test fair" },
      { id: "faster", text: "To make the test finish faster" },
      { id: "biggest", text: "To use the biggest towel" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "fair",
    },
    explanation: "In a fair test you change only one thing and keep everything else the same. By using the same amount of water and the same size towel, the only difference left is the kind of towel, so the result really shows which towel soaks up the most.",
    metadata: {
      subject: "science",
      strand: "Science inquiry",
      topic: "Fair testing",
      skill: "Explaining why some things are kept the same",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["experiment", "fair test", "controlled"],
    },
  },
  {
    id: "icas-y3-science-b-013",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The graph shows how tall Ben's sunflower was at the end of each week. What does the graph show about the sunflower?",
    options: [
      { id: "same", text: "It stayed the same" },
      { id: "smaller", text: "It got smaller" },
      { id: "taller", text: "It grew taller every week" },
      { id: "updown", text: "It went up then down" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-science-b-013-1",
        type: "line_graph",
        altText: "Line graph of sunflower height: Week 1 is 5 cm, Week 2 is 12 cm, Week 3 is 20 cm, Week 4 is 28 cm.",
        data: {
          points: [
            {
              x: 1,
              y: 5,
              label: "Week 1",
            },
            {
              x: 2,
              y: 12,
              label: "Week 2",
            },
            {
              x: 3,
              y: 20,
              label: "Week 3",
            },
            {
              x: 4,
              y: 28,
              label: "Week 4",
            },
          ],
          xAxisLabel: "Week",
          yAxisLabel: "Height (cm)",
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "taller",
    },
    explanation: "Read the height at the end of each week: 5, then 12, then 20, then 28 cm. Every point on the line is higher than the one before, so the sunflower grew taller every week. It never stayed level or dropped down.",
    metadata: {
      subject: "science",
      strand: "Science inquiry",
      topic: "Interpreting results",
      skill: "Drawing a conclusion from a line graph",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["graph", "conclusion", "growth"],
    },
  },
  {
    id: "icas-y3-science-b-014",
    type: "ordering",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Mia wants to test which ball bounces the highest. Put her steps in the correct order, from first to last.",
    options: [],
    interaction: {
      type: "ordering",
      items: [
        {
          id: "drop",
          text: "Drop each ball from the same height",
        },
        {
          id: "measure",
          text: "Measure how high each ball bounces",
        },
        {
          id: "record",
          text: "Write the bounce heights in a table",
        },
        {
          id: "decide",
          text: "Decide which ball bounced the highest",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["drop", "measure", "record", "decide"],
    },
    explanation: "First you do the test the same way each time by dropping each ball from the same height. Then you measure the bounce, then write the numbers down, and only after you have all the results can you decide which ball bounced highest.",
    metadata: {
      subject: "science",
      strand: "Science inquiry",
      topic: "Steps of a method",
      skill: "Ordering the steps of an investigation",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["method", "ordering", "investigation"],
    },
  },
  {
    id: "icas-y3-science-b-015",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Match each material to the property that makes it useful.",
    options: [],
    interaction: {
      type: "matching",
      sources: [
        {
          id: "glass",
          text: "Glass",
        },
        {
          id: "wool",
          text: "Wool",
        },
        {
          id: "rubber",
          text: "Rubber",
        },
        {
          id: "steel",
          text: "Steel",
        },
      ],
      targets: [
        {
          id: "seethrough",
          text: "You can see through it",
        },
        {
          id: "warm",
          text: "It keeps you warm",
        },
        {
          id: "stretch",
          text: "It stretches and bounces back",
        },
        {
          id: "strong",
          text: "It is strong and hard",
        },
        {
          id: "floats",
          text: "It floats easily on water",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "glass",
          targetId: "seethrough",
        },
        {
          sourceId: "wool",
          targetId: "warm",
        },
        {
          sourceId: "rubber",
          targetId: "stretch",
        },
        {
          sourceId: "steel",
          targetId: "strong",
        },
      ],
    },
    explanation: "Think about what each material is used for. Glass windows let you see through them, woollen jumpers trap warmth, rubber bands stretch and spring back, and steel is strong and hard for tools and frames. 'Floats easily on water' does not match any of these four.",
    metadata: {
      subject: "science",
      strand: "Chemical sciences",
      topic: "Properties of materials",
      skill: "Matching materials to their useful properties",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 80,
      tags: ["materials", "properties", "matching"],
    },
  },
  {
    id: "icas-y3-science-b-016",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Tom rolled the same toy car across four different surfaces and measured how far it went each time. Look at the chart. How far did the car roll on the wood floor?",
    instructions: "Write just the number of centimetres, without the unit.",
    options: [],
    visuals: [
      {
        id: "visual-icas-y3-science-b-016-1",
        type: "bar_chart",
        altText: "Bar chart of how far a car rolled on four surfaces: Carpet 30 cm, Wood 80 cm, Tile 120 cm, Grass 20 cm.",
        data: {
          labels: ["Carpet", "Wood", "Tile", "Grass"],
          values: [30, 80, 120, 20],
          xAxisLabel: "Surface",
          yAxisLabel: "Distance rolled (cm)",
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 80,
      tolerance: 0,
      unit: "cm",
    },
    explanation: "Find the bar labelled 'Wood' and read its height against the scale on the side. The wood bar reaches 80, so the car rolled 80 cm on the wood floor.",
    metadata: {
      subject: "science",
      strand: "Physical sciences",
      topic: "Movement and surfaces",
      skill: "Reading a value from a bar chart",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["bar chart", "movement", "surfaces"],
    },
  },
  {
    id: "icas-y3-science-b-017",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The table shows how warm the water was in three cups 10 minutes after it was poured. Claim: 'The cup with no cover stayed the warmest.' Use the table to decide if the claim is true or false.",
    options: [],
    visuals: [
      {
        id: "visual-icas-y3-science-b-017-1",
        type: "table",
        altText: "Table of water temperature after 10 minutes: no cover 30 degrees, paper lid 34 degrees, plastic lid 38 degrees.",
        data: {
          headers: ["Cup", "Cover", "Temperature after 10 min (°C)"],
          rows: [
            ["Cup 1", "No cover", "30"],
            ["Cup 2", "Paper lid", "34"],
            ["Cup 3", "Plastic lid", "38"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "boolean",
      value: false,
    },
    explanation: "Read the temperature column. The cup with no cover was 30 °C, the paper lid was 34 °C and the plastic lid was 38 °C. The no-cover cup was the coolest, not the warmest, so the claim is false.",
    metadata: {
      subject: "science",
      strand: "Science inquiry",
      topic: "Interpreting results",
      skill: "Checking a claim against a results table",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 80,
      tags: ["table", "claim", "results"],
    },
  },
  {
    id: "icas-y3-science-b-018",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A class wants a lid for a fish tank that you can see through and that will not break easily. The table lists some materials. Which material is the best choice?",
    options: [
      { id: "glass", text: "Sheet glass" },
      { id: "wood", text: "Solid wood" },
      { id: "cardboard", text: "Thick cardboard" },
      { id: "plastic", text: "Clear plastic" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-science-b-018-1",
        type: "table",
        altText: "Material table: Clear plastic see-through yes breaks easily no; Sheet glass see-through yes breaks easily yes; Solid wood see-through no breaks easily no; Thick cardboard see-through no breaks easily yes.",
        data: {
          headers: ["Material", "See-through?", "Breaks easily?"],
          rows: [
            ["Clear plastic", "Yes", "No"],
            ["Sheet glass", "Yes", "Yes"],
            ["Solid wood", "No", "No"],
            ["Thick cardboard", "No", "Yes"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "plastic",
    },
    explanation: "The lid must be see-through (Yes) and must not break easily (No). Check both columns together. Glass is see-through but breaks easily; wood and cardboard are not see-through. Only clear plastic is both see-through and hard to break, so it is the best choice.",
    metadata: {
      subject: "science",
      strand: "Chemical sciences",
      topic: "Choosing materials",
      skill: "Using a properties table to pick the best material",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["materials", "properties", "table"],
    },
  },
  {
    id: "icas-y3-science-a-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A desert lizard hides under a large rock during the hottest part of the day and comes out to hunt in the cool evening. How does hiding under the rock help the lizard survive?",
    options: [
      { id: "more-food", text: "It helps the lizard find more food to eat." },
      { id: "water", text: "It gives the lizard water to drink." },
      { id: "cool-shade", text: "It keeps the lizard cool and shaded from the hot sun." },
      { id: "moonlight", text: "It hides the lizard from the moonlight." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "cool-shade",
    },
    explanation: "Deserts get very hot in the middle of the day. The shade under a rock is much cooler than the open sand, so the lizard does not overheat. Hiding does not create food or water for it, and moonlight is not a problem during the hot day.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Animal adaptations",
      skill: "Explaining how a feature or behaviour helps an animal survive in its habitat",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["living things", "survival", "habitat", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-002",
    type: "ordering",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A frog changes as it grows. Put these stages of a frog's life cycle in order, starting with the very first stage.",
    interaction: {
      type: "ordering",
      items: [
        {
          id: "tadpole",
          text: "A tadpole swimming in water",
        },
        {
          id: "frog",
          text: "An adult frog",
        },
        {
          id: "egg",
          text: "Frog eggs (frogspawn)",
        },
        {
          id: "froglet",
          text: "A young froglet with legs and a short tail",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["egg", "tadpole", "froglet", "frog"],
    },
    explanation: "A frog begins as jelly-like eggs. The eggs hatch into tadpoles that live in water. Each tadpole slowly grows legs to become a froglet, and finally becomes an adult frog that can live on land.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Life cycles",
      skill: "Ordering the stages of a frog's life cycle",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["life cycle", "frog", "ordering", "growth"],
    },
  },
  {
    id: "icas-y3-science-a-003",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A butterfly lays tiny eggs on a leaf. A few days later, something hatches from each egg. What comes out of a butterfly's egg first?",
    options: [
      { id: "butterfly", text: "A fully grown butterfly." },
      { id: "chrysalis", text: "A hard chrysalis case." },
      { id: "moth", text: "A small brown moth." },
      { id: "caterpillar", text: "A tiny caterpillar." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "caterpillar",
    },
    explanation: "Butterfly eggs hatch into caterpillars, which eat leaves and grow. Later a caterpillar makes a chrysalis, and only then does an adult butterfly come out. So the first stage after the egg is a caterpillar, not a butterfly, chrysalis or moth.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Life cycles",
      skill: "Identifying the first stage after a butterfly egg hatches",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["life cycle", "butterfly", "caterpillar"],
    },
  },
  {
    id: "icas-y3-science-a-005",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A family is going away and asks a neighbour to look after their pet rabbit. Which TWO things must the neighbour give the rabbit every day to keep it alive and well? Select two.",
    options: [
      { id: "food", text: "Food to eat" },
      { id: "water", text: "Fresh water to drink" },
      { id: "toy", text: "A brand-new toy each day" },
      { id: "tv", text: "A television to watch" },
    ],
    visuals: [],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["food", "water"],
    },
    explanation: "Every living animal needs food and water to stay alive. A new toy or a television might be fun, but the rabbit can live perfectly well without them, so they are not daily needs.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Needs of living things",
      skill: "Identifying the daily needs of a living animal",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["living things", "needs", "animals"],
    },
  },
  {
    id: "icas-y3-science-a-006",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Sort each thing into 'Living' or 'Non-living'.",
    interaction: {
      type: "matching",
      sources: [
        {
          id: "dog",
          text: "A dog barking in a yard",
        },
        {
          id: "gum-tree",
          text: "A gum tree growing taller each year",
        },
        {
          id: "robot",
          text: "A wind-up robot toy that walks",
        },
        {
          id: "rock",
          text: "A grey rock on the ground",
        },
      ],
      targets: [
        {
          id: "living",
          text: "Living",
        },
        {
          id: "non-living",
          text: "Non-living",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "dog",
          targetId: "living",
        },
        {
          sourceId: "gum-tree",
          targetId: "living",
        },
        {
          sourceId: "robot",
          targetId: "non-living",
        },
        {
          sourceId: "rock",
          targetId: "non-living",
        },
      ],
    },
    explanation: "Living things grow, need food or water, and can make more of their own kind. A dog and a gum tree do these things, so they are living. A rock has never been alive. A robot toy can move, but movement alone is not enough — it cannot grow, eat or make young, so it is non-living.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Living and non-living",
      skill: "Sorting things into living and non-living",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["living things", "non-living", "sorting", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-007",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Match each food to the plant or animal it comes from.",
    interaction: {
      type: "matching",
      sources: [
        {
          id: "honey",
          text: "Honey",
        },
        {
          id: "milk",
          text: "Milk",
        },
        {
          id: "egg",
          text: "An egg",
        },
        {
          id: "bread",
          text: "Bread",
        },
      ],
      targets: [
        {
          id: "bee",
          text: "Bees",
        },
        {
          id: "cow",
          text: "A cow",
        },
        {
          id: "hen",
          text: "A hen",
        },
        {
          id: "wheat",
          text: "A wheat plant",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "honey",
          targetId: "bee",
        },
        {
          sourceId: "milk",
          targetId: "cow",
        },
        {
          sourceId: "egg",
          targetId: "hen",
        },
        {
          sourceId: "bread",
          targetId: "wheat",
        },
      ],
    },
    explanation: "Honey is made by bees, milk comes from cows, eggs are laid by hens, and bread is made from flour that is ground from wheat. Tracing each food back shows where the food we eat begins.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Food sources",
      skill: "Matching foods to the plant or animal they come from",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["food sources", "living things", "matching"],
    },
  },
  {
    id: "icas-y3-science-a-008",
    type: "ordering",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "In a garden, grass is eaten by a grasshopper, the grasshopper is eaten by a frog, and a snake eats the frog. Put this food chain in order, starting with the living thing that makes its own food.",
    interaction: {
      type: "ordering",
      items: [
        {
          id: "frog",
          text: "A frog",
        },
        {
          id: "grass",
          text: "Grass",
        },
        {
          id: "snake",
          text: "A snake",
        },
        {
          id: "grasshopper",
          text: "A grasshopper",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["grass", "grasshopper", "frog", "snake"],
    },
    explanation: "A food chain starts with a plant, because grass makes its own food using sunlight. The grasshopper eats the grass, the frog eats the grasshopper, and the snake eats the frog. Each step points to the animal doing the eating.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Food chains",
      skill: "Ordering a simple food chain",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["food chain", "energy", "ordering", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-009",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Match each part of a plant to the job it does.",
    interaction: {
      type: "matching",
      sources: [
        {
          id: "roots",
          text: "Roots",
        },
        {
          id: "stem",
          text: "Stem",
        },
        {
          id: "leaves",
          text: "Leaves",
        },
        {
          id: "flower",
          text: "Flower",
        },
      ],
      targets: [
        {
          id: "take-water",
          text: "Take in water from the soil",
        },
        {
          id: "hold-up",
          text: "Hold the plant up",
        },
        {
          id: "make-food",
          text: "Make food using sunlight",
        },
        {
          id: "make-seeds",
          text: "Make seeds for new plants",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "roots",
          targetId: "take-water",
        },
        {
          sourceId: "stem",
          targetId: "hold-up",
        },
        {
          sourceId: "leaves",
          targetId: "make-food",
        },
        {
          sourceId: "flower",
          targetId: "make-seeds",
        },
      ],
    },
    explanation: "Roots reach down and take in water from the soil, the stem holds the plant up, the leaves make food using sunlight, and the flower makes seeds so new plants can grow.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Plant parts",
      skill: "Matching plant parts to their jobs",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["plants", "plant parts", "matching"],
    },
  },
  {
    id: "icas-y3-science-a-010",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "It is midnight and the sky outside is dark. Why can we NOT see the Sun in the sky at midnight?",
    options: [
      { id: "switch-off", text: "The Sun switches off during the night." },
      { id: "turned-away", text: "Our side of the Earth faces away from the Sun." },
      { id: "clouds", text: "Thick clouds always cover the Sun at night." },
      { id: "moon", text: "The Moon moves in front of the Sun each night." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "turned-away",
    },
    explanation: "The Earth spins once each day. At midnight your side of the Earth has turned away from the Sun, so its light cannot reach you. The Sun never switches off, clouds are not always there, and the Moon does not cover the Sun each night.",
    metadata: {
      subject: "science",
      strand: "Earth and space sciences",
      topic: "Day and night",
      skill: "Explaining why the Sun is not seen at midnight",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["day and night", "Earth", "Sun", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-011",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "In a town in southern Australia it is the coldest time of the year. The days are short and there is snow on the nearby mountains. Which season is it most likely to be?",
    options: [
      { id: "summer", text: "Summer" },
      { id: "spring", text: "Spring" },
      { id: "winter", text: "Winter" },
      { id: "autumn", text: "Autumn" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "winter",
    },
    explanation: "Short, very cold days with snow on the mountains happen in winter, the coldest season. Summer is hot, spring is mild and warming up, and autumn is cooling but not the coldest, so winter fits the clues best.",
    metadata: {
      subject: "science",
      strand: "Earth and space sciences",
      topic: "Weather and seasons",
      skill: "Identifying a season from weather clues",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["weather", "seasons", "winter"],
    },
  },
  {
    id: "icas-y3-science-a-012",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A class wants to reduce the amount of rubbish they send to landfill each week. Which action would help the most?",
    options: [
      { id: "new-bottle", text: "Buying a brand-new drink bottle every single day." },
      { id: "one-bin", text: "Putting every kind of rubbish into one large bin." },
      { id: "lights", text: "Leaving all the classroom lights on through the night." },
      { id: "reuse", text: "Packing lunches in containers they can wash and reuse." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "reuse",
    },
    explanation: "Reusable containers are washed and used again, so nothing is thrown away. Buying a new bottle every day and mixing everything into one bin both make more landfill rubbish, and leaving lights on wastes power but does not reduce rubbish at all.",
    metadata: {
      subject: "science",
      strand: "Earth and space sciences",
      topic: "Caring for the environment",
      skill: "Choosing the best action to reduce rubbish sent to landfill",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["environment", "rubbish", "reuse", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-013",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The bar chart shows how much rain fell each day. How many millimetres of rain fell on Tuesday?",
    instructions: "Write just the number of millimetres, without the unit.",
    visuals: [
      {
        id: "visual-icas-y3-science-a-013-1",
        type: "bar_chart",
        altText: "Bar chart of daily rainfall: Monday 10 mm, Tuesday 25 mm, Wednesday 15 mm, Thursday 20 mm.",
        data: {
          labels: ["Monday", "Tuesday", "Wednesday", "Thursday"],
          values: [10, 25, 15, 20],
          xAxisLabel: "Day",
          yAxisLabel: "Rain (mm)",
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 25,
      tolerance: 0,
      unit: "mm",
    },
    explanation: "Find the bar labelled Tuesday and read across to the scale on the side. The Tuesday bar reaches 25, so 25 millimetres of rain fell that day.",
    metadata: {
      subject: "science",
      strand: "Earth and space sciences",
      topic: "Weather data",
      skill: "Reading a value from a rainfall bar chart",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["weather", "bar chart", "data", "rainfall"],
    },
  },
  {
    id: "icas-y3-science-a-014",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A green tree frog sits very still on a bright green leaf. A hungry bird flying above finds it very hard to spot the frog. Which feature of the frog is helping keep it safe?",
    options: [
      { id: "green", text: "Its green colour that blends in with the leaf." },
      { id: "tongue", text: "Its long sticky tongue for catching flies." },
      { id: "feet", text: "Its webbed feet that help it swim across ponds." },
      { id: "croak", text: "Its loud croaking call heard at night." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "green",
    },
    explanation: "The frog's green colour matches the green leaf, so the bird's eyes cannot pick it out. This is called camouflage. Its tongue, feet and croak are all real frog features, but none of them help it hide from a bird looking down.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Camouflage",
      skill: "Identifying camouflage as a feature that keeps an animal safe",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["camouflage", "survival", "animals", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-015",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Match each animal to the place where it is best suited to live.",
    interaction: {
      type: "matching",
      sources: [
        {
          id: "fish",
          text: "A fish",
        },
        {
          id: "camel",
          text: "A camel",
        },
        {
          id: "polar-bear",
          text: "A polar bear",
        },
        {
          id: "worm",
          text: "An earthworm",
        },
      ],
      targets: [
        {
          id: "pond",
          text: "A pond of water",
        },
        {
          id: "desert",
          text: "A hot, sandy desert",
        },
        {
          id: "ice",
          text: "Cold snow and ice",
        },
        {
          id: "soil",
          text: "Damp soil underground",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "fish",
          targetId: "pond",
        },
        {
          sourceId: "camel",
          targetId: "desert",
        },
        {
          sourceId: "polar-bear",
          targetId: "ice",
        },
        {
          sourceId: "worm",
          targetId: "soil",
        },
      ],
    },
    explanation: "Each animal is suited to one home: a fish breathes underwater in a pond, a camel copes with heat and little water in a desert, a polar bear stays warm in snow and ice, and an earthworm lives in damp soil underground.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Habitats",
      skill: "Matching animals to their habitats",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 55,
      tags: ["habitats", "animals", "matching"],
    },
  },
  {
    id: "icas-y3-science-a-016",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Four bean seeds were grown in different places. The table shows how tall each plant was after two weeks. The tallest plant was kept in a sunny window and watered. Which TWO things helped this plant grow the best? Select two.",
    options: [
      { id: "water", text: "Being watered" },
      { id: "darkness", text: "Being kept in the dark" },
      { id: "no-water", text: "Being left with no water" },
      { id: "sunlight", text: "Sunlight from the window" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-science-a-016-1",
        type: "table",
        altText: "Table of four bean plants: sunny and watered 12 cm, dark and watered 5 cm, sunny and not watered 2 cm, dark and not watered 0 cm.",
        data: {
          headers: ["Bean plant", "Where it was kept", "Height after 2 weeks (cm)"],
          rows: [
            ["Plant 1", "Sunny window, watered", "12"],
            ["Plant 2", "Dark cupboard, watered", "5"],
            ["Plant 3", "Sunny window, not watered", "2"],
            ["Plant 4", "Dark cupboard, not watered", "0"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["sunlight", "water"],
    },
    explanation: "Compare the rows. Plant 1 had both sunlight and water and grew tallest at 12 cm. Taking away light (Plant 2) or water (Plant 3) made the plant much shorter, and with neither (Plant 4) it did not grow at all. So sunlight and water together helped the plant grow best.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Needs of living things",
      skill: "Interpreting a data table to find what a plant needs to grow",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["plants", "needs", "table", "data", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-017",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "As autumn turns colder, some animals eat a lot and store extra fat in their bodies before winter arrives. Why is storing this fat helpful for them?",
    options: [
      { id: "fur", text: "The cold weather makes their fur change colour." },
      { id: "run-more", text: "Winter days are long, so they need to run more." },
      { id: "energy", text: "Food is hard to find in winter, so the fat gives them energy." },
      { id: "taller", text: "They want to grow much taller before the spring." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "energy",
    },
    explanation: "In winter, plants and small creatures are scarce, so food is hard to find. The fat stored in autumn acts like a food store the animal's body can use for energy through the cold months. The other choices do not explain why the stored fat helps.",
    metadata: {
      subject: "science",
      strand: "Biological sciences",
      topic: "Seasonal animal behaviour",
      skill: "Reasoning about why animals store fat before winter",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["animals", "seasons", "survival", "reasoning"],
    },
  },
  {
    id: "icas-y3-science-a-018",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Some children notice that a park full of litter has far fewer birds than a clean park nearby. They say that dropping litter in a park can harm the animals that live there. Is this a sensible conclusion from what they saw?",
    visuals: [],
    answerKey: {
      kind: "boolean",
      value: true,
    },
    explanation: "The children compared two parks and saw fewer birds where there was more litter. That is a sensible reason to think litter can harm the animals, because rubbish can poison or trap them or drive them away. It is a fair conclusion drawn from what they observed.",
    metadata: {
      subject: "science",
      strand: "Earth and space sciences",
      topic: "Caring for the environment",
      skill: "Drawing a conclusion about litter harming animals from an observation",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 55,
      tags: ["environment", "litter", "conclusion", "reasoning"],
    },
  },
]);
