import { defineQuestions } from "../helpers/create-question";

/**
 * Grade 3 ICAS-style Digital Technologies — 34 hand-authored questions.
 * ICAS sets this paper only to Year 7, and NAPLAN not at all, so the
 * programme is ICAS-only and its year span stops short of the others.
 */
export const grade3IcasDigitalTechnologies = defineQuestions([
  {
    id: "icas-y3-digitech-a-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Follow these steps in order. Start with the number 4. Add 3. Then double the answer. What number do you finish with?",
    options: [
      { id: "a", text: "11" },
      { id: "c", text: "10" },
      { id: "b", text: "14" },
      { id: "d", text: "8" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "b",
    },
    explanation: "Do the steps in order. 4 add 3 is 7. To double 7 means 7 and 7 together, which is 14. If you double first you get the wrong answer.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Following a sequence of steps",
      skill: "Follow a step-by-step sequence to find the result",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["algorithms", "sequence", "following steps"],
    },
  },
  {
    id: "icas-y3-digitech-a-002",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Mia wrote these steps to make a jam sandwich. 1) Take two slices of bread. 2) Spread jam on one slice. 3) Put the two slices together. 4) Pour the jam into a cup. Which step is wrong?",
    options: [
      { id: "b", text: "Step 2" },
      { id: "c", text: "Step 3" },
      { id: "d", text: "Step 1" },
      { id: "a", text: "Step 4" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "a",
    },
    explanation: "Read each step and picture doing it. Pouring jam into a cup does not help make a sandwich, so step 4 is the step that does not belong.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Errors in instructions",
      skill: "Find the wrong step in a set of instructions",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["algorithms", "debugging", "wrong step"],
    },
  },
  {
    id: "icas-y3-digitech-a-003",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "These steps tell how to plant a seed, but one step is missing. 1) Dig a small hole in the soil. 2) Put the seed in the hole. 3) ??? 4) Water the soil. Which step is missing at number 3?",
    options: [
      { id: "d", text: "Cover the seed with soil" },
      { id: "a", text: "Dig another hole nearby" },
      { id: "b", text: "Take the seed back out" },
      { id: "c", text: "Water it again now" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "d",
    },
    explanation: "After putting the seed in the hole, you cover it with soil, then water it. Digging another hole, taking the seed out, or watering before covering will not help the seed grow where you planted it.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Missing steps",
      skill: "Find the missing step in an algorithm",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["algorithms", "missing step", "reasoning"],
    },
  },
  {
    id: "icas-y3-digitech-a-004",
    type: "ordering",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Put these steps for washing your hands in the correct order, from first to last.",
    interaction: {
      type: "ordering",
      items: [
        {
          id: "soap",
          text: "Rub soap on your hands",
        },
        {
          id: "tap",
          text: "Turn on the tap",
        },
        {
          id: "dry",
          text: "Dry your hands with a towel",
        },
        {
          id: "wet",
          text: "Wet your hands",
        },
        {
          id: "rinse",
          text: "Rinse the soap off",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["tap", "wet", "soap", "rinse", "dry"],
    },
    explanation: "Think about what must happen first. You turn on the tap, then wet your hands, then rub soap on, then rinse the soap off, and dry your hands last.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Ordering task steps",
      skill: "Put the steps of an everyday task in order",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["algorithms", "ordering", "sequence"],
    },
  },
  {
    id: "icas-y3-digitech-a-005",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A robot starts on square 1. It follows this rule: 'Move forward 2 squares. Do this 3 times.' Which square does the robot land on?",
    options: [
      { id: "a", text: "Square 5" },
      { id: "c", text: "Square 7" },
      { id: "b", text: "Square 6" },
      { id: "d", text: "Square 8" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "c",
    },
    explanation: "Doing 'move 2' three times adds 6 in total. Start on 1, then 3, then 5, then 7. So the robot lands on square 7.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Loops and repeats",
      skill: "Work out the result of a repeated instruction (loop)",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["algorithms", "loops", "repeats"],
    },
  },
  {
    id: "icas-y3-digitech-a-006",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The pictograph shows how many books each child read. Each star stands for 2 books. How many books did Sam read?",
    visuals: [
      {
        id: "visual-icas-y3-digitech-a-006-1",
        type: "table",
        altText: "A pictograph. Ava has three stars, Sam has four stars, and Leo has two stars. Each star stands for 2 books.",
        data: {
          headers: ["Child", "Books read"],
          rows: [
            ["Ava", "★ ★ ★"],
            ["Sam", "★ ★ ★ ★"],
            ["Leo", "★ ★"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 8,
      tolerance: 0,
    },
    explanation: "Sam's row has four stars. Each star means 2 books, so count in twos: 2, 4, 6, 8. Sam read 8 books.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Reading a pictograph",
      skill: "Read a value from a pictograph",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["data", "pictograph", "reading data"],
    },
  },
  {
    id: "icas-y3-digitech-a-007",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The table shows how many children chose each lunch. How many children chose the salad?",
    options: [
      { id: "b", text: "9" },
      { id: "c", text: "7" },
      { id: "a", text: "5" },
      { id: "d", text: "6" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-digitech-a-007-1",
        type: "table",
        altText: "A table of lunch choices: Pie 9 children, Salad 5 children, Wrap 7 children.",
        data: {
          headers: ["Lunch", "Children"],
          rows: [
            ["Pie", "9"],
            ["Salad", "5"],
            ["Wrap", "7"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "single_option",
      optionId: "a",
    },
    explanation: "Find the Salad row, then read across to the Children column. It shows 5, so 5 children chose the salad.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Reading a table",
      skill: "Read information from a table",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["data", "table", "reading data"],
    },
  },
  {
    id: "icas-y3-digitech-a-008",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A class sorts these animals into the group 'can fly'. Choose all the animals that belong in this group.",
    options: [
      { id: "goldfish", text: "Goldfish" },
      { id: "sparrow", text: "Sparrow" },
      { id: "eagle", text: "Eagle" },
      { id: "dog", text: "Dog" },
    ],
    visuals: [],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["sparrow", "eagle"],
    },
    explanation: "The group is 'can fly'. Sparrows and eagles are birds that fly, so they belong. A dog and a goldfish cannot fly, so they do not belong in this group.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Sorting by an attribute",
      skill: "Sort items into a group by an attribute",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["data", "sorting", "grouping"],
    },
  },
  {
    id: "icas-y3-digitech-a-009",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The tally chart shows goals scored each week. How many goals were scored in total across the three weeks?",
    visuals: [
      {
        id: "visual-icas-y3-digitech-a-009-1",
        type: "table",
        altText: "A tally chart. Week 1 has three marks, Week 2 has two marks, Week 3 has four marks.",
        data: {
          headers: ["Week", "Tally"],
          rows: [
            ["Week 1", "| | |"],
            ["Week 2", "| |"],
            ["Week 3", "| | | |"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "number",
      value: 9,
      tolerance: 0,
    },
    explanation: "Count the marks in each row: 3, then 2, then 4. Add them together: 3 + 2 + 4 = 9 goals in total.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Tally marks",
      skill: "Count and total using tally marks",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["data", "tally", "counting"],
    },
  },
  {
    id: "icas-y3-digitech-a-010",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A weather chart uses symbols. Match each symbol to what it means.",
    interaction: {
      type: "matching",
      sources: [
        {
          id: "sun",
          text: "☀ (sun)",
        },
        {
          id: "cloud",
          text: "☁ (cloud)",
        },
        {
          id: "umbrella",
          text: "☂ (umbrella)",
        },
        {
          id: "snow",
          text: "❄ (snowflake)",
        },
      ],
      targets: [
        {
          id: "sunny",
          text: "Sunny",
        },
        {
          id: "cloudy",
          text: "Cloudy",
        },
        {
          id: "rainy",
          text: "Rainy",
        },
        {
          id: "snowy",
          text: "Snowy",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "sun",
          targetId: "sunny",
        },
        {
          sourceId: "cloud",
          targetId: "cloudy",
        },
        {
          sourceId: "umbrella",
          targetId: "rainy",
        },
        {
          sourceId: "snow",
          targetId: "snowy",
        },
      ],
    },
    explanation: "Match each symbol to what it shows: the sun means sunny, the cloud means cloudy, the umbrella is used for rain so it means rainy, and the snowflake means snowy.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Symbols and keys",
      skill: "Match symbols to their meanings using a key",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["data", "symbols", "key"],
    },
  },
  {
    id: "icas-y3-digitech-a-011",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A drummer follows this instruction: 'Hit the drum, then wait. Repeat until you have hit the drum 4 times.' The drummer has already hit the drum 1 time. How many more times must the drummer hit the drum?",
    options: [
      { id: "d", text: "3" },
      { id: "a", text: "2" },
      { id: "b", text: "4" },
      { id: "c", text: "5" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "d",
    },
    explanation: "The drummer needs 4 hits in total and has already done 1. So the number left is 4 − 1 = 3 more hits.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Counting repeats in a loop",
      skill: "Count how many times a step still repeats in a loop",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["algorithms", "loops", "counting"],
    },
  },
  {
    id: "icas-y3-digitech-a-012",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A game has this rule: 'If the number is even, clap. If the number is odd, jump.' The number called out is 7. What should you do?",
    options: [
      { id: "a", text: "Clap" },
      { id: "c", text: "Jump" },
      { id: "b", text: "Clap and jump" },
      { id: "d", text: "Do nothing" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "c",
    },
    explanation: "7 is an odd number. The rule says to jump for odd numbers, so you jump. You would only clap if the number were even.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Simple if-then rules",
      skill: "Follow a simple 'if... then' instruction",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["algorithms", "if then", "rules"],
    },
  },
  {
    id: "icas-y3-digitech-a-013",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Look at the pictograph. Each dot stands for 2 pets. Statement: More dogs than cats were counted. Is this statement true or false?",
    visuals: [
      {
        id: "visual-icas-y3-digitech-a-013-1",
        type: "table",
        altText: "A pictograph. Cats have three dots, dogs have five dots, birds have one dot. Each dot stands for 2 pets.",
        data: {
          headers: ["Pet", "Dots"],
          rows: [
            ["Cats", "● ● ●"],
            ["Dogs", "● ● ● ● ●"],
            ["Birds", "●"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "boolean",
      value: true,
    },
    explanation: "Dogs have 5 dots, which is 10 pets, and cats have 3 dots, which is 6 pets. 10 is more than 6, so it is true that more dogs than cats were counted.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Comparing data on a pictograph",
      skill: "Decide if a statement about a pictograph is true or false",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["data", "pictograph", "comparing"],
    },
  },
  {
    id: "icas-y3-digitech-a-014",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Ben wants a floor robot to draw a square. A square has four equal sides and four corners. Which set of steps will draw a square?",
    options: [
      { id: "a", text: "Go forward once, then stop." },
      { id: "c", text: "Go forward 4 times without turning." },
      { id: "b", text: "Repeat 4 times: go forward, then turn." },
      { id: "d", text: "Turn 4 times without going forward." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "b",
    },
    explanation: "Going forward makes a side and turning makes a corner. A square needs 4 sides and 4 corners, so you repeat 'go forward, then turn' four times. Going forward without turning only makes one long line.",
    metadata: {
      subject: "digital_technologies",
      strand: "Algorithms",
      topic: "Choosing correct steps",
      skill: "Choose the set of steps that completes a task",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["algorithms", "loops", "reasoning"],
    },
  },
  {
    id: "icas-y3-digitech-a-015",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The table shows how many minutes each child read. Choose all the children who read for more than 20 minutes.",
    options: [
      { id: "max", text: "Max" },
      { id: "noah", text: "Noah" },
      { id: "zoe", text: "Zoe" },
      { id: "ivy", text: "Ivy" },
    ],
    visuals: [
      {
        id: "visual-icas-y3-digitech-a-015-1",
        type: "table",
        altText: "A table of reading time: Noah 15 minutes, Zoe 30 minutes, Ivy 20 minutes, Max 25 minutes.",
        data: {
          headers: ["Child", "Minutes"],
          rows: [
            ["Noah", "15"],
            ["Zoe", "30"],
            ["Ivy", "20"],
            ["Max", "25"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["zoe", "max"],
    },
    explanation: "'More than 20' means a number bigger than 20. Zoe read 30 and Max read 25, which are both more than 20. Ivy read exactly 20, which is not more than 20, and Noah read only 15.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Selecting data that fits a rule",
      skill: "Choose all data items that fit a rule",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["data", "table", "rule"],
    },
  },
  {
    id: "icas-y3-digitech-a-018",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A class sorts things into a group called 'living things'. They put a cat, a rock and a tree into the group. Is this group sorted correctly?",
    visuals: [],
    answerKey: {
      kind: "boolean",
      value: false,
    },
    explanation: "A group called 'living things' should only hold things that are alive. A cat and a tree are living, but a rock is not alive, so the group is not sorted correctly.",
    metadata: {
      subject: "digital_technologies",
      strand: "Data",
      topic: "Checking a sorted group",
      skill: "Decide if items are grouped correctly by attribute",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["data", "sorting", "attribute"],
    },
  },
  {
    id: "icas-y3-digitech-b-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Anita wants to type her name so it appears on the computer. Which one of these lets her put words INTO the computer?",
    options: [
      { id: "keyboard", text: "A keyboard" },
      { id: "speakers", text: "A pair of speakers" },
      { id: "printer", text: "A colour printer" },
      { id: "screen", text: "A picture screen" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "keyboard",
    },
    explanation: "An input device lets you put information into a computer. You type on a keyboard, so it is an input device. Speakers, a printer and a screen all send information out to you, so they are output devices.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Input and output devices",
      skill: "Identifying an input device",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["input device", "keyboard", "hardware"],
    },
  },
  {
    id: "icas-y3-digitech-b-002",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A computer has worked out an answer. Which part SHOWS the answer so a person can read it?",
    options: [
      { id: "microphone", text: "A small microphone" },
      { id: "monitor", text: "The monitor screen" },
      { id: "mouse", text: "The computer mouse" },
      { id: "scanner", text: "A flat scanner" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "monitor",
    },
    explanation: "An output device sends information out from the computer to you. The monitor screen shows the answer so you can read it. A microphone, mouse and scanner all put information in, so they are input devices.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Input and output devices",
      skill: "Identifying an output device",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["output device", "monitor", "hardware"],
    },
  },
  {
    id: "icas-y3-digitech-b-003",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A game you can play on a tablet is a kind of software: a set of instructions that tells the tablet what to do. Is this statement true or false?",
    options: [],
    visuals: [],
    answerKey: {
      kind: "boolean",
      value: true,
    },
    explanation: "Software means the programs and instructions that tell a device what to do, like games and apps. Hardware is the parts you can touch. A game is a program, so it is software, which makes the statement true.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Hardware and software",
      skill: "Understanding what software is",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["software", "programs", "apps"],
    },
  },
  {
    id: "icas-y3-digitech-b-004",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Sort each thing into 'Hardware' (a part you can touch) or 'Software' (a program that runs).",
    options: [],
    interaction: {
      type: "matching",
      sources: [
        {
          id: "mouse",
          text: "A computer mouse",
        },
        {
          id: "drawing-app",
          text: "A drawing app",
        },
        {
          id: "printer",
          text: "A printer",
        },
        {
          id: "browser",
          text: "A web browser program",
        },
      ],
      targets: [
        {
          id: "hardware",
          text: "Hardware",
        },
        {
          id: "software",
          text: "Software",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "mouse",
          targetId: "hardware",
        },
        {
          sourceId: "drawing-app",
          targetId: "software",
        },
        {
          sourceId: "printer",
          targetId: "hardware",
        },
        {
          sourceId: "browser",
          targetId: "software",
        },
      ],
    },
    explanation: "Hardware is any part you can touch, like a mouse or a printer. Software is a program that runs, like a drawing app or a web browser. Ask yourself: can I hold it (hardware) or does it run on the screen (software)?",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Hardware and software",
      skill: "Sorting items as hardware or software",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["hardware", "software", "sorting"],
    },
  },
  {
    id: "icas-y3-digitech-b-005",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Match each device to the job it is made to do.",
    options: [],
    interaction: {
      type: "matching",
      sources: [
        {
          id: "printer",
          text: "A printer",
        },
        {
          id: "headphones",
          text: "Headphones",
        },
        {
          id: "webcam",
          text: "A webcam",
        },
        {
          id: "microphone",
          text: "A microphone",
        },
      ],
      targets: [
        {
          id: "on-paper",
          text: "Print words onto paper",
        },
        {
          id: "hear-private",
          text: "Let only you hear the sound",
        },
        {
          id: "show-face",
          text: "Show your face on a video call",
        },
        {
          id: "record-voice",
          text: "Record your voice",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "printer",
          targetId: "on-paper",
        },
        {
          sourceId: "headphones",
          targetId: "hear-private",
        },
        {
          sourceId: "webcam",
          targetId: "show-face",
        },
        {
          sourceId: "microphone",
          targetId: "record-voice",
        },
      ],
    },
    explanation: "Match each device to what it is built to do. A printer puts words on paper, headphones let only you hear sound, a webcam shows your face on a video call, and a microphone records your voice.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Devices and their uses",
      skill: "Matching a device to the job it does",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["devices", "uses", "matching"],
    },
  },
  {
    id: "icas-y3-digitech-b-006",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "The table shows the buttons in a computer menu and what each one does. Use the table to choose the right button for each task.",
    options: [],
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "f1",
          label: "To add a picture to her page, Sam clicks the button called",
          options: [
            { id: "file", text: "File" },
            { id: "edit", text: "Edit" },
            { id: "insert", text: "Insert" },
            { id: "help", text: "Help" },
          ],
        },
        {
          id: "f2",
          label: "To save her work, Sam clicks the button called",
          options: [
            { id: "file", text: "File" },
            { id: "edit", text: "Edit" },
            { id: "insert", text: "Insert" },
            { id: "help", text: "Help" },
          ],
        },
      ],
    },
    visuals: [
      {
        id: "visual-icas-y3-digitech-b-006-1",
        type: "table",
        altText: "A menu table with buttons File, Edit, Insert and Help and what each button does.",
        data: {
          headers: ["Menu button", "What it does"],
          rows: [
            ["File", "Open or save your work"],
            ["Edit", "Undo or copy"],
            ["Insert", "Add a picture"],
            ["Help", "Get answers to questions"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "dropdown",
      fields: [
        {
          id: "f1",
          correctOptionId: "insert",
        },
        {
          id: "f2",
          correctOptionId: "file",
        },
      ],
    },
    explanation: "Read the menu table row by row. The Insert button says 'Add a picture', so Sam clicks Insert to add a picture. The File button says 'Open or save your work', so she clicks File to save her work.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Menus and navigation",
      skill: "Following a menu to find the right button",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 80,
      tags: ["menu", "navigation", "table"],
    },
  },
  {
    id: "icas-y3-digitech-b-007",
    type: "ordering",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A kitchen robot follows a flowchart to make toast. Put the robot's steps in the correct order, from first to last.",
    options: [],
    interaction: {
      type: "ordering",
      items: [
        {
          id: "put-bread",
          text: "Put a slice of bread in the toaster",
        },
        {
          id: "press",
          text: "Press the start button",
        },
        {
          id: "wait",
          text: "Wait until the toast pops up",
        },
        {
          id: "take-out",
          text: "Take the toast out",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["put-bread", "press", "wait", "take-out"],
    },
    explanation: "A flowchart is followed one step at a time. First put the bread in, then press start, then wait for the toast to pop up, and last take the toast out. Each step must finish before the next one can begin.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Flowcharts and steps",
      skill: "Ordering the steps in a flowchart",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["flowchart", "steps", "sequence"],
    },
  },
  {
    id: "icas-y3-digitech-b-008",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A flowchart says: 'Is it raining? If YES, take an umbrella. If NO, take a hat.' This morning it is sunny with no rain. Following the flowchart, what should you take?",
    options: [
      { id: "both", text: "Both an umbrella and a hat" },
      { id: "nothing", text: "Nothing at all today" },
      { id: "hat", text: "A hat" },
      { id: "umbrella", text: "An umbrella" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "hat",
    },
    explanation: "Follow the flowchart by answering its question. It asks 'Is it raining?' It is sunny with no rain, so the answer is NO. The NO path says take a hat, so you take a hat, not an umbrella.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Flowcharts and steps",
      skill: "Following a yes or no decision in a flowchart",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 80,
      tags: ["flowchart", "decision", "reasoning"],
    },
  },
  {
    id: "icas-y3-digitech-b-009",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A row of lights shows a repeating pattern: ON, OFF, ON, OFF, ON, then a blank. What should the next light be?",
    options: [
      { id: "on", text: "ON" },
      { id: "flashing", text: "Flashing" },
      { id: "half", text: "Half ON" },
      { id: "off", text: "OFF" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "off",
    },
    explanation: "The pattern repeats ON, OFF over and over. The last light shown is ON, so the next one must be OFF to keep the repeat going. Saying the pattern out loud helps you hear what comes next.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Patterns and codes",
      skill: "Continuing an on and off pattern",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["pattern", "on off", "sequence"],
    },
  },
  {
    id: "icas-y3-digitech-b-010",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Ben writes each letter using a code made of just two symbols: dot and dash. Use the table to read the code, then choose the right letter for each one.",
    options: [],
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "f1",
          label: "The code 'dash dot' stands for the letter",
          options: [
            { id: "a", text: "A" },
            { id: "b", text: "B" },
            { id: "c", text: "C" },
            { id: "d", text: "D" },
          ],
        },
        {
          id: "f2",
          label: "The code 'dot dash' stands for the letter",
          options: [
            { id: "a", text: "A" },
            { id: "b", text: "B" },
            { id: "c", text: "C" },
            { id: "d", text: "D" },
          ],
        },
      ],
    },
    visuals: [
      {
        id: "visual-icas-y3-digitech-b-010-1",
        type: "table",
        altText: "A code table: A is dot dot, B is dot dash, C is dash dot, D is dash dash.",
        data: {
          headers: ["Letter", "Its code"],
          rows: [
            ["A", "dot dot"],
            ["B", "dot dash"],
            ["C", "dash dot"],
            ["D", "dash dash"],
          ],
        },
      },
    ],
    answerKey: {
      kind: "dropdown",
      fields: [
        {
          id: "f1",
          correctOptionId: "c",
        },
        {
          id: "f2",
          correctOptionId: "b",
        },
      ],
    },
    explanation: "Read the code table one row at a time. 'dash dot' is in the row for the letter C, so that code stands for C. 'dot dash' is in the row for the letter B, so that code stands for B.",
    metadata: {
      subject: "digital_technologies",
      strand: "Digital Systems",
      topic: "Patterns and codes",
      skill: "Reading a two-symbol code",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["code", "two symbols", "table"],
    },
  },
  {
    id: "icas-y3-digitech-b-011",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "While playing an online game, a stranger sends Kai a message asking where he lives. What is the safest thing for Kai to do?",
    options: [
      { id: "tell-adult", text: "Do not reply and tell a trusted adult" },
      { id: "give-address", text: "Send the stranger his home address" },
      { id: "give-school", text: "Tell the stranger his school name" },
      { id: "meet", text: "Agree to meet the stranger soon" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "tell-adult",
    },
    explanation: "A stranger online should never be told where you live. The safe choice is to not reply and tell a trusted adult. Giving your address or school name, or agreeing to meet, could put you in danger.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Staying safe online",
      skill: "Responding safely to an online stranger",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["online safety", "strangers", "trusted adult"],
    },
  },
  {
    id: "icas-y3-digitech-b-012",
    type: "true_false",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Writing a mean comment about a classmate's photo online is being kind. Is this statement true or false?",
    options: [],
    visuals: [],
    answerKey: {
      kind: "boolean",
      value: false,
    },
    explanation: "Being kind online means writing polite and friendly words. A mean comment about someone's photo hurts their feelings, so it is unkind, not kind, which makes the statement false.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Being kind online",
      skill: "Being kind and polite online",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 40,
      tags: ["kindness", "online", "behaviour"],
    },
  },
  {
    id: "icas-y3-digitech-b-013",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Priya's friend asks her to tell them her password so they can play on her account. What should Priya do?",
    options: [
      { id: "write-board", text: "Write the password on the board" },
      { id: "keep-secret", text: "Keep it secret and say no" },
      { id: "send-message", text: "Send the password in a message" },
      { id: "say-loud", text: "Say the password out loud in class" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "keep-secret",
    },
    explanation: "A password is a secret that keeps your account safe. Even a friend should not be told your password, so Priya should keep it secret and say no. Writing it, sending it, or saying it out loud lets other people use her account.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Passwords",
      skill: "Keeping a password private",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["password", "private", "account"],
    },
  },
  {
    id: "icas-y3-digitech-b-014",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which TWO of these make a password stronger and safer? Choose all that are correct.",
    options: [
      { id: "your-name", text: "It is just your first name" },
      { id: "birthday", text: "It is your birthday, like 0704" },
      { id: "long-mix", text: "It is long and mixes letters and numbers" },
      { id: "hard-guess", text: "It is hard for other people to guess" },
    ],
    visuals: [],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["long-mix", "hard-guess"],
    },
    explanation: "A strong password is long, mixes letters and numbers, and is hard for others to guess. Your first name or your birthday is far too easy for someone to work out, so those two choices make a weak password.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Passwords",
      skill: "Recognising a strong password",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["password", "strong", "security"],
    },
  },
  {
    id: "icas-y3-digitech-b-015",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which TWO of these are personal information that you should keep private online? Choose all that are correct.",
    options: [
      { id: "fav-game", text: "The name of a game you like" },
      { id: "home-address", text: "Your home address" },
      { id: "phone", text: "Your phone number" },
      { id: "fav-colour", text: "Your favourite colour" },
    ],
    visuals: [],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["home-address", "phone"],
    },
    explanation: "Personal information tells someone who or where you are, like your home address and phone number. These should be kept private online. A favourite colour or a game you like cannot be used to find you.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Personal information",
      skill: "Recognising personal information",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 65,
      tags: ["personal information", "privacy", "online"],
    },
  },
  {
    id: "icas-y3-digitech-b-016",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Leo wants to write a story and then print it out for his teacher. Which digital tool is the most sensible one to use?",
    options: [
      { id: "writing", text: "A writing app" },
      { id: "calculator", text: "A calculator app" },
      { id: "music", text: "A music player" },
      { id: "stopwatch", text: "A stopwatch app" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "writing",
    },
    explanation: "Choose the tool built for the job. Leo wants to write and print a story, so a writing app is the sensible choice. A calculator, a music player and a stopwatch are made for other jobs, not for writing.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Choosing digital tools",
      skill: "Choosing a sensible digital tool for a task",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["digital tools", "writing", "choice"],
    },
  },
  {
    id: "icas-y3-digitech-b-017",
    type: "matching",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "Match each task to the digital tool that is best for doing it.",
    options: [],
    interaction: {
      type: "matching",
      sources: [
        {
          id: "draw",
          text: "Draw a colourful picture",
        },
        {
          id: "add-numbers",
          text: "Add up a list of numbers",
        },
        {
          id: "video-call",
          text: "See and talk to Grandma far away",
        },
        {
          id: "find-facts",
          text: "Find facts about tigers",
        },
      ],
      targets: [
        {
          id: "paint-app",
          text: "A paint app",
        },
        {
          id: "calc-app",
          text: "A calculator app",
        },
        {
          id: "video-app",
          text: "A video call app",
        },
        {
          id: "search-web",
          text: "A search website",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "draw",
          targetId: "paint-app",
        },
        {
          sourceId: "add-numbers",
          targetId: "calc-app",
        },
        {
          sourceId: "video-call",
          targetId: "video-app",
        },
        {
          sourceId: "find-facts",
          targetId: "search-web",
        },
      ],
    },
    explanation: "Match each task to the tool made for it: a paint app to draw a picture, a calculator app to add numbers, a video call app to see and talk to Grandma, and a search website to find facts about tigers.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Choosing digital tools",
      skill: "Matching a task to the right digital tool",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["digital tools", "tasks", "matching"],
    },
  },
  {
    id: "icas-y3-digitech-b-018",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    origin: "original_seed",
    prompt: "A pop-up appears on the screen and says: 'You have won a prize! Type your name and address to claim it.' What is the safest thing to do?",
    options: [
      { id: "type-details", text: "Type your name and address in it" },
      { id: "close", text: "Close the pop-up and do not type anything" },
      { id: "click-quick", text: "Click on it to get the prize" },
      { id: "share", text: "Send the pop-up to your friends" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "close",
    },
    explanation: "A pop-up promising a prize for your details is a trick to collect your private information. The safe choice is to close it and not type anything. Typing your details, clicking it, or sharing it could give private information away.",
    metadata: {
      subject: "digital_technologies",
      strand: "Safe and Responsible Use",
      topic: "Staying safe online",
      skill: "Spotting a suspicious pop-up message",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 80,
      tags: ["pop-up", "scam", "online safety"],
    },
  },
]);
