import { defineQuestions } from "../helpers/create-question";

/**
 * Grade 3 NAPLAN-style Reading — 10 original questions.
 * Every passage is newly written MindMosaic content.
 */
export const grade3NaplanReading = defineQuestions([
  {
    id: "g3-nap-read-literal-001",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Where did Prue finally find her kite?",
    instructions: "Read the story, then choose one answer.",
    stimulus: {
      title: "The Lost Kite",
      body: "Prue and her grandpa took the new dragon kite to the beach. The wind was wild that morning, whipping sand along the shore. As soon as Prue let out the string, the kite leapt into the sky like it wanted to escape. Then a huge gust tore the string right out of her hands! Prue and Grandpa hurried over the dunes, checking the spiky grass as they went. There was no sign of it near the rock pools either. At last, beside the walking track, Prue spotted a flash of red. The kite was tangled in a banksia bush, flapping gently like a resting bird.",
    },
    options: [
      { id: "dunes", text: "In the spiky grass on the dunes" },
      { id: "rock-pools", text: "Near the rock pools" },
      { id: "banksia-bush", text: "In a banksia bush beside the walking track" },
      { id: "shore", text: "On the sand along the shore" },
    ],
    answerKey: { kind: "single_option", optionId: "banksia-bush" },
    explanation:
      "The story says Prue spotted the kite beside the walking track, tangled in a banksia bush. The dunes and rock pools are places she searched without finding it.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Finding information in a story",
      skill: "Locating directly stated details",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["narrative"],
    },
  },
  {
    id: "g3-nap-read-sequence-001",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What should you do straight after adding the pebbles?",
    instructions: "Read the instructions, then choose one answer.",
    stimulus: {
      title: "How to Make a Terrarium",
      body: "A terrarium is a tiny garden inside a jar. First, wash a large glass jar and let it dry. Next, pour a layer of small pebbles into the bottom. The pebbles help extra water drain away from the roots. After the pebbles, add a thick layer of potting soil. Then use a spoon to dig little holes and lower in your seedlings. Press the soil gently around each one. Finally, spray the plants with water and put the lid on loosely. Place your terrarium somewhere bright, but keep it out of the hot afternoon sun.",
    },
    options: [
      { id: "wash-jar", text: "Wash the glass jar" },
      { id: "add-soil", text: "Add a layer of potting soil" },
      { id: "plant-seedlings", text: "Lower in the seedlings" },
      { id: "spray-water", text: "Spray the plants with water" },
    ],
    answerKey: { kind: "single_option", optionId: "add-soil" },
    explanation:
      "The instructions say to add a thick layer of potting soil after the pebbles. Washing the jar happens first, and the seedlings and water come later.",
    metadata: {
      subject: "reading",
      strand: "Sequencing",
      topic: "Following a procedure",
      skill: "Identifying the order of steps",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["procedure"],
    },
  },
  {
    id: "g3-nap-read-infer-001",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Why did Sam stay very still?",
    instructions: "Read the story, then choose one answer.",
    stimulus: {
      title: "The Quiet Visitor",
      body: "Sam was picking beans in the vegie patch when he heard a soft rustle. A blue-tongue lizard was sliding slowly out from under the rhubarb leaves. Its scales shone like little river stones. Sam froze with the bucket still in his hand. He hardly even breathed. The lizard flicked out its bright blue tongue, tasted the air, and wandered right past his boots. When it finally disappeared behind the water tank, Sam let out a long, happy sigh. Wait until he told his sister about this!",
    },
    options: [
      { id: "scared", text: "He was too scared to move" },
      { id: "not-frighten", text: "He did not want to frighten the lizard away" },
      { id: "tired", text: "He was tired from picking beans" },
      { id: "hiding", text: "He was hiding from his sister" },
    ],
    answerKey: { kind: "single_option", optionId: "not-frighten" },
    explanation:
      "Sam froze and hardly breathed while watching the lizard, then sighed happily and wanted to tell his sister. This shows he stayed still so the lizard would not be frightened away, not because he was scared.",
    metadata: {
      subject: "reading",
      strand: "Inference",
      topic: "Inferring character motivation",
      skill: "Inferring reasons for actions",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["narrative", "inference"],
    },
  },
  {
    id: "g3-nap-read-vocab-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "In this sentence, what does 'exhausted' mean?",
    instructions: "Read the sentence, then choose one answer.",
    stimulus: {
      body: "After the long bushwalk, Ben was exhausted and fell asleep straight after dinner.",
    },
    options: [
      { id: "very-tired", text: "Very tired" },
      { id: "very-hungry", text: "Very hungry" },
      { id: "very-excited", text: "Very excited" },
      { id: "very-cold", text: "Very cold" },
    ],
    answerKey: { kind: "single_option", optionId: "very-tired" },
    explanation:
      "Ben fell asleep straight after dinner because the long bushwalk had worn him out, so 'exhausted' means very tired.",
    metadata: {
      subject: "reading",
      strand: "Vocabulary in context",
      topic: "Word meaning from context",
      skill: "Using context clues for word meaning",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["vocabulary"],
    },
  },
  {
    id: "g3-nap-read-table-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which activity starts at 11:00 on Saturday?",
    instructions: "Use the library timetable, then choose one answer.",
    options: [
      { id: "story-circle", text: "Story circle" },
      { id: "craft-corner", text: "Craft corner" },
      { id: "puppet-show", text: "Puppet show" },
      { id: "book-club", text: "Book club" },
    ],
    visuals: [
      {
        id: "g3-library-timetable",
        type: "table",
        title: "Weekend activities at Wattle Creek Library",
        altText:
          "Timetable showing story circle on Saturday at 10:00, craft corner on Saturday at 11:00, puppet show on Sunday at 11:00 and book club on Sunday at 13:00.",
        data: {
          headers: ["Activity", "Day", "Start time"],
          rows: [
            ["Story circle", "Saturday", "10:00"],
            ["Craft corner", "Saturday", "11:00"],
            ["Puppet show", "Sunday", "11:00"],
            ["Book club", "Sunday", "13:00"],
          ],
          rowHeaders: true,
        },
      },
    ],
    answerKey: { kind: "single_option", optionId: "craft-corner" },
    explanation:
      "The timetable shows craft corner on Saturday at 11:00. The puppet show also starts at 11:00, but it is on Sunday.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Reading a timetable",
      skill: "Finding information in a table",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["timetable", "table"],
    },
  },
  {
    id: "g3-nap-read-fact-001",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Select the two statements from the flyer that are facts.",
    instructions:
      "A fact can be checked. An opinion is what someone thinks or feels. Choose two answers.",
    stimulus: {
      title: "Come to Riverbend Zoo!",
      body: "Riverbend Zoo opens at 9 o'clock every morning. It is the best place in the whole world for a family day out. The keepers feed the penguins at midday, and watching them waddle to their fish is the most fun you can ever have.",
    },
    options: [
      { id: "opens-nine", text: "The zoo opens at 9 o'clock every morning." },
      { id: "best-place", text: "The zoo is the best place for a family day out." },
      { id: "penguins-midday", text: "The penguins are fed at midday." },
      { id: "most-fun", text: "Watching the penguins is the most fun you can ever have." },
    ],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["opens-nine", "penguins-midday"],
    },
    explanation:
      "The opening time and the penguin feeding time can be checked, so they are facts. Saying the zoo is 'the best place' or 'the most fun' is what the writer thinks, so those are opinions.",
    metadata: {
      subject: "reading",
      strand: "Fact and opinion",
      topic: "Telling facts from opinions",
      skill: "Distinguishing fact from opinion",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["persuasive", "fact-opinion"],
    },
  },
  {
    id: "g3-nap-read-literal-002",
    type: "true_false",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "True or false? According to the text, emus are fast runners.",
    instructions: "Read the text, then choose true or false.",
    stimulus: {
      title: "Emus",
      body: "The emu is Australia's tallest bird. Emus cannot fly, but their long, powerful legs make them very fast runners. An emu can sprint quicker than a car driving down a suburban street. Emus eat seeds, fruits and insects, and they swallow small stones to help grind up their food.",
    },
    answerKey: { kind: "boolean", value: true },
    explanation:
      "The text says emus' long, powerful legs make them very fast runners, so the statement is true.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Checking statements against a text",
      skill: "Verifying details in an information text",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["information-text"],
    },
  },
  {
    id: "g3-nap-read-sequence-002",
    type: "ordering",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Put the events from the story in the order they happened.",
    instructions: "Read the story, then arrange the events from first to last.",
    stimulus: {
      title: "Pancake Morning",
      body: "On Sunday morning, Ruby helped Dad make pancakes. First they stirred flour and milk together in the big striped bowl. Next, Ruby carefully cracked in two eggs and whisked everything until it was smooth. Then Dad cooked the pancakes in the hot pan, flipping each one high in the air. At last the whole family sat down and ate the warm pancakes with lemon and sugar.",
    },
    interaction: {
      type: "ordering",
      items: [
        { id: "event-stir", text: "Flour and milk are stirred in the bowl" },
        { id: "event-eggs", text: "Ruby cracks in the eggs" },
        { id: "event-cook", text: "Dad cooks the pancakes" },
        { id: "event-eat", text: "The family eats the pancakes" },
      ],
    },
    answerKey: {
      kind: "ordering",
      optionIds: ["event-stir", "event-eggs", "event-cook", "event-eat"],
    },
    explanation:
      "The story uses order words: 'first' they stirred flour and milk, 'next' Ruby cracked the eggs, 'then' Dad cooked the pancakes, and 'at last' the family ate them.",
    metadata: {
      subject: "reading",
      strand: "Sequencing",
      topic: "Ordering story events",
      skill: "Sequencing events in a narrative",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["narrative", "sequencing"],
    },
  },
  {
    id: "g3-nap-read-literal-003",
    type: "short_answer",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What is the name of Milly's dog?",
    instructions: "Read the text, then write your answer.",
    stimulus: {
      title: "Rainy Day Walk",
      body: "Milly's dog, Biscuit, loves rainy days more than anything. The moment the first drops tap on the roof, Biscuit fetches his lead and waits by the door with his tail thumping. On their walk, Biscuit splashes through every single puddle, while Milly hops around them in her gumboots.",
    },
    answerKey: {
      kind: "text",
      acceptableAnswers: ["Biscuit"],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation:
      "The text introduces 'Milly's dog, Biscuit', so the dog's name is Biscuit.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Recalling a detail",
      skill: "Recalling names and details",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["narrative"],
    },
  },
  {
    id: "g3-nap-read-vocab-002",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Choose the best meaning for the word as it is used in the sentence.",
    instructions: "Read the sentence, then pick one answer from the box.",
    stimulus: {
      body: "The wind was so strong that it nearly blew Dad's hat into the pond.",
    },
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "strong-meaning",
          label: "In this sentence, 'strong' means",
          options: [
            { id: "powerful", text: "powerful" },
            { id: "heavy", text: "heavy" },
            { id: "loud", text: "loud" },
            { id: "brave", text: "brave" },
          ],
        },
      ],
    },
    answerKey: {
      kind: "dropdown",
      fields: [{ id: "strong-meaning", correctOptionId: "powerful" }],
    },
    explanation:
      "A wind that nearly blows a hat away has great force, so 'strong' here means powerful.",
    metadata: {
      subject: "reading",
      strand: "Vocabulary in context",
      topic: "Word meaning from context",
      skill: "Choosing the best word meaning",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["vocabulary"],
    },
  },
]);
