import { defineQuestions } from "../helpers/create-question";

/**
 * Grade 3 NAPLAN-style Reading — 10 original questions.
 * Every passage is newly written MindMosaic content.
 */
export const grade3NaplanReading = defineQuestions([
  {
    id: "g3-nap-read-literal-001",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Where did Prue finally find her kite?",
    instructions: "Read the story, then choose one answer.",
    stimulus: {
      title: "The Lost Kite",
      body: "Prue and her grandpa took the new dragon kite to the beach. The wind was wild that morning, whipping sand along the shore. As soon as Prue let out the string, the kite leapt into the sky like it wanted to escape. Then a huge gust tore the string right out of her hands! Prue and Grandpa hurried over the dunes, checking the spiky grass as they went. There was no sign of it near the rock pools either. At last, beside the walking track, Prue spotted a flash of red. The kite was tangled in a banksia bush, flapping gently like a resting bird.",
    },
    options: [
      { id: "dunes", text: "In the spiky grass on the dunes" },
      { id: "banksia-bush", text: "In a banksia bush beside the walking track" },
      { id: "rock-pools", text: "Near the rock pools" },
      { id: "shore", text: "On the sand along the shore" },
    ],
    answerKey: { kind: "single_option", optionId: "banksia-bush" },
    explanation:
      "The story says Prue spotted the kite beside the walking track, tangled in a banksia bush. The dunes and rock pools are places she searched without finding it.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Finding information in a story",
      skill: "Locating directly stated details",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["narrative"],
    },
  },
  {
    id: "g3-nap-read-sequence-001",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What should you do straight after adding the pebbles?",
    instructions: "Read the instructions, then choose one answer.",
    stimulus: {
      title: "How to Make a Terrarium",
      body: "A terrarium is a tiny garden inside a jar. First, wash a large glass jar and let it dry. Next, pour a layer of small pebbles into the bottom. The pebbles help extra water drain away from the roots. After the pebbles, add a thick layer of potting soil. Then use a spoon to dig little holes and lower in your seedlings. Press the soil gently around each one. Finally, spray the plants with water and put the lid on loosely. Place your terrarium somewhere bright, but keep it out of the hot afternoon sun.",
    },
    options: [
      { id: "wash-jar", text: "Wash the glass jar" },
      { id: "plant-seedlings", text: "Lower in the seedlings" },
      { id: "add-soil", text: "Add a layer of potting soil" },
      { id: "spray-water", text: "Spray the plants with water" },
    ],
    answerKey: { kind: "single_option", optionId: "add-soil" },
    explanation:
      "The instructions say to add a thick layer of potting soil after the pebbles. Washing the jar happens first, and the seedlings and water come later.",
    metadata: {
      subject: "reading",
      strand: "Sequencing",
      topic: "Following a procedure",
      skill: "Identifying the order of steps",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["procedure"],
    },
  },
  {
    id: "g3-nap-read-infer-001",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Why did Sam stay very still?",
    instructions: "Read the story, then choose one answer.",
    stimulus: {
      title: "The Quiet Visitor",
      body: "Sam was picking beans in the vegie patch when he heard a soft rustle. A blue-tongue lizard was sliding slowly out from under the rhubarb leaves. Its scales shone like little river stones. Sam froze with the bucket still in his hand. He hardly even breathed. The lizard flicked out its bright blue tongue, tasted the air, and wandered right past his boots. When it finally disappeared behind the water tank, Sam let out a long, happy sigh. Wait until he told his sister about this!",
    },
    options: [
      { id: "scared", text: "He was too scared to move" },
      { id: "tired", text: "He was tired from picking beans" },
      { id: "hiding", text: "He was hiding from his sister" },
      { id: "not-frighten", text: "He did not want to frighten the lizard away" },
    ],
    answerKey: { kind: "single_option", optionId: "not-frighten" },
    explanation:
      "Sam froze and hardly breathed while watching the lizard, then sighed happily and wanted to tell his sister. This shows he stayed still so the lizard would not be frightened away, not because he was scared.",
    metadata: {
      subject: "reading",
      strand: "Inference",
      topic: "Inferring character motivation",
      skill: "Inferring reasons for actions",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["narrative", "inference"],
    },
  },
  {
    id: "g3-nap-read-vocab-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "In this sentence, what does 'exhausted' mean?",
    instructions: "Read the sentence, then choose one answer.",
    stimulus: {
      body: "After the long bushwalk, Ben was exhausted and fell asleep straight after dinner.",
    },
    options: [
      { id: "very-tired", text: "Very tired" },
      { id: "very-hungry", text: "Very hungry" },
      { id: "very-excited", text: "Very excited" },
      { id: "very-cold", text: "Very cold" },
    ],
    answerKey: { kind: "single_option", optionId: "very-tired" },
    explanation:
      "Ben fell asleep straight after dinner because the long bushwalk had worn him out, so 'exhausted' means very tired.",
    metadata: {
      subject: "reading",
      strand: "Vocabulary in context",
      topic: "Word meaning from context",
      skill: "Using context clues for word meaning",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["vocabulary"],
    },
  },
  {
    id: "g3-nap-read-table-001",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which activity starts at 11:00 on Saturday?",
    instructions: "Use the library timetable, then choose one answer.",
    options: [
      { id: "story-circle", text: "Story circle" },
      { id: "craft-corner", text: "Craft corner" },
      { id: "puppet-show", text: "Puppet show" },
      { id: "book-club", text: "Book club" },
    ],
    visuals: [
      {
        id: "g3-library-timetable",
        type: "table",
        title: "Weekend activities at Wattle Creek Library",
        altText:
          "Timetable showing story circle on Saturday at 10:00, craft corner on Saturday at 11:00, puppet show on Sunday at 11:00 and book club on Sunday at 13:00.",
        data: {
          headers: ["Activity", "Day", "Start time"],
          rows: [
            ["Story circle", "Saturday", "10:00"],
            ["Craft corner", "Saturday", "11:00"],
            ["Puppet show", "Sunday", "11:00"],
            ["Book club", "Sunday", "13:00"],
          ],
          rowHeaders: true,
        },
      },
    ],
    answerKey: { kind: "single_option", optionId: "craft-corner" },
    explanation:
      "The timetable shows craft corner on Saturday at 11:00. The puppet show also starts at 11:00, but it is on Sunday.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Reading a timetable",
      skill: "Finding information in a table",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["timetable", "table"],
    },
  },
  {
    id: "g3-nap-read-fact-001",
    type: "multiple_select",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Select the two statements from the flyer that are facts.",
    instructions:
      "A fact can be checked. An opinion is what someone thinks or feels. Choose two answers.",
    stimulus: {
      title: "Come to Riverbend Zoo!",
      body: "Riverbend Zoo opens at 9 o'clock every morning. It is the best place in the whole world for a family day out. The keepers feed the penguins at midday, and watching them waddle to their fish is the most fun you can ever have.",
    },
    options: [
      { id: "opens-nine", text: "The zoo opens at 9 o'clock every morning." },
      { id: "best-place", text: "The zoo is the best place for a family day out." },
      { id: "penguins-midday", text: "The penguins are fed at midday." },
      { id: "most-fun", text: "Watching the penguins is the most fun you can ever have." },
    ],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["opens-nine", "penguins-midday"],
    },
    explanation:
      "The opening time and the penguin feeding time can be checked, so they are facts. Saying the zoo is 'the best place' or 'the most fun' is what the writer thinks, so those are opinions.",
    metadata: {
      subject: "reading",
      strand: "Fact and opinion",
      topic: "Telling facts from opinions",
      skill: "Distinguishing fact from opinion",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["persuasive", "fact-opinion"],
    },
  },
  {
    id: "g3-nap-read-literal-002",
    type: "true_false",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "True or false? According to the text, emus are fast runners.",
    instructions: "Read the text, then choose true or false.",
    stimulus: {
      title: "Emus",
      body: "The emu is Australia's tallest bird. Emus cannot fly, but their long, powerful legs make them very fast runners. An emu can sprint quicker than a car driving down a suburban street. Emus eat seeds, fruits and insects, and they swallow small stones to help grind up their food.",
    },
    answerKey: { kind: "boolean", value: true },
    explanation:
      "The text says emus' long, powerful legs make them very fast runners, so the statement is true.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Checking statements against a text",
      skill: "Verifying details in an information text",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["information-text"],
    },
  },
  {
    id: "g3-nap-read-sequence-002",
    type: "ordering",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Put the events from the story in the order they happened.",
    instructions: "Read the story, then arrange the events from first to last.",
    stimulus: {
      title: "Pancake Morning",
      body: "On Sunday morning, Ruby helped Dad make pancakes. First they stirred flour and milk together in the big striped bowl. Next, Ruby carefully cracked in two eggs and whisked everything until it was smooth. Then Dad cooked the pancakes in the hot pan, flipping each one high in the air. At last the whole family sat down and ate the warm pancakes with lemon and sugar.",
    },
    interaction: {
      type: "ordering",
      items: [
        { id: "event-stir", text: "Flour and milk are stirred in the bowl" },
        { id: "event-eggs", text: "Ruby cracks in the eggs" },
        { id: "event-cook", text: "Dad cooks the pancakes" },
        { id: "event-eat", text: "The family eats the pancakes" },
      ],
    },
    answerKey: {
      kind: "ordering",
      optionIds: ["event-stir", "event-eggs", "event-cook", "event-eat"],
    },
    explanation:
      "The story uses order words: 'first' they stirred flour and milk, 'next' Ruby cracked the eggs, 'then' Dad cooked the pancakes, and 'at last' the family ate them.",
    metadata: {
      subject: "reading",
      strand: "Sequencing",
      topic: "Ordering story events",
      skill: "Sequencing events in a narrative",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["narrative", "sequencing"],
    },
  },
  {
    id: "g3-nap-read-literal-003",
    type: "short_answer",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What is the name of Milly's dog?",
    instructions: "Read the text, then write your answer.",
    stimulus: {
      title: "Rainy Day Walk",
      body: "Milly's dog, Biscuit, loves rainy days more than anything. The moment the first drops tap on the roof, Biscuit fetches his lead and waits by the door with his tail thumping. On their walk, Biscuit splashes through every single puddle, while Milly hops around them in her gumboots.",
    },
    answerKey: {
      kind: "text",
      acceptableAnswers: ["Biscuit"],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation:
      "The text introduces 'Milly's dog, Biscuit', so the dog's name is Biscuit.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Recalling a detail",
      skill: "Recalling names and details",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["narrative"],
    },
  },
  {
    id: "g3-nap-read-vocab-002",
    type: "dropdown",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Choose the best meaning for the word as it is used in the sentence.",
    instructions: "Read the sentence, then pick one answer from the box.",
    stimulus: {
      body: "The wind was so strong that it nearly blew Dad's hat into the pond.",
    },
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "strong-meaning",
          label: "In this sentence, 'strong' means",
          options: [
            { id: "powerful", text: "powerful" },
            { id: "heavy", text: "heavy" },
            { id: "loud", text: "loud" },
            { id: "brave", text: "brave" },
          ],
        },
      ],
    },
    answerKey: {
      kind: "dropdown",
      fields: [{ id: "strong-meaning", correctOptionId: "powerful" }],
    },
    explanation:
      "A wind that nearly blows a hat away has great force, so 'strong' here means powerful.",
    metadata: {
      subject: "reading",
      strand: "Vocabulary in context",
      topic: "Word meaning from context",
      skill: "Choosing the best word meaning",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["vocabulary"],
    },
  },
  {
    id: "naplan-y3-reading-b-001",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What colour was Priya's sunhat?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Runaway Hat",
      body: "On the windiest day of the year, Priya wore her new sunhat to the beach. It was yellow with a wide brim, and her aunt had sewn a green button on the front.\n\nPriya built a sandcastle near the rock pools. She was patting the last wall smooth when a gust of wind lifted her hat and rolled it down the sand like a wheel. Priya jumped up and chased it.\n\nThe hat bounced over a towel, spun past a sleeping dog, and stopped at the feet of a boy holding a bucket of shells. He picked it up and turned it over.\n\n\"Is this yours?\" he asked. \"I saw it fly past.\"\n\nPriya nodded, out of breath. \"Thank you. My aunt made it for me.\"\n\nThe boy grinned. \"I'm Theo. Want to help me find more shells? The best ones are past the rocks.\"\n\nPriya put her hat back on and held onto it tightly with one hand. Together they walked towards the rock pools.",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "green", text: "Green" },
      { id: "yellow", text: "Yellow" },
      { id: "orange", text: "Orange" },
      { id: "purple", text: "Purple" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "yellow",
    },
    explanation: "Reread the second sentence: 'It was yellow with a wide brim.' The hat is yellow. Green is a trap — that is the colour of the button on the front, not the hat. Orange and purple are never mentioned.",
    metadata: {
      subject: "reading",
      strand: "Narrative comprehension",
      topic: "Recalling a stated detail",
      skill: "Locating a directly stated detail",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["narrative", "locating information", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-002",
    type: "ordering",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Put these events from the story in the order they happened, from first to last.",
    instructions: "Read the story, then place the events in the correct order.",
    stimulus: {
      title: "The Runaway Hat",
      body: "On the windiest day of the year, Priya wore her new sunhat to the beach. It was yellow with a wide brim, and her aunt had sewn a green button on the front.\n\nPriya built a sandcastle near the rock pools. She was patting the last wall smooth when a gust of wind lifted her hat and rolled it down the sand like a wheel. Priya jumped up and chased it.\n\nThe hat bounced over a towel, spun past a sleeping dog, and stopped at the feet of a boy holding a bucket of shells. He picked it up and turned it over.\n\n\"Is this yours?\" he asked. \"I saw it fly past.\"\n\nPriya nodded, out of breath. \"Thank you. My aunt made it for me.\"\n\nThe boy grinned. \"I'm Theo. Want to help me find more shells? The best ones are past the rocks.\"\n\nPriya put her hat back on and held onto it tightly with one hand. Together they walked towards the rock pools.",
      attribution: "MindMosaic original",
    },
    interaction: {
      type: "ordering",
      items: [
        {
          id: "theo-picks-up",
          text: "Theo picks up the hat and asks if it is Priya's.",
        },
        {
          id: "built-sandcastle",
          text: "Priya builds a sandcastle near the rock pools.",
        },
        {
          id: "walk-to-rocks",
          text: "Priya and Theo walk towards the rock pools together.",
        },
        {
          id: "wind-lifts-hat",
          text: "The wind lifts the hat and rolls it down the sand.",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "ordering",
      optionIds: ["built-sandcastle", "wind-lifts-hat", "theo-picks-up", "walk-to-rocks"],
    },
    explanation: "Follow the story from the start. First Priya is building her sandcastle. Then the wind lifts the hat away. She chases it and Theo picks it up and asks if it is hers. Last of all, the two of them walk off towards the rock pools together. Look for the order the sentences appear in the text.",
    metadata: {
      subject: "reading",
      strand: "Narrative comprehension",
      topic: "Ordering story events",
      skill: "Sequencing events in a story",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["narrative", "sequencing", "ordering", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-003",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Read this part of the story: 'a gust of wind lifted her hat'. What does the word gust mean?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Runaway Hat",
      body: "On the windiest day of the year, Priya wore her new sunhat to the beach. It was yellow with a wide brim, and her aunt had sewn a green button on the front.\n\nPriya built a sandcastle near the rock pools. She was patting the last wall smooth when a gust of wind lifted her hat and rolled it down the sand like a wheel. Priya jumped up and chased it.\n\nThe hat bounced over a towel, spun past a sleeping dog, and stopped at the feet of a boy holding a bucket of shells. He picked it up and turned it over.\n\n\"Is this yours?\" he asked. \"I saw it fly past.\"\n\nPriya nodded, out of breath. \"Thank you. My aunt made it for me.\"\n\nThe boy grinned. \"I'm Theo. Want to help me find more shells? The best ones are past the rocks.\"\n\nPriya put her hat back on and held onto it tightly with one hand. Together they walked towards the rock pools.",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "gentle", text: "A light, gentle breeze" },
      { id: "thunder", text: "A loud clap of thunder" },
      { id: "strong-rush", text: "A sudden, strong rush of wind" },
      { id: "cloud", text: "A soft grey rain cloud" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "strong-rush",
    },
    explanation: "Use the clues around the word. The wind lifted the hat right off Priya's head and rolled it 'down the sand like a wheel'. Only a strong, sudden rush of wind could do that, so 'gust' means a sudden strong wind. A gentle breeze would not carry a hat away, and thunder and clouds are not moving air at all.",
    metadata: {
      subject: "reading",
      strand: "Vocabulary",
      topic: "Meaning from context",
      skill: "Working out a word's meaning from context",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["narrative", "vocabulary", "word meaning", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-004",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What is a baby echidna called?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Amazing Echidna",
      body: "Echidnas are one of only two kinds of animal in the world that lay eggs but also feed their babies milk. They live all over Australia, in forests, deserts and grassy hills.\n\nAn echidna is covered in sharp spines. When it feels afraid, it does not run away. Instead, it curls into a tight ball, or digs straight down into the soil until only its spines can be seen. This keeps it safe from animals that might try to eat it.\n\nEchidnas have no teeth. They use a long, sticky tongue to catch the ants and termites they eat. A hungry echidna can flick its tongue in and out about one hundred times in a single minute.\n\nA baby echidna is called a puggle. It stays safe inside a pouch on its mother's body until its spines begin to grow. After that it lives in a burrow, where its mother comes to feed it.",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "joey", text: "A joey" },
      { id: "chick", text: "A chick" },
      { id: "duckling", text: "A duckling" },
      { id: "puggle", text: "A puggle" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "puggle",
    },
    explanation: "The last paragraph says it straight out: 'A baby echidna is called a puggle.' Find that sentence and copy the word. A joey is a baby kangaroo, a chick is a baby chicken and a duckling is a baby duck, so those are traps from other animals.",
    metadata: {
      subject: "reading",
      strand: "Information text comprehension",
      topic: "Recalling a stated fact",
      skill: "Finding a fact in an information text",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["information text", "locating information", "animals", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-005",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What is this text mostly about?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Amazing Echidna",
      body: "Echidnas are one of only two kinds of animal in the world that lay eggs but also feed their babies milk. They live all over Australia, in forests, deserts and grassy hills.\n\nAn echidna is covered in sharp spines. When it feels afraid, it does not run away. Instead, it curls into a tight ball, or digs straight down into the soil until only its spines can be seen. This keeps it safe from animals that might try to eat it.\n\nEchidnas have no teeth. They use a long, sticky tongue to catch the ants and termites they eat. A hungry echidna can flick its tongue in and out about one hundred times in a single minute.\n\nA baby echidna is called a puggle. It stays safe inside a pouch on its mother's body until its spines begin to grow. After that it lives in a burrow, where its mother comes to feed it.",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "whole", text: "What echidnas are like and how they live" },
      { id: "digging", text: "How an echidna digs down deep into the soil" },
      { id: "desert", text: "Why echidnas live only in the hot desert" },
      { id: "eaten", text: "The animals that try to eat an echidna" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "whole",
    },
    explanation: "The main idea is what the whole text is about, not just one sentence. This text tells us how echidnas have babies, how they stay safe, what they eat and where their babies grow — that is 'what echidnas are like and how they live'. Digging, the desert and being eaten are each only small parts of the text, so they are too narrow to be the main idea.",
    metadata: {
      subject: "reading",
      strand: "Information text comprehension",
      topic: "Identifying the main idea",
      skill: "Identifying the main idea of a text",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["information text", "main idea", "animals", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-006",
    type: "matching",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Using the text, match each part of the echidna to what it is used for.",
    instructions: "Read the text, then match each part to its use.",
    stimulus: {
      title: "The Amazing Echidna",
      body: "Echidnas are one of only two kinds of animal in the world that lay eggs but also feed their babies milk. They live all over Australia, in forests, deserts and grassy hills.\n\nAn echidna is covered in sharp spines. When it feels afraid, it does not run away. Instead, it curls into a tight ball, or digs straight down into the soil until only its spines can be seen. This keeps it safe from animals that might try to eat it.\n\nEchidnas have no teeth. They use a long, sticky tongue to catch the ants and termites they eat. A hungry echidna can flick its tongue in and out about one hundred times in a single minute.\n\nA baby echidna is called a puggle. It stays safe inside a pouch on its mother's body until its spines begin to grow. After that it lives in a burrow, where its mother comes to feed it.",
      attribution: "MindMosaic original",
    },
    interaction: {
      type: "matching",
      sources: [
        {
          id: "spines",
          text: "Its sharp spines",
        },
        {
          id: "tongue",
          text: "Its long, sticky tongue",
        },
        {
          id: "pouch",
          text: "The pouch on the mother's body",
        },
      ],
      targets: [
        {
          id: "keep-safe",
          text: "Keeping the echidna safe from animals",
        },
        {
          id: "catch-food",
          text: "Catching ants and termites to eat",
        },
        {
          id: "carry-baby",
          text: "Keeping the baby echidna safe",
        },
        {
          id: "find-water",
          text: "Digging tunnels to find water",
        },
      ],
    },
    visuals: [],
    answerKey: {
      kind: "matching",
      pairs: [
        {
          sourceId: "spines",
          targetId: "keep-safe",
        },
        {
          sourceId: "tongue",
          targetId: "catch-food",
        },
        {
          sourceId: "pouch",
          targetId: "carry-baby",
        },
      ],
    },
    explanation: "Match each part to the job the text gives it. The spines keep the echidna safe from animals that might eat it. The sticky tongue is used to catch ants and termites. The mother's pouch keeps the baby safe until its spines grow. 'Digging tunnels to find water' is not in the text at all, so it is left over.",
    metadata: {
      subject: "reading",
      strand: "Information text comprehension",
      topic: "Linking features to their use",
      skill: "Matching parts of an animal to their use",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 100,
      tags: ["information text", "matching", "animals", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-007",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "The text says an echidna can flick its tongue about one hundred times in a minute. What does this tell you about how an echidna eats?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Amazing Echidna",
      body: "Echidnas are one of only two kinds of animal in the world that lay eggs but also feed their babies milk. They live all over Australia, in forests, deserts and grassy hills.\n\nAn echidna is covered in sharp spines. When it feels afraid, it does not run away. Instead, it curls into a tight ball, or digs straight down into the soil until only its spines can be seen. This keeps it safe from animals that might try to eat it.\n\nEchidnas have no teeth. They use a long, sticky tongue to catch the ants and termites they eat. A hungry echidna can flick its tongue in and out about one hundred times in a single minute.\n\nA baby echidna is called a puggle. It stays safe inside a pouch on its mother's body until its spines begin to grow. After that it lives in a burrow, where its mother comes to feed it.",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "chews", text: "It chews its food slowly with its sharp teeth." },
      { id: "quick", text: "It catches many tiny insects very quickly with its tongue." },
      { id: "one-meal", text: "It only eats one large meal on each day." },
      { id: "stones", text: "It swallows small stones and grit to help grind up its food." },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "quick",
    },
    explanation: "Put two clues together. The echidna eats ants and termites, which are tiny, and its tongue moves about one hundred times a minute — that is very fast. So it must catch lots of little insects quickly. The 'sharp teeth' answer cannot be right because the text says echidnas have no teeth. The other two ideas are never mentioned.",
    metadata: {
      subject: "reading",
      strand: "Information text comprehension",
      topic: "Drawing a conclusion",
      skill: "Drawing a conclusion from a stated fact",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["information text", "inference", "animals", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-008",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "How deep should you push the sunflower seed into the soil?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "How to Plant a Sunflower Seed",
      body: "You will need: a small pot, some potting soil, one sunflower seed, and water.\n\n1. Fill the pot almost to the top with potting soil.\n2. Push one seed into the soil with your finger, about as deep as your first knuckle.\n3. Cover the seed gently with a little more soil.\n4. Water the soil until it is damp, but not soaking wet.\n5. Put the pot on a sunny windowsill.\n\nCheck the pot each day. When the soil feels dry, add a little water. In about one week, a small green shoot will push up through the soil. Keep the pot in the sunlight, and soon your sunflower will grow taller than you!",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "bottom", text: "All the way to the bottom of the pot" },
      { id: "ontop", text: "Just resting on top of the soil" },
      { id: "knuckle", text: "About as deep as your first knuckle" },
      { id: "whole-hand", text: "As deep as your whole hand" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "knuckle",
    },
    explanation: "Look at step 2: 'Push one seed into the soil with your finger, about as deep as your first knuckle.' That is the exact depth. Pushing to the bottom or using your whole hand would be far too deep, and leaving the seed on top means it is not planted at all.",
    metadata: {
      subject: "reading",
      strand: "Procedural text comprehension",
      topic: "Recalling a step",
      skill: "Following a specific step in instructions",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 50,
      tags: ["instructions", "locating information", "gardening", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-009",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Why did the writer write this text?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "How to Plant a Sunflower Seed",
      body: "You will need: a small pot, some potting soil, one sunflower seed, and water.\n\n1. Fill the pot almost to the top with potting soil.\n2. Push one seed into the soil with your finger, about as deep as your first knuckle.\n3. Cover the seed gently with a little more soil.\n4. Water the soil until it is damp, but not soaking wet.\n5. Put the pot on a sunny windowsill.\n\nCheck the pot each day. When the soil feels dry, add a little water. In about one week, a small green shoot will push up through the soil. Keep the pot in the sunlight, and soon your sunflower will grow taller than you!",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "story", text: "To tell an exciting garden story" },
      { id: "describe", text: "To describe what sunflowers look like" },
      { id: "list", text: "To list some flower names" },
      { id: "teach", text: "To teach you how to plant a sunflower seed" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "teach",
    },
    explanation: "Think about the shape of the text. It starts with a 'You will need' list and then gives numbered steps to follow in order. Texts built like this are written to teach you how to do something — here, how to plant a sunflower seed. It does not tell a story, describe how sunflowers look, or list flower names.",
    metadata: {
      subject: "reading",
      strand: "Procedural text comprehension",
      topic: "Author's purpose",
      skill: "Identifying the purpose of a text",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["instructions", "author purpose", "gardening", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-010",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Why does the writer tell you to put the pot on a sunny windowsill?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "How to Plant a Sunflower Seed",
      body: "You will need: a small pot, some potting soil, one sunflower seed, and water.\n\n1. Fill the pot almost to the top with potting soil.\n2. Push one seed into the soil with your finger, about as deep as your first knuckle.\n3. Cover the seed gently with a little more soil.\n4. Water the soil until it is damp, but not soaking wet.\n5. Put the pot on a sunny windowsill.\n\nCheck the pot each day. When the soil feels dry, add a little water. In about one week, a small green shoot will push up through the soil. Keep the pot in the sunlight, and soon your sunflower will grow taller than you!",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "sun", text: "Because a sunflower needs sunlight to grow well" },
      { id: "fall", text: "So the pot does not fall off the table" },
      { id: "remember", text: "So you will always remember to water the pot each day" },
      { id: "cool", text: "So the soil stays cool and damp all week" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "sun",
    },
    explanation: "The last lines say to 'keep the pot in the sunlight' and then the sunflower 'will grow taller than you'. Linking sunlight to growing tells you the plant needs sun to grow, so that is why it goes on a sunny windowsill. A sunny spot would make soil warmer, not cooler, and the text never links the windowsill to falling or to remembering.",
    metadata: {
      subject: "reading",
      strand: "Procedural text comprehension",
      topic: "Reason for an instruction",
      skill: "Inferring the reason behind an instruction",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["instructions", "inference", "gardening", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-011",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What does the child pull on before going outside?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Biggest Puddle",
      body: "When the grey clouds burst and the raindrops fall,\nI wait by the window, my boots in the hall.\nThe garden turns shiny, the path becomes wet,\nand the biggest brown puddle I ever have met\n\nsits fat by the gate where the driveway dips low.\nI pull on my raincoat and out I will go!\nI stamp and I splash till my socks are all soaked,\nthen Mum at the door calls my name, soft and slow.\n\nIt's time to come in for a warm cup and dry,\nbut tomorrow it might rain again — my, oh my!",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "boots", text: "Some boots" },
      { id: "raincoat", text: "A raincoat" },
      { id: "hat", text: "A warm hat" },
      { id: "socks", text: "Dry socks" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "raincoat",
    },
    explanation: "Find the line with the words 'pull on': 'I pull on my raincoat and out I will go!' So the child pulls on a raincoat. Boots are a trap — they are waiting 'in the hall', but the poem never says the child puts them on. The socks get soaked later, and no hat is mentioned.",
    metadata: {
      subject: "reading",
      strand: "Poetry comprehension",
      topic: "Recalling a detail",
      skill: "Finding a detail in a poem",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["poem", "locating information", "weather", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-012",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "How does the child feel about the rainy day?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Biggest Puddle",
      body: "When the grey clouds burst and the raindrops fall,\nI wait by the window, my boots in the hall.\nThe garden turns shiny, the path becomes wet,\nand the biggest brown puddle I ever have met\n\nsits fat by the gate where the driveway dips low.\nI pull on my raincoat and out I will go!\nI stamp and I splash till my socks are all soaked,\nthen Mum at the door calls my name, soft and slow.\n\nIt's time to come in for a warm cup and dry,\nbut tomorrow it might rain again — my, oh my!",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "bored", text: "Bored and grumpy" },
      { id: "scared", text: "Scared and worried" },
      { id: "happy", text: "Excited and happy" },
      { id: "tired", text: "Tired and sleepy" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "happy",
    },
    explanation: "There is no feeling word, so watch what the child does. They wait eagerly by the window, rush out ('out I will go!'), stamp and splash in the puddle, and even hope it rains again tomorrow. All of this shows the child is excited and happy. A bored, scared or sleepy child would not run out to jump in a puddle.",
    metadata: {
      subject: "reading",
      strand: "Poetry comprehension",
      topic: "Inferring feelings",
      skill: "Working out how a person feels",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["poem", "inference", "feelings", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-013",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Why does the child stop splashing in the puddle?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "The Biggest Puddle",
      body: "When the grey clouds burst and the raindrops fall,\nI wait by the window, my boots in the hall.\nThe garden turns shiny, the path becomes wet,\nand the biggest brown puddle I ever have met\n\nsits fat by the gate where the driveway dips low.\nI pull on my raincoat and out I will go!\nI stamp and I splash till my socks are all soaked,\nthen Mum at the door calls my name, soft and slow.\n\nIt's time to come in for a warm cup and dry,\nbut tomorrow it might rain again — my, oh my!",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "rain-stops", text: "Because the rain has stopped" },
      { id: "dried", text: "Because the puddle dried up" },
      { id: "boot", text: "Because a boot got lost" },
      { id: "mum", text: "Because Mum calls the child to come inside" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "mum",
    },
    explanation: "Read the end of the poem: 'then Mum at the door calls my name' and 'It's time to come in.' The child stops because Mum calls them inside. The rain has not stopped — the child even says it 'might rain again' tomorrow — the puddle has not dried, and no boot is lost.",
    metadata: {
      subject: "reading",
      strand: "Poetry comprehension",
      topic: "Cause of an event",
      skill: "Working out why an event happens",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 85,
      tags: ["poem", "inference", "cause and effect", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-014",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Who is this note written to?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "A Note from Grandpa",
      body: "Dear Ollie,\n\nI have gone next door to help Mrs Patel move her heavy bookshelf. I should be back home by half past four.\n\nYour afternoon snack is in the blue container on the bottom shelf of the fridge. Please do not share any of it with Biscuit. The vet said Biscuit must never eat grapes, and there are grapes inside.\n\nIf you finish your reading before I get home, you may feed the chickens. The scoop is hanging by the back door, and one scoopful each is plenty.\n\nSee you soon,\nGrandpa",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "ollie", text: "Ollie" },
      { id: "patel", text: "Mrs Patel" },
      { id: "vet", text: "The vet" },
      { id: "biscuit", text: "Biscuit" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "ollie",
    },
    explanation: "A note or letter usually starts with 'Dear ___' to show who it is for. This one begins 'Dear Ollie', so the note is written to Ollie. Mrs Patel, the vet and Biscuit are all mentioned inside the note, but the note is not addressed to any of them.",
    metadata: {
      subject: "reading",
      strand: "Everyday text comprehension",
      topic: "Identifying the audience",
      skill: "Identifying who a text is written for",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 45,
      tags: ["note", "audience", "locating information", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-015",
    type: "reading_comprehension",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Why does Grandpa say not to share the snack with Biscuit?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "A Note from Grandpa",
      body: "Dear Ollie,\n\nI have gone next door to help Mrs Patel move her heavy bookshelf. I should be back home by half past four.\n\nYour afternoon snack is in the blue container on the bottom shelf of the fridge. Please do not share any of it with Biscuit. The vet said Biscuit must never eat grapes, and there are grapes inside.\n\nIf you finish your reading before I get home, you may feed the chickens. The scoop is hanging by the back door, and one scoopful each is plenty.\n\nSee you soon,\nGrandpa",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "dinner", text: "Because Biscuit already ate his dinner" },
      { id: "grapes", text: "Because the snack has grapes, which Biscuit must not eat" },
      { id: "one", text: "Because there is only one snack" },
      { id: "outside", text: "Because Biscuit is shut outside" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "grapes",
    },
    explanation: "Grandpa gives the reason right after the rule: 'The vet said Biscuit must never eat grapes, and there are grapes inside.' So the snack must not be shared because it has grapes in it. The note never says Biscuit has eaten, that there is only one snack, or that Biscuit is outside.",
    metadata: {
      subject: "reading",
      strand: "Everyday text comprehension",
      topic: "Reason for a rule",
      skill: "Finding the reason given for a rule",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 70,
      tags: ["note", "inference", "locating information", "naplan style"],
    },
  },
  {
    id: "naplan-y3-reading-b-016",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What must Ollie do before he is allowed to feed the chickens?",
    instructions: "Read the text, then choose the best answer.",
    stimulus: {
      title: "A Note from Grandpa",
      body: "Dear Ollie,\n\nI have gone next door to help Mrs Patel move her heavy bookshelf. I should be back home by half past four.\n\nYour afternoon snack is in the blue container on the bottom shelf of the fridge. Please do not share any of it with Biscuit. The vet said Biscuit must never eat grapes, and there are grapes inside.\n\nIf you finish your reading before I get home, you may feed the chickens. The scoop is hanging by the back door, and one scoopful each is plenty.\n\nSee you soon,\nGrandpa",
      attribution: "MindMosaic original",
    },
    options: [
      { id: "fridge", text: "Put the snack back in the fridge" },
      { id: "wait", text: "Wait until Grandpa gets home" },
      { id: "reading", text: "Finish his reading" },
      { id: "walk", text: "Take Biscuit for a walk" },
    ],
    visuals: [],
    answerKey: {
      kind: "single_option",
      optionId: "reading",
    },
    explanation: "The word 'If' sets a condition: 'If you finish your reading before I get home, you may feed the chickens.' So Ollie must finish his reading first. 'Wait until Grandpa gets home' is the opposite — he can feed them before Grandpa returns. Putting the snack away and walking Biscuit are never asked for.",
    metadata: {
      subject: "reading",
      strand: "Everyday text comprehension",
      topic: "Understanding a condition",
      skill: "Understanding a condition in a text",
      difficulty: "challenging",
      marks: 1,
      estimatedTimeSeconds: 85,
      tags: ["note", "inference", "conditions", "naplan style"],
    },
  },
]);
