/**
 * The authoritative skill taxonomy registry data.
 *
 * Generated once, offline, from two sources:
 *  - the production question bank (`src/content/questions`), grouped by
 *    (subject, strand, topic) — the `aliases` list captures every distinct
 *    `metadata.skill` string observed for that group;
 *  - the legacy `_HARVEST/02-question-factory/question-factory/config/skill-taxonomy.json`
 *    curriculum taxonomy, kept under its original stable id.
 *
 * This file is static data: ids are fixed strings, never recomputed from
 * `displayName` at runtime. Edit by re-running the authoring process, not
 * by hand-editing individual ids.
 */
import type { TaxonomyEntry } from "./types";

export const SKILL_TAXONOMY_ENTRIES: readonly TaxonomyEntry[] = [
  {
    id: "lang.prod.grammar.irregular-plurals",
    displayName: "Irregular plurals",
    aliases: [
      "Forming irregular plural nouns",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["short_answer"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Forming irregular plural nouns",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.grammar.sentence-types",
    displayName: "Sentence types",
    aliases: [
      "Classifying sentence types",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["matching"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Classifying sentence types",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.grammar.subject-verb-agreement",
    displayName: "Subject-verb agreement",
    aliases: [
      "Matching verbs to singular and plural subjects",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Matching verbs to singular and plural subjects",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.grammar.verb-forms-and-agreement",
    displayName: "Verb forms and agreement",
    aliases: [
      "Choosing correct verb forms",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Choosing correct verb forms",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.grammar.verb-tense",
    displayName: "Verb tense",
    aliases: [
      "Choosing the correct past tense",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Choosing the correct past tense",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.logical-language-reasoning.word-analogies",
    displayName: "Word analogies",
    aliases: [
      "Completing word analogies",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Logical language reasoning",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Completing word analogies",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.logical-language-reasoning.word-relationships",
    displayName: "Word relationships",
    aliases: [
      "Reasoning about word relationships",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Logical language reasoning",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Reasoning about word relationships",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.parts-of-speech.adverbs",
    displayName: "Adverbs",
    aliases: [
      "Recognising adverbs",
      "Identifying adverbs in sentences",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Parts of speech",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Recognising adverbs; Identifying adverbs in sentences",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.parts-of-speech.adverbs-and-adjectives",
    displayName: "Adverbs and adjectives",
    aliases: [
      "Distinguishing adverbs from adjectives",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Parts of speech",
    prerequisites: [],
    recommendedQuestionTypes: ["true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Distinguishing adverbs from adjectives",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.parts-of-speech.common-and-proper-nouns",
    displayName: "Common and proper nouns",
    aliases: [
      "Sorting common and proper nouns",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Parts of speech",
    prerequisites: [],
    recommendedQuestionTypes: ["drag_drop"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Sorting common and proper nouns",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.parts-of-speech.nouns-and-verbs",
    displayName: "Nouns and verbs",
    aliases: [
      "Sorting nouns and verbs",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Parts of speech",
    prerequisites: [],
    recommendedQuestionTypes: ["drag_drop"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Sorting nouns and verbs",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.punctuation.capital-letters",
    displayName: "Capital letters",
    aliases: [
      "Using capital letters for sentences and proper nouns",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Punctuation",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Using capital letters for sentences and proper nouns",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.punctuation.contractions",
    displayName: "Contractions",
    aliases: [
      "Forming contractions with apostrophes",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Punctuation",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Forming contractions with apostrophes",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.punctuation.possessive-apostrophes",
    displayName: "Possessive apostrophes",
    aliases: [
      "Using apostrophes for singular possession",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Punctuation",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Using apostrophes for singular possession",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.spelling.correcting-misspelt-words",
    displayName: "Correcting misspelt words",
    aliases: [
      "Spelling common adjectives",
      "Spelling commonly confused words",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Spelling",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Skill: Spelling common adjectives; Spelling commonly confused words",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.spelling.homophones",
    displayName: "Homophones",
    aliases: [
      "Choosing the correct homophone",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Spelling",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Choosing the correct homophone",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.text-structure.connectives",
    displayName: "Connectives",
    aliases: [
      "Using cause-and-effect connectives",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Text structure",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Using cause-and-effect connectives",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.text-structure.paragraph-cohesion",
    displayName: "Paragraph cohesion",
    aliases: [
      "Ordering sentences for cohesion",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Text structure",
    prerequisites: [],
    recommendedQuestionTypes: ["ordering"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Ordering sentences for cohesion",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.text-structure.parts-of-a-letter",
    displayName: "Parts of a letter",
    aliases: [
      "Identifying letter structure",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Text structure",
    prerequisites: [],
    recommendedQuestionTypes: ["label_diagram"],
    recommendedVisualTypes: ["labelled_svg"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Identifying letter structure",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.vocabulary.antonyms",
    displayName: "Antonyms",
    aliases: [
      "Matching words to their antonyms",
      "Producing antonyms",
    ],
    yearLevels: [3],
    examStyles: ["icas_style", "naplan_style"],
    subject: "language_conventions",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["matching", "short_answer"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "easy"],
    curriculumNotes: [
      "Skill: Matching words to their antonyms; Producing antonyms",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.vocabulary.figurative-language",
    displayName: "Figurative language",
    aliases: [
      "Classifying figurative language",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["matching"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Classifying figurative language",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.vocabulary.synonym-groups",
    displayName: "Synonym groups",
    aliases: [
      "Grouping words by meaning",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["drag_drop"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Grouping words by meaning",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.vocabulary.synonyms",
    displayName: "Synonyms",
    aliases: [
      "Producing synonyms",
      "Producing synonyms for formal words",
    ],
    yearLevels: [5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "language_conventions",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["short_answer"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Producing synonyms; Producing synonyms for formal words",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.vocabulary.word-meanings",
    displayName: "Word meanings",
    aliases: [
      "Matching words to definitions",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["matching"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Matching words to definitions",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.apostrophes-possession",
    displayName: "Using apostrophes to show possession",
    aliases: [
      "Using apostrophes to show possession",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Punctuation",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Correctly placing an apostrophe to show singular or plural possession.",
      "Legacy target count: 50",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.capital-letters",
    displayName: "Using capital letters correctly",
    aliases: [
      "Using capital letters correctly",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Punctuation",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Identifying where capital letters are required (sentence starts, proper nouns).",
      "Legacy target count: 40",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.complex-sentences",
    displayName: "Identifying and constructing complex sentences",
    aliases: [
      "Identifying and constructing complex sentences",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Identifying the clauses in a complex sentence and choosing the correct conjunction.",
      "Legacy target count: 35",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.full-stops-question-marks",
    displayName: "Using full stops and question marks",
    aliases: [
      "Using full stops and question marks",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Punctuation",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Choosing the correct end-of-sentence punctuation for statements and questions.",
      "Legacy target count: 40",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.nouns-verbs-adjectives",
    displayName: "Identifying nouns, verbs and adjectives",
    aliases: [
      "Identifying nouns, verbs and adjectives",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["matching", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Classifying words in a sentence by their word class.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.plurals",
    displayName: "Forming irregular plurals",
    aliases: [
      "Forming irregular plurals",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank", "short_answer"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Forming the correct plural of nouns with irregular plural forms.",
      "Legacy target count: 50",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.pronouns",
    displayName: "Using pronouns correctly",
    aliases: [
      "Using pronouns correctly",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown", "fill_blank"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Choosing the correct pronoun to replace or refer back to a noun.",
      "Legacy target count: 50",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.grammar.subject-verb-agreement",
    displayName: "Subject-verb agreement",
    aliases: [
      "Subject-verb agreement",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Matching singular or plural subjects to the correct verb form.",
      "Legacy target count: 40",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.punctuation.commas-in-lists",
    displayName: "Using commas to separate items in a list",
    aliases: [
      "Using commas to separate items in a list",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Punctuation",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Correctly placing commas when listing three or more items in a sentence.",
      "Legacy target count: 50",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.reading.authors-purpose",
    displayName: "Identifying an author's purpose",
    aliases: [
      "Identifying an author's purpose",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Identifying why an author wrote a passage (to inform, persuade or entertain).",
      "Legacy target count: 85",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.reading.compare-texts",
    displayName: "Comparing information across two short texts",
    aliases: [
      "Comparing information across two short texts",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_select", "reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Identifying similarities and differences between two short passages on a related topic.",
      "Legacy target count: 80",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.reading.figurative-language",
    displayName: "Identifying figurative language",
    aliases: [
      "Identifying figurative language",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "reading",
    strand: "Comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Identifying similes, metaphors and idioms and their intended meaning within a text.",
      "Legacy target count: 35",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.reading.inference",
    displayName: "Making inferences from a text",
    aliases: [
      "Making inferences from a text",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Drawing conclusions from clues in a passage rather than explicit statements.",
      "Legacy target count: 85",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.reading.main-idea",
    displayName: "Identifying the main idea of a passage",
    aliases: [
      "Identifying the main idea of a passage",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Identifying the central idea or topic of a short passage.",
      "Legacy target count: 75",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.reading.sequence-of-events",
    displayName: "Sequencing events in a text",
    aliases: [
      "Sequencing events in a text",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["ordering", "reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Identifying the correct order of events described in a short passage.",
      "Legacy target count: 75",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.spelling.common-words",
    displayName: "Spelling common high-frequency words",
    aliases: [
      "Spelling common high-frequency words",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Spelling",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank", "short_answer"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Correctly spelling common high-frequency words used in Year 3 writing.",
      "Legacy target count: 40",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.vocabulary.antonyms",
    displayName: "Identifying antonyms",
    aliases: [
      "Identifying antonyms",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Identifying a word with the opposite meaning to a given word.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.vocabulary.context-clues",
    displayName: "Using context clues to determine word meaning",
    aliases: [
      "Using context clues to determine word meaning",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "reading",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Determining the meaning of an unfamiliar word from surrounding sentence context.",
      "Legacy target count: 35",
    ],
    generationConstraints: [],
  },
  {
    id: "lit.vocabulary.synonyms",
    displayName: "Identifying synonyms",
    aliases: [
      "Identifying synonyms",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "language_conventions",
    strand: "Vocabulary",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Identifying a word with the closest meaning to a given word.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "num.addition.two-digit",
    displayName: "Adding two-digit numbers",
    aliases: [
      "Adding two-digit numbers",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "number_entry"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Adding two two-digit whole numbers, with and without regrouping.",
      "Legacy target count: 75",
    ],
    generationConstraints: [],
  },
  {
    id: "num.data.read-bar-chart",
    displayName: "Reading and interpreting bar charts",
    aliases: [
      "Reading and interpreting bar charts",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "number_entry"],
    recommendedVisualTypes: ["bar_chart"],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Reading values and making comparisons from a bar chart.",
      "Legacy target count: 100",
    ],
    generationConstraints: [],
  },
  {
    id: "num.data.read-line-graph",
    displayName: "Reading and interpreting line graphs",
    aliases: [
      "Reading and interpreting line graphs",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "number_entry"],
    recommendedVisualTypes: ["line_graph"],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Reading trends and specific values from a line graph.",
      "Legacy target count: 100",
    ],
    generationConstraints: [],
  },
  {
    id: "num.data.read-pie-chart",
    displayName: "Reading and interpreting pie charts",
    aliases: [
      "Reading and interpreting pie charts",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: ["pie_chart"],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Reading proportions and comparing categories from a pie chart.",
      "Legacy target count: 100",
    ],
    generationConstraints: [],
  },
  {
    id: "num.data.read-table",
    displayName: "Reading a data table",
    aliases: [
      "Reading a data table",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "number_entry"],
    recommendedVisualTypes: ["table"],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Reading values and simple totals from a table of data.",
      "Legacy target count: 75",
    ],
    generationConstraints: [],
  },
  {
    id: "num.fractions.equivalent",
    displayName: "Identifying equivalent fractions",
    aliases: [
      "Identifying equivalent fractions",
    ],
    yearLevels: [5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Fractions",
    prerequisites: [],
    recommendedQuestionTypes: ["matching", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Identifying fractions that represent the same value in simplest or unsimplified form.",
      "Legacy target count: 20",
      "PB1 remediation: naplan_style added — equivalent-fraction recognition is standard Year 5 Australian Curriculum numeracy content in both exam styles, not ICAS-exclusive. Year level and conceptual scope unchanged.",
    ],
    generationConstraints: [],
  },
  {
    id: "num.geometry.2d-shapes",
    displayName: "Identifying properties of 2D shapes",
    aliases: [
      "Identifying properties of 2D shapes",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "true_false"],
    recommendedVisualTypes: ["geometry_shape"],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Identifying 2D shapes by their number of sides and vertices.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "num.geometry.angles",
    displayName: "Classifying and estimating angles",
    aliases: [
      "Classifying and estimating angles",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown", "multiple_choice"],
    recommendedVisualTypes: ["geometry_shape"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Classifying angles as acute, right, obtuse or reflex, and estimating angle size.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "num.measurement.units",
    displayName: "Matching units of measurement",
    aliases: [
      "Matching units of measurement",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Measurement",
    prerequisites: [],
    recommendedQuestionTypes: ["matching", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Matching everyday quantities (length, mass, capacity) to their appropriate metric unit.",
      "Legacy target count: 75",
    ],
    generationConstraints: [],
  },
  {
    id: "num.number.multiples",
    displayName: "Identifying common multiples",
    aliases: [
      "Identifying common multiples",
    ],
    yearLevels: [5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "multiple_select", "true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Identifying multiples of a given number, including common multiples of two numbers.",
      "Legacy target count: 20",
      "PB1 remediation: naplan_style and true_false added — multiples reasoning is standard Year 5 Australian Curriculum numeracy content in both exam styles and is legitimately assessed via true/false reasoning items, not only selection items. Existing multiples concept unchanged.",
    ],
    generationConstraints: [],
  },
  {
    id: "num.number.odd-even",
    displayName: "Identifying odd and even numbers",
    aliases: [
      "Identifying odd and even numbers",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Recognising whether a whole number is odd or even.",
      "Legacy target count: 75",
    ],
    generationConstraints: [],
  },
  {
    id: "num.number.order-decimals",
    displayName: "Ordering decimal numbers",
    aliases: [
      "Ordering decimal numbers",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "ordering"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Ordering a set of decimal numbers from smallest to largest or vice versa.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "num.number.prime",
    displayName: "Identifying prime numbers",
    aliases: [
      "Identifying prime numbers",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Determining whether a whole number has exactly two factors.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "num.number.skip-counting",
    displayName: "Skip counting and identifying number patterns",
    aliases: [
      "Skip counting and identifying number patterns",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "number_entry"],
    recommendedVisualTypes: ["number_line"],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Continuing a skip-counting sequence and identifying the underlying pattern.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "num.patterns.number-patterns",
    displayName: "Extending and describing number patterns",
    aliases: [
      "Extending and describing number patterns",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Patterns and Algebra",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "number_entry"],
    recommendedVisualTypes: ["number_line"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Identifying the rule in a number pattern and extending it.",
      "Legacy target count: 20",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.2d-shapes",
    displayName: "2D shapes",
    aliases: [
      "Naming 2D shapes",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["label_diagram"],
    recommendedVisualTypes: ["labelled_svg"],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Naming 2D shapes",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.3d-objects",
    displayName: "3D objects",
    aliases: [
      "Naming parts of 3D objects",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["label_diagram"],
    recommendedVisualTypes: ["labelled_svg"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Naming parts of 3D objects",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.coordinates",
    displayName: "Coordinates",
    aliases: [
      "Locating points on a grid",
      "Reading coordinate pairs",
      "Filtering points by coordinate",
    ],
    yearLevels: [3, 5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["matching", "multiple_choice", "multiple_select"],
    recommendedVisualTypes: ["coordinate_grid"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Locating points on a grid; Reading coordinate pairs; Filtering points by coordinate",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.distance-on-a-grid",
    displayName: "Distance on a grid",
    aliases: [
      "Finding horizontal distance between points",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["coordinate_grid"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Finding horizontal distance between points",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.parts-of-a-circle",
    displayName: "Parts of a circle",
    aliases: [
      "Naming parts of a circle",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["label_diagram"],
    recommendedVisualTypes: ["labelled_svg"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Naming parts of a circle",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.polygons",
    displayName: "Polygons",
    aliases: [
      "Naming polygons by side count",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["label_diagram"],
    recommendedVisualTypes: ["labelled_svg"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Naming polygons by side count",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.properties-of-shapes",
    displayName: "Properties of shapes",
    aliases: [
      "Identifying a square by its properties",
      "Identifying curved and straight sides",
    ],
    yearLevels: [3],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["hotspot"],
    recommendedVisualTypes: ["hotspot_svg"],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Identifying a square by its properties; Identifying curved and straight sides",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.quadrilaterals",
    displayName: "Quadrilaterals",
    aliases: [
      "Identifying a parallelogram",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["hotspot"],
    recommendedVisualTypes: ["hotspot_svg"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Identifying a parallelogram",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.types-of-angles",
    displayName: "Types of angles",
    aliases: [
      "Classifying angles",
      "Identifying acute angles",
    ],
    yearLevels: [5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["hotspot", "label_diagram"],
    recommendedVisualTypes: ["hotspot_svg", "labelled_svg"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Classifying angles; Identifying acute angles",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.geometry.types-of-triangles",
    displayName: "Types of triangles",
    aliases: [
      "Identifying right angles in shapes",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Geometry",
    prerequisites: [],
    recommendedQuestionTypes: ["true_false"],
    recommendedVisualTypes: ["geometry_shape"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Identifying right angles in shapes",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.measurement.area-of-a-triangle",
    displayName: "Area of a triangle",
    aliases: [
      "Calculating the area of a triangle",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Measurement",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["geometry_shape"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Calculating the area of a triangle",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.measurement.perimeter",
    displayName: "Perimeter",
    aliases: [
      "Calculating the perimeter of a square",
      "Calculating the perimeter of a rectangle",
      "num.measurement.perimeter-rectangle",
    ],
    yearLevels: [3, 5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Measurement",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "number_entry", "true_false"],
    recommendedVisualTypes: ["geometry_shape"],
    supportedDifficulties: ["challenging", "medium"],
    curriculumNotes: [
      "Skill: Calculating the perimeter of a square; Calculating the perimeter of a rectangle",
      "Calculating perimeter given the length and width of a rectangle.",
      "Legacy target count: 100",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.measurement.perimeter-and-area",
    displayName: "Perimeter and area",
    aliases: [
      "Calculating perimeter and area of a rectangle",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Measurement",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank"],
    recommendedVisualTypes: ["geometry_shape"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Calculating perimeter and area of a rectangle",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.comparing-decimals",
    displayName: "Comparing decimals",
    aliases: [
      "Ordering decimals on a number line",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_select"],
    recommendedVisualTypes: ["number_line"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Ordering decimals on a number line",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.comparing-fractions",
    displayName: "Comparing fractions",
    aliases: [
      "Comparing fractions with one half",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["drag_drop"],
    recommendedVisualTypes: ["fraction_model"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Comparing fractions with one half",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.decimals",
    displayName: "Decimals",
    aliases: [
      "Reading decimals on a number line",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["number_line"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Reading decimals on a number line",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.fractions",
    displayName: "Fractions",
    aliases: [
      "Naming fractions from a model",
      "Describing a fraction model",
      "Recognising one half in different models",
    ],
    yearLevels: [3, 5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown", "fill_blank", "hotspot"],
    recommendedVisualTypes: ["fraction_model", "hotspot_svg"],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Skill: Naming fractions from a model; Describing a fraction model; Recognising one half in different models",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.fractions-of-a-set",
    displayName: "Fractions of a set",
    aliases: [
      "Finding a fraction of a collection",
    ],
    yearLevels: [3, 5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["fraction_model"],
    supportedDifficulties: ["medium", "challenging"],
    curriculumNotes: [
      "Skill: Finding a fraction of a collection",
      "PB1 remediation: Year 5 added, with 'challenging' difficulty, following the same same-id-spans-two-years pattern already used by num.prod.measurement.perimeter — the concept progresses from a unit fraction of a small set (Year 3) to a non-unit fraction of a larger amount (Year 5). Existing Year 3 support unchanged.",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.money",
    displayName: "Money",
    aliases: [
      "Adding money amounts",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["table"],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Adding money amounts",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.money-problems",
    displayName: "Money problems",
    aliases: [
      "Solving multi-step money problems",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["table"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Solving multi-step money problems",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.multiples",
    displayName: "Multiples",
    aliases: [
      "Identifying multiples of 4",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_select"],
    recommendedVisualTypes: ["number_line"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Identifying multiples of 4",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.odd-and-even-numbers",
    displayName: "Odd and even numbers",
    aliases: [
      "Identifying even numbers",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_select"],
    recommendedVisualTypes: ["number_line"],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Identifying even numbers",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.ordering-numbers",
    displayName: "Ordering numbers",
    aliases: [
      "Ordering values from a table",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["ordering"],
    recommendedVisualTypes: ["table"],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Ordering values from a table",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.skip-counting",
    displayName: "Skip counting",
    aliases: [
      "Reading a number line",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["number_line"],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Reading a number line",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.patterns.number-patterns",
    displayName: "Number patterns",
    aliases: [
      "Extending a linear pattern",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Patterns",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["line_graph"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Extending a linear pattern",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.comparing-data",
    displayName: "Comparing data",
    aliases: [
      "Comparing values in a bar chart",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["bar_chart"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Comparing values in a bar chart",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.comparing-data-with-a-benchmark",
    displayName: "Comparing data with a benchmark",
    aliases: [
      "Reading values against a threshold",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_select"],
    recommendedVisualTypes: ["bar_chart"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Reading values against a threshold",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.comparing-shares-in-a-pie-chart",
    displayName: "Comparing shares in a pie chart",
    aliases: [
      "Ordering data by size",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["ordering"],
    recommendedVisualTypes: ["pie_chart"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Ordering data by size",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.fractions-in-a-pie-chart",
    displayName: "Fractions in a pie chart",
    aliases: [
      "Relating fractions to data",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: ["pie_chart"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Relating fractions to data",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.interpreting-tables",
    displayName: "Interpreting tables",
    aliases: [
      "Comparing values in a table",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown"],
    recommendedVisualTypes: ["table"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Comparing values in a table",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.proportional-reasoning-with-data",
    displayName: "Proportional reasoning with data",
    aliases: [
      "Comparing data multiplicatively",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: ["pie_chart"],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Comparing data multiplicatively",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.range-of-a-data-set",
    displayName: "Range of a data set",
    aliases: [
      "Finding the difference between extremes",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["bar_chart"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Finding the difference between extremes",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.reading-a-bar-chart",
    displayName: "Reading a bar chart",
    aliases: [
      "Interpreting bar charts",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: ["bar_chart"],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Interpreting bar charts",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.reading-a-line-graph",
    displayName: "Reading a line graph",
    aliases: [
      "Ordering values from a graph",
      "Finding the maximum on a line graph",
      "Matching values on a line graph",
    ],
    yearLevels: [3, 5],
    examStyles: ["icas_style", "naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["matching", "multiple_choice", "ordering"],
    recommendedVisualTypes: ["line_graph"],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Skill: Ordering values from a graph; Finding the maximum on a line graph; Matching values on a line graph",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.reading-a-pie-chart",
    displayName: "Reading a pie chart",
    aliases: [
      "Relating fractions to a pie chart",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: ["pie_chart"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Relating fractions to a pie chart",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.statistics.totalling-data",
    displayName: "Totalling data",
    aliases: [
      "Adding values from a bar chart",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Statistics",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: ["bar_chart"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Adding values from a bar chart",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.fact-and-opinion.sorting-facts-and-opinions",
    displayName: "Sorting facts and opinions",
    aliases: [
      "Classifying statements as fact or opinion",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Fact and opinion",
    prerequisites: [],
    recommendedQuestionTypes: ["drag_drop"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Classifying statements as fact or opinion",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.fact-and-opinion.telling-facts-from-opinions",
    displayName: "Telling facts from opinions",
    aliases: [
      "Distinguishing fact from opinion",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Fact and opinion",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "multiple_select"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Skill: Distinguishing fact from opinion",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.inference.connecting-ideas-in-an-information-text",
    displayName: "Connecting ideas in an information text",
    aliases: [
      "Drawing conclusions from an information text",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "reading",
    strand: "Inference",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Drawing conclusions from an information text",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.inference.inferring-character-motivation",
    displayName: "Inferring character motivation",
    aliases: [
      "Inferring reasons for actions",
      "Inferring motives from actions",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Inference",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Inferring reasons for actions; Inferring motives from actions",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.inference.understanding-purpose-in-an-information-text",
    displayName: "Understanding purpose in an information text",
    aliases: [
      "Inferring purpose from an information text",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "reading",
    strand: "Inference",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Inferring purpose from an information text",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.literal-comprehension.checking-statements-against-a-text",
    displayName: "Checking statements against a text",
    aliases: [
      "Verifying details in an information text",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Literal comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Verifying details in an information text",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.literal-comprehension.combining-text-and-table-information",
    displayName: "Combining text and table information",
    aliases: [
      "Integrating text with a table",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Literal comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: ["table"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Integrating text with a table",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.literal-comprehension.finding-information-in-a-story",
    displayName: "Finding information in a story",
    aliases: [
      "Locating directly stated details",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Literal comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Locating directly stated details",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.literal-comprehension.reading-a-timetable",
    displayName: "Reading a timetable",
    aliases: [
      "Finding information in a table",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Literal comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: ["table"],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Finding information in a table",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.literal-comprehension.recalling-a-detail",
    displayName: "Recalling a detail",
    aliases: [
      "Recalling names and details",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Literal comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["short_answer"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Skill: Recalling names and details",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.literal-comprehension.verifying-statements-against-a-text",
    displayName: "Verifying statements against a text",
    aliases: [
      "Checking multiple details in a text",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Literal comprehension",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_select"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Checking multiple details in a text",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.main-idea.identifying-the-purpose-of-a-text",
    displayName: "Identifying the purpose of a text",
    aliases: [
      "Identifying author purpose",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Main idea",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Identifying author purpose",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.sequencing.following-a-procedure",
    displayName: "Following a procedure",
    aliases: [
      "Identifying the order of steps",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Sequencing",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Identifying the order of steps",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.sequencing.ordering-story-events",
    displayName: "Ordering story events",
    aliases: [
      "Sequencing events in a narrative",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Sequencing",
    prerequisites: [],
    recommendedQuestionTypes: ["ordering"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Sequencing events in a narrative",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.vocabulary-in-context.idioms",
    displayName: "Idioms",
    aliases: [
      "Interpreting idioms in context",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Vocabulary in context",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Interpreting idioms in context",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.vocabulary-in-context.word-meaning-from-context",
    displayName: "Word meaning from context",
    aliases: [
      "Using context clues for word meaning",
      "Choosing the best word meaning",
    ],
    yearLevels: [3, 5],
    examStyles: ["naplan_style"],
    subject: "reading",
    strand: "Vocabulary in context",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown", "multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Skill: Using context clues for word meaning; Choosing the best word meaning",
    ],
    generationConstraints: [],
  },
  {
    id: "write.prod.informative-writing.writing-an-information-report",
    displayName: "Writing an information report",
    aliases: [
      "Composing an information report",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "writing",
    strand: "Informative writing",
    prerequisites: [],
    recommendedQuestionTypes: ["essay"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Composing an information report",
    ],
    generationConstraints: [],
  },
  {
    id: "write.prod.narrative-writing.writing-a-short-narrative",
    displayName: "Writing a short narrative",
    aliases: [
      "Composing a narrative",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "writing",
    strand: "Narrative writing",
    prerequisites: [],
    recommendedQuestionTypes: ["essay"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Composing a narrative",
    ],
    generationConstraints: [],
  },
  {
    id: "write.prod.persuasive-writing.writing-a-persuasive-text",
    displayName: "Writing a persuasive text",
    aliases: [
      "Composing a persuasive argument",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "writing",
    strand: "Persuasive writing",
    prerequisites: [],
    recommendedQuestionTypes: ["essay"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Skill: Composing a persuasive argument",
    ],
    generationConstraints: [],
  },
  {
    id: "write.prod.procedural-writing.writing-instructions",
    displayName: "Writing instructions",
    aliases: [
      "Composing a procedure",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "writing",
    strand: "Procedural writing",
    prerequisites: [],
    recommendedQuestionTypes: ["essay"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Skill: Composing a procedure",
    ],
    generationConstraints: [],
  },

  // --- PB1 taxonomy remediation (6 new entries) ---
  // Added to cover genuine registry gaps surfaced by the PB1 pilot batch
  // adjudication: each concept below was confirmed absent under every
  // subject/strand in the registry (not merely "nearby"), and is standard
  // NAPLAN/ICAS-tested Australian Curriculum content at the stated year
  // level. See docs/reports/mission3-production/06-pb1-taxonomy-remediation.md
  // for the full adjudication record.
  {
    id: "num.prod.chance.most-likely-outcome",
    displayName: "Most likely outcome (chance and probability)",
    aliases: [
      "Most likely outcome (chance and probability)",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Chance",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Comparing the likelihood of outcomes from a described set (e.g. marbles in a bag) and identifying the most likely.",
      "New strand ('Chance'), distinct from the existing 'Statistics' strand entries, which are all chart/data-reading skills rather than likelihood reasoning.",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.place-value",
    displayName: "Place value",
    aliases: [
      "Place value",
    ],
    yearLevels: [5],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["dropdown"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["medium"],
    curriculumNotes: [
      "Identifying the place value of a digit within a multi-digit number (e.g. 'the digit 7 is in the ___ place').",
      "Year 3 place value is not yet covered here — no Year 3 PB1 evidence for this entry; add separately if/when a Year 3 candidate justifies it.",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.measurement.units-of-time",
    displayName: "Units of time",
    aliases: [
      "Units of time",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "numeracy",
    strand: "Measurement",
    prerequisites: [],
    recommendedQuestionTypes: ["ordering"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Ordering or comparing amounts of time (e.g. minutes, hours).",
      "Deliberately a separate entry from 'num.measurement.units': that entry's own curriculum note scopes it explicitly to length, mass and capacity, excluding time.",
    ],
    generationConstraints: [],
  },
  {
    id: "num.prod.number.multiplication-equal-groups",
    displayName: "Multiplication as equal groups",
    aliases: [
      "Multiplication as equal groups",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "numeracy",
    strand: "Number",
    prerequisites: [],
    recommendedQuestionTypes: ["number_entry"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Computing a product from a number of equal-size groups (e.g. '4 trays of 6 muffins').",
      "Deliberately distinct from 'num.prod.number.multiples' / 'num.number.multiples': those are multiple-identification skills ('is X a multiple of Y'), not multiplication computation.",
    ],
    generationConstraints: [],
  },
  {
    id: "read.prod.inference.inferring-from-a-narrative",
    displayName: "Inferring from a narrative",
    aliases: [
      "Inferring from a narrative",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "reading",
    strand: "Inference",
    prerequisites: [],
    recommendedQuestionTypes: ["reading_comprehension"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["challenging"],
    curriculumNotes: [
      "Inferring an unstated setting, situation, or implication from descriptive detail in a narrative passage — e.g. inferring that a garden is highly productive from descriptions of its produce, without that conclusion being stated outright.",
      "Scope note distinguishing this from 'read.prod.inference.inferring-character-motivation': that entry covers inferring *why a character acts* (motive); this entry covers inferring general facts, setting or situation from narrative detail, not character motive specifically. Use the motivation entry when the inference target is a character's reason for acting; use this entry otherwise.",
    ],
    generationConstraints: [],
  },
  {
    id: "lang.prod.grammar.regular-plurals",
    displayName: "Regular plurals",
    aliases: [
      "Regular plurals",
    ],
    yearLevels: [3],
    examStyles: ["naplan_style"],
    subject: "language_conventions",
    strand: "Grammar",
    prerequisites: [],
    recommendedQuestionTypes: ["fill_blank"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy"],
    curriculumNotes: [
      "Forming the regular plural of a noun using the -s/-es/-ies rules (e.g. 'box' -> 'boxes'), as distinct from irregular plural forms.",
      "Sibling entry to 'lang.prod.grammar.irregular-plurals' (same strand, 'Grammar', not 'Spelling' — pluralisation is a morphology/grammar rule, not rote spelling recall). Keep the two separate: this entry is regular -s/-es/-ies formation; the irregular entry is exception forms (e.g. child -> children).",
    ],
    generationConstraints: [],
  },
  {
    // Hand-authored curriculum seed for the Science subject foundation, not
    // harvested from the production bank (there is no Science content in
    // `src/content/questions/*` yet — see docs/CONTENT_STANDARDS_SCIENCE.md).
    id: "sci.biological-sciences.basic-needs-of-living-things",
    displayName: "Basic needs of living things",
    aliases: [
      "Identifying the basic needs of living things",
    ],
    yearLevels: [3],
    examStyles: ["icas_style"],
    subject: "science",
    strand: "Biological Sciences",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "true_false"],
    recommendedVisualTypes: [],
    supportedDifficulties: ["easy", "medium"],
    curriculumNotes: [
      "Living things have basic needs, including food, water and air (Australian Curriculum Year 3 Biological Sciences).",
    ],
    generationConstraints: [],
  },
  {
    id: "sci.physical-sciences.light-and-shadows",
    displayName: "Light and shadows",
    aliases: [
      "Explaining shadows formed by blocking a light source",
    ],
    yearLevels: [5],
    examStyles: ["icas_style"],
    subject: "science",
    strand: "Physical Sciences",
    prerequisites: [],
    recommendedQuestionTypes: ["multiple_choice", "label_diagram"],
    recommendedVisualTypes: ["labelled_svg"],
    supportedDifficulties: ["medium", "challenging"],
    curriculumNotes: [
      "Light from a source forms shadows when the path of light is blocked by an object (Australian Curriculum Year 5 Physical Sciences).",
    ],
    generationConstraints: [],
  },
];
