import { defineQuestions } from "../helpers/create-question";
import type { QuestionSeed } from "../types";

/**
 * Grade 5 ICAS-style Digital Technologies — 35 questions promoted from
 * staging batch `icas-y5-digital_technologies-b01` (generated by codex,
 * blind re-solved by a different model, verdict pass). Content is byte
 * -identical to the audited batch; only `status` moved to "published".
 */
export const grade5IcasDigitalTechnologies = defineQuestions([
  ...([
  {
    "id": "icas-y5-digital_technologies-b01-001",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Which component keeps files even after a tablet is switched off?",
    "options": [
      {
        "id": "a",
        "text": "Storage"
      },
      {
        "id": "b",
        "text": "Speaker"
      },
      {
        "id": "c",
        "text": "Camera"
      },
      {
        "id": "d",
        "text": "Microphone"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "a"
    },
    "explanation": "Storage is non-volatile, so it retains files without power. The other components capture or output sound and images.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Digital Systems",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "digital systems"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-002",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A weather station records 18°C. Which description identifies the data type most precisely?",
    "options": [
      {
        "id": "a",
        "text": "a picture"
      },
      {
        "id": "b",
        "text": "a number"
      },
      {
        "id": "c",
        "text": "a sound"
      },
      {
        "id": "d",
        "text": "a yes-or-no value"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "b"
    },
    "explanation": "The reading 18 is numeric data. It is not an image, audio recording or Boolean value.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-003",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A robot repeats: move forward, turn right. Which instruction is executed second?",
    "options": [
      {
        "id": "a",
        "text": "stop"
      },
      {
        "id": "b",
        "text": "move forward"
      },
      {
        "id": "c",
        "text": "turn right"
      },
      {
        "id": "d",
        "text": "turn left"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "c"
    },
    "explanation": "The listed sequence places the right turn after the forward move, so it is the second instruction.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-004",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A message asks for a password and threatens to close an account immediately. What is the safest response?",
    "options": [
      {
        "id": "a",
        "text": "Send only part of the password"
      },
      {
        "id": "b",
        "text": "Reply and ask who sent it"
      },
      {
        "id": "c",
        "text": "Forward it to classmates"
      },
      {
        "id": "d",
        "text": "Do not reply; show a trusted adult"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "d"
    },
    "explanation": "Urgency and a request for a password are warning signs. Avoid engaging and seek help from a trusted adult.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Internet & Email",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "digital citizenship and safety"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-005",
    "type": "multiple_select",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Which TWO details should usually be kept private when posting publicly?",
    "options": [
      {
        "id": "a",
        "text": "home address"
      },
      {
        "id": "b",
        "text": "favourite fruit"
      },
      {
        "id": "c",
        "text": "account password"
      },
      {
        "id": "d",
        "text": "preferred sport"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "multiple_options",
      "optionIds": [
        "a",
        "c"
      ]
    },
    "explanation": "A home address can locate a person and a password can unlock an account. General preferences do not usually provide such access.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Internet & Email",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "digital citizenship and safety"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-006",
    "type": "true_false",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A keyboard is mainly an input device.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "boolean",
      "value": true
    },
    "explanation": "A keyboard sends letters and commands into a digital system, so it is an input device.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Digital Systems",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "digital systems"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-007",
    "type": "ordering",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Put the steps for saving a new drawing in a sensible order.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "ordering",
      "optionIds": [
        "step-2",
        "step-1",
        "step-3",
        "step-4"
      ]
    },
    "explanation": "The content must exist before saving; then choose its location, name it clearly and confirm.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    },
    "interaction": {
      "type": "ordering",
      "items": [
        {
          "id": "step-1",
          "text": "Choose a folder"
        },
        {
          "id": "step-2",
          "text": "Create the drawing"
        },
        {
          "id": "step-3",
          "text": "Enter a useful file name"
        },
        {
          "id": "step-4",
          "text": "Confirm the save"
        }
      ]
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-008",
    "type": "matching",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Match each device with its main role.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "matching",
      "pairs": [
        {
          "sourceId": "source-1",
          "targetId": "target-2"
        },
        {
          "sourceId": "source-2",
          "targetId": "target-3"
        },
        {
          "sourceId": "source-3",
          "targetId": "target-1"
        }
      ]
    },
    "explanation": "A microphone captures sound, a monitor displays on a screen, and a printer produces paper output.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Digital Systems",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "digital systems"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    },
    "interaction": {
      "type": "matching",
      "sources": [
        {
          "id": "source-1",
          "text": "microphone"
        },
        {
          "id": "source-2",
          "text": "monitor"
        },
        {
          "id": "source-3",
          "text": "printer"
        }
      ],
      "targets": [
        {
          "id": "target-1",
          "text": "paper output"
        },
        {
          "id": "target-2",
          "text": "sound input"
        },
        {
          "id": "target-3",
          "text": "screen output"
        }
      ]
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-009",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Which file name best helps someone identify a photo from a school garden survey?",
    "options": [
      {
        "id": "a",
        "text": "garden-survey-march"
      },
      {
        "id": "b",
        "text": "newfile"
      },
      {
        "id": "c",
        "text": "photo"
      },
      {
        "id": "d",
        "text": "image1"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "a"
    },
    "explanation": "The descriptive name states the subject and time. The other names give almost no clue about the file.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-010",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A light turns on only when a sensor reads 'dark'. This is an example of what?",
    "options": [
      {
        "id": "a",
        "text": "a password"
      },
      {
        "id": "b",
        "text": "a condition"
      },
      {
        "id": "c",
        "text": "a folder"
      },
      {
        "id": "d",
        "text": "a pixel"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "b"
    },
    "explanation": "The sensor result is tested as a condition that decides whether the light turns on.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-011",
    "type": "drag_drop",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Sort each item by its data form.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "drag_drop",
      "placements": {
        "item-1": "zone-1",
        "item-2": "zone-2",
        "item-3": "zone-3"
      }
    },
    "explanation": "27 is numeric, WAV commonly stores audio, and PNG commonly stores an image.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "easy",
      "marks": 1,
      "estimatedTimeSeconds": 45,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    },
    "interaction": {
      "type": "drag_drop",
      "items": [
        {
          "id": "item-1",
          "text": "27"
        },
        {
          "id": "item-2",
          "text": "welcome.wav"
        },
        {
          "id": "item-3",
          "text": "map.png"
        }
      ],
      "zones": [
        {
          "id": "zone-1",
          "label": "number"
        },
        {
          "id": "zone-2",
          "label": "sound"
        },
        {
          "id": "zone-3",
          "label": "image"
        }
      ]
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-012",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "The table shows four records. Which record has a missing value?",
    "options": [
      {
        "id": "a",
        "text": "R1"
      },
      {
        "id": "b",
        "text": "R2"
      },
      {
        "id": "c",
        "text": "R3"
      },
      {
        "id": "d",
        "text": "R4"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-012-1",
        "type": "table",
        "altText": "Table of records and scores: R1 14, R2 9, R3 has a blank score, and R4 17.",
        "data": {
          "headers": [
            "Record",
            "Score"
          ],
          "rows": [
            [
              "R1",
              14
            ],
            [
              "R2",
              9
            ],
            [
              "R3",
              ""
            ],
            [
              "R4",
              17
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "c"
    },
    "explanation": "R3 has no entry in the Score column, while every other record has both fields.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-013",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A wireless mouse stops responding, but the computer and keyboard still work. Which check is most directly related to the mouse?",
    "options": [
      {
        "id": "a",
        "text": "Replace the monitor"
      },
      {
        "id": "b",
        "text": "Check the mouse battery"
      },
      {
        "id": "c",
        "text": "Rename a document"
      },
      {
        "id": "d",
        "text": "Increase speaker volume"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "b"
    },
    "explanation": "A wireless mouse needs power, so its battery is the most relevant first check. The other actions affect unrelated parts.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Digital Systems",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "digital systems"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-014",
    "type": "multiple_select",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Which TWO instructions contain a clear condition?",
    "options": [
      {
        "id": "a",
        "text": "Repeat four times"
      },
      {
        "id": "b",
        "text": "If the gate is open, move forward"
      },
      {
        "id": "c",
        "text": "Draw a blue square"
      },
      {
        "id": "d",
        "text": "When the timer reaches zero, stop"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "multiple_options",
      "optionIds": [
        "b",
        "d"
      ]
    },
    "explanation": "Both correct instructions test an event or state before acting. A fixed repeat and a direct drawing command do not test conditions.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-015",
    "type": "true_false",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Sorting a list changes the order of its records but does not have to change the values stored in them.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "boolean",
      "value": true
    },
    "explanation": "Sorting rearranges records according to a rule; the values within those records can remain unchanged.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-016",
    "type": "ordering",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Put the steps for finding the largest number in a list into a workable algorithm.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "ordering",
      "optionIds": [
        "step-2",
        "step-1",
        "step-3",
        "step-4"
      ]
    },
    "explanation": "Begin with a valid candidate, compare each later value, update only when larger, then report the final candidate.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    },
    "interaction": {
      "type": "ordering",
      "items": [
        {
          "id": "step-1",
          "text": "Compare the next number with the remembered number"
        },
        {
          "id": "step-2",
          "text": "Remember the first number"
        },
        {
          "id": "step-3",
          "text": "Replace the remembered number if the next is larger"
        },
        {
          "id": "step-4",
          "text": "Report the remembered number after all comparisons"
        }
      ]
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-017",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A sensor log is shown. At which time did the value first exceed 20?",
    "options": [
      {
        "id": "a",
        "text": "09:00"
      },
      {
        "id": "b",
        "text": "09:10"
      },
      {
        "id": "c",
        "text": "09:20"
      },
      {
        "id": "d",
        "text": "09:30"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-017-1",
        "type": "table",
        "altText": "Sensor log: 09:00 value 16, 09:10 value 20, 09:20 value 23, and 09:30 value 21.",
        "data": {
          "headers": [
            "Time",
            "Value"
          ],
          "rows": [
            [
              "09:00",
              16
            ],
            [
              "09:10",
              20
            ],
            [
              "09:20",
              23
            ],
            [
              "09:30",
              21
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "c"
    },
    "explanation": "The values at 09:00 and 09:10 are not above 20. The 09:20 value is 23, the first value that exceeds 20.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-018",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A class wants to reuse an online image in a public webpage. What should they check first?",
    "options": [
      {
        "id": "a",
        "text": "whether the image is colourful"
      },
      {
        "id": "b",
        "text": "whether they have permission or a suitable licence"
      },
      {
        "id": "c",
        "text": "whether the file name is short"
      },
      {
        "id": "d",
        "text": "whether friends like the image"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "b"
    },
    "explanation": "Public availability does not automatically grant reuse rights. Permission or an appropriate licence is the relevant check.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Internet & Email",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "digital citizenship and safety"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-019",
    "type": "matching",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Match each data task with the best operation.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "matching",
      "pairs": [
        {
          "sourceId": "source-1",
          "targetId": "target-2"
        },
        {
          "sourceId": "source-2",
          "targetId": "target-3"
        },
        {
          "sourceId": "source-3",
          "targetId": "target-1"
        }
      ]
    },
    "explanation": "Filtering selects matching records, sorting orders dates, and editing corrects the stored suburb.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    },
    "interaction": {
      "type": "matching",
      "sources": [
        {
          "id": "source-1",
          "text": "show only red bicycles"
        },
        {
          "id": "source-2",
          "text": "put dates from earliest to latest"
        },
        {
          "id": "source-3",
          "text": "fix a misspelled suburb"
        }
      ],
      "targets": [
        {
          "id": "target-1",
          "text": "edit a value"
        },
        {
          "id": "target-2",
          "text": "filter records"
        },
        {
          "id": "target-3",
          "text": "sort records"
        }
      ]
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-020",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A robot follows: repeat 3 times [move 2 squares, turn right]. How many squares does it move altogether?",
    "options": [
      {
        "id": "a",
        "text": "2"
      },
      {
        "id": "b",
        "text": "3"
      },
      {
        "id": "c",
        "text": "5"
      },
      {
        "id": "d",
        "text": "6"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "d"
    },
    "explanation": "Each of three repeats moves two squares, giving 3 × 2 = 6 squares. Turning changes direction but adds no distance.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-021",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Which animal has the greatest increase from Monday to Tuesday?",
    "options": [
      {
        "id": "a",
        "text": "kookaburra"
      },
      {
        "id": "b",
        "text": "magpie"
      },
      {
        "id": "c",
        "text": "lorikeet"
      },
      {
        "id": "d",
        "text": "galah"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-021-1",
        "type": "table",
        "altText": "Bird counts: kookaburra 5 Monday and 9 Tuesday; magpie 8 and 6; lorikeet 2 and 5; galah 4 and 5.",
        "data": {
          "headers": [
            "Animal",
            "Monday",
            "Tuesday"
          ],
          "rows": [
            [
              "kookaburra",
              5,
              9
            ],
            [
              "magpie",
              8,
              6
            ],
            [
              "lorikeet",
              2,
              5
            ],
            [
              "galah",
              4,
              5
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "a"
    },
    "explanation": "The changes are +4, −2, +3 and +1 respectively, so the kookaburra count increases the most.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-022",
    "type": "drag_drop",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Sort each action by whether it is safe to do without further checking.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "drag_drop",
      "placements": {
        "item-1": "zone-1",
        "item-2": "zone-2",
        "item-3": "zone-1",
        "item-4": "zone-2"
      }
    },
    "explanation": "A nickname limits exposure and reporting bullying seeks help. Unexpected attachments and public live locations create security or privacy risks.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Internet & Email",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "digital citizenship and safety"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    },
    "interaction": {
      "type": "drag_drop",
      "items": [
        {
          "id": "item-1",
          "text": "Use a nickname in a public game"
        },
        {
          "id": "item-2",
          "text": "Open an unexpected attachment"
        },
        {
          "id": "item-3",
          "text": "Tell a trusted adult about bullying"
        },
        {
          "id": "item-4",
          "text": "Share a live location publicly"
        }
      ],
      "zones": [
        {
          "id": "zone-1",
          "label": "generally safe"
        },
        {
          "id": "zone-2",
          "label": "needs checking or should be avoided"
        }
      ]
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-023",
    "type": "multiple_select",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A video call has clear pictures but nobody can hear one student. Which TWO checks are most relevant?",
    "options": [
      {
        "id": "a",
        "text": "microphone permission"
      },
      {
        "id": "b",
        "text": "microphone mute setting"
      },
      {
        "id": "c",
        "text": "screen brightness"
      },
      {
        "id": "d",
        "text": "printer paper"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "multiple_options",
      "optionIds": [
        "a",
        "b"
      ]
    },
    "explanation": "Audio input depends on microphone access and mute state. Brightness and printer paper cannot restore captured sound.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Digital Systems",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "digital systems"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-024",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "An algorithm says: if score > 10, display 'high'; otherwise display 'low'. What appears for a score of 10?",
    "options": [
      {
        "id": "a",
        "text": "high"
      },
      {
        "id": "b",
        "text": "both words"
      },
      {
        "id": "c",
        "text": "nothing"
      },
      {
        "id": "d",
        "text": "low"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "d"
    },
    "explanation": "The condition requires a value greater than 10. Ten is not greater than 10, so the otherwise branch displays low.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-025",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "The table is sorted by which field?",
    "options": [
      {
        "id": "a",
        "text": "Item alphabetically"
      },
      {
        "id": "b",
        "text": "Quantity from smallest to largest"
      },
      {
        "id": "c",
        "text": "Shelf alphabetically"
      },
      {
        "id": "d",
        "text": "Quantity from largest to smallest"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-025-1",
        "type": "table",
        "altText": "Inventory rows: Tape shelf C quantity 2; Card A 5; Pens D 7; Clips B 11.",
        "data": {
          "headers": [
            "Item",
            "Shelf",
            "Quantity"
          ],
          "rows": [
            [
              "Tape",
              "C",
              2
            ],
            [
              "Card",
              "A",
              5
            ],
            [
              "Pens",
              "D",
              7
            ],
            [
              "Clips",
              "B",
              11
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "b"
    },
    "explanation": "The quantities rise 2, 5, 7, 11. Neither text column is alphabetically ordered.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-026",
    "type": "true_false",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Deleting a post always removes every copy that other people may have saved.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "boolean",
      "value": false
    },
    "explanation": "Other people may already have copied, downloaded or captured a post, so deleting the original cannot guarantee every copy disappears.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Internet & Email",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "digital citizenship and safety"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-027",
    "type": "ordering",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Arrange these checks to test a four-digit code efficiently from left to right.",
    "options": [],
    "visuals": [],
    "answerKey": {
      "kind": "ordering",
      "optionIds": [
        "step-2",
        "step-4",
        "step-1",
        "step-3"
      ]
    },
    "explanation": "A left-to-right comparison checks positions 1, 2, 3 and then 4; mismatches can be found as early as possible.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "medium",
      "marks": 1,
      "estimatedTimeSeconds": 65,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    },
    "interaction": {
      "type": "ordering",
      "items": [
        {
          "id": "step-1",
          "text": "Compare digit 3"
        },
        {
          "id": "step-2",
          "text": "Compare digit 1"
        },
        {
          "id": "step-3",
          "text": "Compare digit 4"
        },
        {
          "id": "step-4",
          "text": "Compare digit 2"
        }
      ]
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-028",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Which rule selects exactly records P and R?",
    "options": [
      {
        "id": "a",
        "text": "Colour is blue AND score is above 12"
      },
      {
        "id": "b",
        "text": "Colour is blue"
      },
      {
        "id": "c",
        "text": "Score is below 18"
      },
      {
        "id": "d",
        "text": "Score is above 12"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-028-1",
        "type": "table",
        "altText": "Records: P blue score 14; Q blue score 12; R green score 19; S green score 8.",
        "data": {
          "headers": [
            "Record",
            "Colour",
            "Score"
          ],
          "rows": [
            [
              "P",
              "blue",
              14
            ],
            [
              "Q",
              "blue",
              12
            ],
            [
              "R",
              "green",
              19
            ],
            [
              "S",
              "green",
              8
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "d"
    },
    "explanation": "P and R have scores 14 and 19, both above 12. Q scores 12 and S scores 8, so neither passes. The other rules select different sets.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-029",
    "type": "multiple_select",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A robot should water a pot only when soil is dry AND the tank is not empty. Which TWO situations make it water?",
    "options": [
      {
        "id": "a",
        "text": "dry soil, full tank"
      },
      {
        "id": "b",
        "text": "wet soil, full tank"
      },
      {
        "id": "c",
        "text": "dry soil, half-full tank"
      },
      {
        "id": "d",
        "text": "dry soil, empty tank"
      },
      {
        "id": "e",
        "text": "wet soil, empty tank"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "multiple_options",
      "optionIds": [
        "a",
        "c"
      ]
    },
    "explanation": "Both required conditions hold only when the soil is dry and some water remains. Wet soil or an empty tank prevents watering.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-030",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A code replaces each letter with the next letter in the alphabet. Which output represents DATA?",
    "options": [
      {
        "id": "a",
        "text": "EBUB"
      },
      {
        "id": "b",
        "text": "DBUB"
      },
      {
        "id": "c",
        "text": "EBTA"
      },
      {
        "id": "d",
        "text": "FCVC"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-030-1",
        "type": "table",
        "altText": "Letter rule examples: A becomes B, B becomes C, C becomes D, D becomes E, and T becomes U.",
        "data": {
          "headers": [
            "Input",
            "A",
            "B",
            "C",
            "D",
            "T"
          ],
          "rows": [
            [
              "Output",
              "B",
              "C",
              "D",
              "E",
              "U"
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "a"
    },
    "explanation": "Advancing D, A, T, A by one letter gives E, B, U, B. Each other option changes at least one position incorrectly.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-031",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Four images total 18 MB. A device has 15 MB free. Which plan stores all four without deleting other files?",
    "options": [
      {
        "id": "a",
        "text": "Copy all images unchanged"
      },
      {
        "id": "b",
        "text": "Rename the four images"
      },
      {
        "id": "c",
        "text": "Compress them to a total below 15 MB"
      },
      {
        "id": "d",
        "text": "Put them in one folder"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "c"
    },
    "explanation": "The total must be reduced below the available 15 MB. Renaming or regrouping files does not reduce their stored data.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Digital Systems",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "digital systems"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-032",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "Two routes control a robot. Route X uses 8 move commands and 3 turns. Route Y reaches the same place using 6 move commands and 3 turns. If each command takes equal time, which claim is supported?",
    "options": [
      {
        "id": "a",
        "text": "Route X is safer"
      },
      {
        "id": "b",
        "text": "Route X uses less memory"
      },
      {
        "id": "c",
        "text": "Both routes take equal time"
      },
      {
        "id": "d",
        "text": "Route Y uses fewer commands"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-032-1",
        "type": "table",
        "altText": "Route X has 8 move commands and 3 turns. Route Y has 6 move commands and 3 turns.",
        "data": {
          "headers": [
            "Route",
            "Move commands",
            "Turn commands"
          ],
          "rows": [
            [
              "X",
              8,
              3
            ],
            [
              "Y",
              6,
              3
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "d"
    },
    "explanation": "Route Y uses 9 commands in total, compared with 11 for Route X. Equal command times therefore make Y the shorter instruction sequence.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-033",
    "type": "multiple_select",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A quiz app asks for birth date, precise location, favourite colour and a display name. Which TWO requests are least necessary for running a general knowledge quiz and create the greatest privacy concern?",
    "options": [
      {
        "id": "a",
        "text": "birth date"
      },
      {
        "id": "b",
        "text": "precise location"
      },
      {
        "id": "c",
        "text": "favourite colour"
      },
      {
        "id": "d",
        "text": "display name"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "multiple_options",
      "optionIds": [
        "a",
        "b"
      ]
    },
    "explanation": "A general quiz does not need an exact birth date or precise location, and both can reveal sensitive personal details. A display name supports play, while favourite colour is less identifying.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Internet & Email",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "digital citizenship and safety"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-034",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A counter starts at 1. Repeat three times: double the counter, then add 1. What is the final value?",
    "options": [
      {
        "id": "a",
        "text": "7"
      },
      {
        "id": "b",
        "text": "9"
      },
      {
        "id": "c",
        "text": "15"
      },
      {
        "id": "d",
        "text": "16"
      }
    ],
    "visuals": [
      {
        "id": "visual-icas-y5-digital_technologies-b01-034-1",
        "type": "table",
        "altText": "Trace table: repeat 1 goes 1 to 2 to 3; repeat 2 goes 3 to 6 to 7; repeat 3 goes 7 to 14 to 15.",
        "data": {
          "headers": [
            "Repeat",
            "Start",
            "After doubling",
            "After adding 1"
          ],
          "rows": [
            [
              1,
              1,
              2,
              3
            ],
            [
              2,
              3,
              6,
              7
            ],
            [
              3,
              7,
              14,
              15
            ]
          ],
          "rowHeaders": false
        }
      }
    ],
    "answerKey": {
      "kind": "single_option",
      "optionId": "c"
    },
    "explanation": "The successive values are 3, 7 and 15. The update must be completed in that order during each repeat.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Programming",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "algorithms"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  },
  {
    "id": "icas-y5-digital_technologies-b01-035",
    "type": "multiple_choice",
    "yearLevel": 5,
    "examStyle": "icas_style",
    "status": "published",
    "origin": "original_seed",
    "prompt": "A database has 40 records. A filter shows 18 red items. A second condition keeps only red items heavier than 2 kg, leaving 7 records. What can be concluded?",
    "options": [
      {
        "id": "a",
        "text": "All 7 are red and heavier than 2 kg"
      },
      {
        "id": "b",
        "text": "Exactly 11 red items weigh 2 kg"
      },
      {
        "id": "c",
        "text": "All 18 red items are heavier than 2 kg"
      },
      {
        "id": "d",
        "text": "The other 22 items are all blue"
      }
    ],
    "visuals": [],
    "answerKey": {
      "kind": "single_option",
      "optionId": "a"
    },
    "explanation": "The combined filter requires both conditions, so every remaining record is red and heavier than 2 kg. The counts do not reveal exact weights or colours of excluded records.",
    "metadata": {
      "subject": "digital_technologies",
      "strand": "Spreadsheets & Databases",
      "topic": "Digital technologies reasoning",
      "skill": "Apply digital technologies concepts",
      "difficulty": "challenging",
      "marks": 1,
      "estimatedTimeSeconds": 90,
      "tags": [
        "digital technologies",
        "data and information"
      ],
      "locale": "en-AU",
      "source": "original",
      "schemaVersion": 1
    }
  }
  ] as QuestionSeed[]),
]);
