import { defineQuestions } from "../helpers/create-question";

/**
 * Grade 5 NAPLAN-style Reading — 11 original questions.
 * Every passage is newly written MindMosaic content.
 */
export const grade5NaplanReading = defineQuestions([
  {
    id: "g5-nap-read-infer-001",
    type: "reading_comprehension",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Why did Mrs Okafor most likely leave the biscuits on the doorstep?",
    instructions: "Read the story, then choose one answer.",
    stimulus: {
      title: "The New Neighbour",
      body: "The moving truck had barely rumbled away when Asha noticed the old woman next door watching from her verandah. Mrs Okafor, the letterbox said. For the first week, Asha's family was too busy unpacking boxes to say hello to anyone. Every evening, Asha's parents came home from their new jobs looking worn out, and dinner was toast more often than not. On Friday morning, Asha opened the front door and nearly stepped on a tin. Inside, under a sheet of baking paper, sat two dozen golden biscuits, still warm. There was no note, but across the fence, Mrs Okafor's curtain twitched, and Asha was sure she could hear someone humming.",
    },
    options: [
      { id: "welcome-family", text: "She wanted to welcome the busy new family" },
      { id: "too-many", text: "She had baked too many biscuits by mistake" },
      { id: "asked-to", text: "Asha's parents had asked her for help" },
      { id: "selling", text: "She was selling biscuits to the neighbourhood" },
    ],
    answerKey: { kind: "single_option", optionId: "welcome-family" },
    explanation:
      "Mrs Okafor watched the new family arrive and saw how busy and tired they were. Leaving warm biscuits without a note, then humming behind her curtain, suggests a quiet act of welcome, not a mistake, a request or a sale.",
    metadata: {
      subject: "reading",
      strand: "Inference",
      topic: "Inferring character motivation",
      skill: "Inferring motives from actions",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 150,
      tags: ["narrative", "inference"],
    },
  },
  {
    id: "g5-nap-read-table-001",
    type: "reading_comprehension",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "According to the text and the table, which class won the Golden Bin award?",
    instructions: "Read the text and use the table, then choose one answer.",
    stimulus: {
      title: "Recycling at Redgum Primary",
      body: "This term, Redgum Primary ran a recycling challenge. Each class collected paper and cardboard in its own bin, and the office weighed every bin at the end of the term. The rules were simple: the class that recycled the greatest mass of paper would win the Golden Bin award and an extra sports session. The results for the four senior classes are shown in the table.",
    },
    options: [
      { id: "class-5a", text: "5A" },
      { id: "class-5b", text: "5B" },
      { id: "class-6a", text: "6A" },
      { id: "class-6b", text: "6B" },
    ],
    visuals: [
      {
        id: "g5-recycling-table",
        type: "table",
        title: "Paper recycled this term",
        altText:
          "Table showing paper recycled: class 5A collected 26 kilograms, 5B collected 32, 6A collected 29 and 6B collected 24.",
        data: {
          headers: ["Class", "Paper recycled in kilograms"],
          rows: [
            ["5A", 26],
            ["5B", 32],
            ["6A", 29],
            ["6B", 24],
          ],
          rowHeaders: true,
        },
      },
    ],
    answerKey: { kind: "single_option", optionId: "class-5b" },
    explanation:
      "The text says the award goes to the class that recycled the greatest mass of paper. The table shows 5B collected 32 kilograms, more than 5A, 6A and 6B, so 5B won the Golden Bin award.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Combining text and table information",
      skill: "Integrating text with a table",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 150,
      tags: ["information-text", "table"],
    },
  },
  {
    id: "g5-nap-read-main-001",
    type: "reading_comprehension",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "What is the main purpose of Jasper's letter?",
    instructions: "Read the letter, then choose one answer.",
    stimulus: {
      title: "A Letter to the Principal",
      body: "Dear Mrs Nguyen,\n\nI am writing to ask the school to build a vegetable garden behind the library. At the moment, that corner of the yard is bare dirt that turns to mud every winter, and nobody can use it. A garden would fix this wasted space and give every class a chance to learn outdoors. Students could grow tomatoes, beans and herbs for the canteen, which would make our lunches fresher and cheaper. Caring for the garden would also teach responsibility, because plants do not water themselves. Our neighbouring school built a garden last year, and their principal says students now race each other to the watering cans. I hope you will consider this idea.\n\nYours sincerely,\nJasper, Year 5",
    },
    options: [
      { id: "complain-mud", text: "To complain about the muddy corner of the yard" },
      { id: "persuade-garden", text: "To persuade the school to build a vegetable garden" },
      { id: "describe-canteen", text: "To describe the food sold at the canteen" },
      { id: "praise-neighbour", text: "To praise the neighbouring school's principal" },
    ],
    answerKey: { kind: "single_option", optionId: "persuade-garden" },
    explanation:
      "Jasper opens by asking the school to build a vegetable garden and then gives reasons to support the idea. The mud, the canteen and the neighbouring school are all supporting arguments, not the main purpose.",
    metadata: {
      subject: "reading",
      strand: "Main idea",
      topic: "Identifying the purpose of a text",
      skill: "Identifying author purpose",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 150,
      tags: ["persuasive", "main-idea"],
    },
  },
  {
    id: "g5-nap-read-vocab-001",
    type: "multiple_choice",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "In this sentence, what does 'reluctant' mean?",
    instructions: "Read the sentence, then choose one answer.",
    stimulus: {
      body: "Priya was reluctant to hand over her library book, because she had not finished the final chapter.",
    },
    options: [
      { id: "unwilling", text: "Unwilling" },
      { id: "delighted", text: "Delighted" },
      { id: "careless", text: "Careless" },
      { id: "confused", text: "Confused" },
    ],
    answerKey: { kind: "single_option", optionId: "unwilling" },
    explanation:
      "Priya did not want to hand the book over because she had not finished it, so 'reluctant' means unwilling.",
    metadata: {
      subject: "reading",
      strand: "Vocabulary in context",
      topic: "Word meaning from context",
      skill: "Using context clues for word meaning",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["vocabulary"],
    },
  },
  {
    id: "g5-nap-read-fact-001",
    type: "multiple_choice",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Which of these sentences is an opinion?",
    instructions: "A fact can be checked. An opinion is what someone thinks or feels.",
    options: [
      { id: "capital", text: "Canberra is the capital city of Australia." },
      { id: "planets", text: "Eight planets orbit the Sun." },
      { id: "cricket", text: "Cricket is the most enjoyable sport to watch." },
      { id: "koalas", text: "Koalas mostly eat eucalyptus leaves." },
    ],
    answerKey: { kind: "single_option", optionId: "cricket" },
    explanation:
      "Whether cricket is enjoyable is a personal judgement that cannot be checked, so it is an opinion. The other three statements can be verified.",
    metadata: {
      subject: "reading",
      strand: "Fact and opinion",
      topic: "Telling facts from opinions",
      skill: "Distinguishing fact from opinion",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["fact-opinion"],
    },
  },
  {
    id: "g5-nap-read-literal-001",
    type: "multiple_select",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Select the two statements that are true according to the text.",
    instructions: "Read the text carefully, then choose two answers.",
    stimulus: {
      title: "The Fogline Express",
      body: "The Fogline Express is a miniature railway that runs through the hills behind Clearwater Bay every Sunday. Volunteers built the little red train more than forty years ago, and volunteers still drive it today. The full loop takes twenty-five minutes and passes two waterfalls, a fern gully and an old timber bridge. Tickets are sold only at the station gate, never online, and every cent goes towards keeping the train running.",
    },
    options: [
      { id: "runs-sunday", text: "The train runs on Sundays." },
      { id: "online-tickets", text: "Tickets can be bought online." },
      { id: "volunteers-drive", text: "Volunteers drive the train." },
      { id: "one-waterfall", text: "The loop passes exactly one waterfall." },
    ],
    answerKey: {
      kind: "multiple_options",
      optionIds: ["runs-sunday", "volunteers-drive"],
    },
    explanation:
      "The text says the railway runs every Sunday and that volunteers still drive the train. Tickets are sold only at the gate, never online, and the loop passes two waterfalls, not one.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Verifying statements against a text",
      skill: "Checking multiple details in a text",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 150,
      tags: ["information-text"],
    },
  },
  {
    id: "g5-nap-read-literal-002",
    type: "true_false",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt:
      "True or false? According to the text, the lighthouse keeper's job ended because the light became automatic.",
    instructions: "Read the text, then choose true or false.",
    stimulus: {
      title: "The Last Keeper of Gull Point",
      body: "For ninety years, a keeper lived beside the lighthouse at Gull Point. The keeper's job was to wind the great clockwork every four hours and polish the lens until it flashed like a diamond. In 1989, engineers fitted an automatic electric lamp that could switch itself on at dusk. After that, no keeper was needed, and the last one, Mr Alvi, moved down to the town below. Visitors can still climb the tower on weekends, and locals say the light has never missed a single night.",
    },
    answerKey: { kind: "boolean", value: true },
    explanation:
      "The text says engineers fitted an automatic electric lamp in 1989 and that no keeper was needed after that, so the statement is true.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Checking statements against a text",
      skill: "Verifying details in an information text",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["information-text"],
    },
  },
  {
    id: "g5-nap-read-sequence-001",
    type: "ordering",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Arrange the events from the sleepover in the order they happened.",
    instructions: "Read the story, then arrange the events from first to last.",
    stimulus: {
      title: "The School Sleepover",
      body: "The Year 5 sleepover began with rolling out sleeping bags between the library shelves. Once everyone had claimed a spot, Ms Tran dimmed the lights and read a ghost story that made even the brave kids inch closer together. Afterwards, the class crept out to the oval with torches to look for the possum that lived in the old fig tree. They spotted her almost at once, two shining eyes in the dark. Back inside, hot chocolate was waiting, and one by one the torch beams went out.",
    },
    interaction: {
      type: "ordering",
      items: [
        { id: "event-bags", text: "Sleeping bags are rolled out in the library" },
        { id: "event-story", text: "Ms Tran reads a ghost story" },
        { id: "event-possum", text: "The class spots the possum on the oval" },
        { id: "event-chocolate", text: "The class drinks hot chocolate" },
      ],
    },
    answerKey: {
      kind: "ordering",
      optionIds: ["event-bags", "event-story", "event-possum", "event-chocolate"],
    },
    explanation:
      "The story begins with rolling out sleeping bags, then Ms Tran reads the ghost story, then the class goes outside and spots the possum, and finally they drink hot chocolate back inside.",
    metadata: {
      subject: "reading",
      strand: "Sequencing",
      topic: "Ordering story events",
      skill: "Sequencing events in a narrative",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 150,
      tags: ["narrative", "sequencing"],
    },
  },
  {
    id: "g5-nap-read-literal-003",
    type: "short_answer",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "In which town is the market held?",
    instructions: "Read the text, then write the name of the town.",
    stimulus: {
      title: "Market Morning",
      body: "Every second Saturday, the town of Willowmere wakes early. By seven o'clock, the main street is lined with stalls selling honey, warm bread, beeswax candles and crates of oranges from the river flats. Buskers tune their guitars near the fountain while the smell of toasted cheese drifts from the community stall. Locals say you have not really lived in Willowmere until you have queued for the famous apple doughnuts.",
    },
    answerKey: {
      kind: "text",
      acceptableAnswers: ["Willowmere"],
      caseSensitive: false,
      trimWhitespace: true,
    },
    explanation:
      "The text says the town of Willowmere wakes early on market mornings, so the market is held in Willowmere.",
    metadata: {
      subject: "reading",
      strand: "Literal comprehension",
      topic: "Recalling a detail",
      skill: "Recalling names and details",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["information-text"],
    },
  },
  {
    id: "g5-nap-read-vocab-002",
    type: "dropdown",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Choose the best meaning for the phrase as it is used in the sentence.",
    instructions: "Read the sentence, then pick one answer from the box.",
    stimulus: {
      body: "When Leila saw her painting hanging in the front window of the gallery, she was over the moon.",
    },
    interaction: {
      type: "dropdown",
      fields: [
        {
          id: "idiom-meaning",
          label: "In this sentence, 'over the moon' means",
          options: [
            { id: "extremely-happy", text: "extremely happy" },
            { id: "very-surprised", text: "very surprised" },
            { id: "far-away", text: "far away" },
            { id: "quite-tired", text: "quite tired" },
          ],
        },
      ],
    },
    answerKey: {
      kind: "dropdown",
      fields: [{ id: "idiom-meaning", correctOptionId: "extremely-happy" }],
    },
    explanation:
      "Seeing her painting displayed in the gallery window is a proud, joyful moment, so the idiom 'over the moon' means extremely happy.",
    metadata: {
      subject: "reading",
      strand: "Vocabulary in context",
      topic: "Idioms",
      skill: "Interpreting idioms in context",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 60,
      tags: ["idioms", "vocabulary"],
    },
  },
  {
    id: "g5-nap-read-fact-002",
    type: "drag_drop",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    origin: "original_seed",
    prompt: "Sort each statement into the correct group: fact or opinion.",
    instructions:
      "A fact can be checked. An opinion is what someone thinks or feels. Drag each statement into the correct group.",
    interaction: {
      type: "drag_drop",
      items: [
        { id: "stmt-canberra", text: "Canberra is the capital of Australia." },
        { id: "stmt-winter", text: "Winter is the best season of the year." },
        { id: "stmt-spiders", text: "Spiders have eight legs." },
        { id: "stmt-netball", text: "Everyone should play netball." },
      ],
      zones: [
        { id: "zone-fact", label: "Fact" },
        { id: "zone-opinion", label: "Opinion" },
      ],
    },
    answerKey: {
      kind: "drag_drop",
      placements: {
        "stmt-canberra": "zone-fact",
        "stmt-spiders": "zone-fact",
        "stmt-winter": "zone-opinion",
        "stmt-netball": "zone-opinion",
      },
    },
    explanation:
      "Canberra being the capital and spiders having eight legs can both be checked, so they are facts. Calling winter 'the best season' and saying everyone 'should' play netball are personal judgements, so they are opinions.",
    metadata: {
      subject: "reading",
      strand: "Fact and opinion",
      topic: "Sorting facts and opinions",
      skill: "Classifying statements as fact or opinion",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 120,
      tags: ["fact-opinion", "sorting"],
    },
  },
]);
