import { validateQuestionBank } from "@/features/exam-engine/validation";

export const sampleQuestions = validateQuestionBank([
  {
    id: "g3-naplan-bean-beds",
    type: "multiple_choice",
    yearLevel: 3,
    examStyle: "naplan_style",
    status: "published",
    prompt: "Which garden bed grew 8 bean plants?",
    instructions: "Use the bar chart, then choose one answer.",
    options: [
      { id: "north", text: "North" },
      { id: "east", text: "East" },
      { id: "south", text: "South" },
      { id: "west", text: "West" },
    ],
    visuals: [
      {
        id: "bean-plants-by-garden-bed",
        type: "bar_chart",
        title: "Bean plants by garden bed",
        altText:
          "Bar chart showing North with 5 plants, East with 8, South with 6 and West with 3.",
        caption: "Bean plants counted after four weeks.",
        data: {
          labels: ["North", "East", "South", "West"],
          values: [5, 8, 6, 3],
          xAxisLabel: "Garden bed",
          yAxisLabel: "Number of bean plants",
          maxValue: 10,
          colour: "#4B2E83",
        },
      },
    ],
    answerKey: { kind: "single_option", optionId: "east" },
    explanation: "The East bar reaches 8, so East is the correct garden bed.",
    metadata: {
      subject: "numeracy",
      strand: "Statistics",
      topic: "Reading a bar chart",
      difficulty: "easy",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["bar-chart", "data"],
      locale: "en-AU",
      source: "original",
      schemaVersion: 1,
    },
  },
  {
    id: "g3-icas-library-trolley",
    type: "number_entry",
    yearLevel: 3,
    examStyle: "icas_style",
    status: "published",
    prompt:
      "A library trolley has 4 shelves with 7 books on each shelf. Nine books are borrowed. How many books remain?",
    instructions: "Enter a number.",
    options: [],
    visuals: [],
    answerKey: { kind: "number", value: 19, tolerance: 0 },
    explanation:
      "There are 4 × 7 = 28 books at first. After 9 are borrowed, 28 − 9 = 19 books remain.",
    metadata: {
      subject: "numeracy",
      strand: "Number",
      topic: "Two-step operations",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 90,
      tags: ["multiplication", "subtraction"],
      locale: "en-AU",
      source: "original",
      schemaVersion: 1,
    },
  },
  {
    id: "g5-naplan-juice-cups",
    type: "multiple_choice",
    yearLevel: 5,
    examStyle: "naplan_style",
    status: "published",
    prompt:
      "A 1.5-litre jug of juice is poured into 250-millilitre cups. How many full cups can be filled?",
    instructions: "Choose one answer.",
    options: [
      { id: "four", text: "4 cups" },
      { id: "five", text: "5 cups" },
      { id: "six", text: "6 cups" },
      { id: "eight", text: "8 cups" },
    ],
    visuals: [],
    answerKey: { kind: "single_option", optionId: "six" },
    explanation:
      "1.5 litres is 1500 millilitres. Dividing 1500 by 250 gives 6 full cups.",
    metadata: {
      subject: "numeracy",
      strand: "Measurement",
      topic: "Metric capacity",
      difficulty: "medium",
      marks: 1,
      estimatedTimeSeconds: 75,
      tags: ["capacity", "division"],
      locale: "en-AU",
      source: "original",
      schemaVersion: 1,
    },
  },
]);
