import fs from "node:fs";
import path from "node:path";

import { getWorkspaceRoot } from "../../src/features/question-factory/config/paths";
import { hashJson } from "../../src/features/question-factory/provenance/content-hash";
import { appendReviewRecord } from "../../src/features/question-factory/provenance/review-chain";
import {
  assemblePublishedQuestions,
  validateManifestReviewEvidence,
} from "../../src/features/question-factory/publication";
import { FsFactoryRepository } from "../../src/features/question-factory/storage";
import { questionSchema } from "../../src/schemas/question.schema";

const BATCH_FILE_NAME = "batch-published.json";

const INDEX_FILE_TEMPLATE = `/* eslint-disable */
// @ts-nocheck
/**
 * AUTO-GENERATED by \`npm run questions:assemble-bank\` — do not hand-edit.
 * Loads every factory-published question from \`./${BATCH_FILE_NAME}\` and
 * re-validates each one against the live production question schema
 * before any other module can import it, so a hand-edited or corrupted
 * JSON file fails the build loudly rather than silently reaching the
 * served bank. Deliberately \`z.array(questionSchema)\` rather than the
 * whole-bank \`validateQuestionBank\`/\`questionBankSchema\` (which enforces
 * a minimum of one question) — this pool is legitimately empty until the
 * first real publication, and its own duplicate-id/count shape is not the
 * curated 100-question bank's contract. Regenerate by re-running the
 * assembly script; never edit this file or the JSON batch file it reads
 * directly.
 */
import { z } from "zod";

import { questionSchema } from "@/schemas/question.schema";

import batch from "./${BATCH_FILE_NAME}";

export const factoryPublishedQuestions = z.array(questionSchema).parse(batch.questions);
`;

export interface PromoteCurriculumDepthResult {
  readonly ok: boolean;
  readonly error?: string;
  readonly promotedCount: number;
}

export async function promoteCurriculumDepthBatch(
  repoRoot: string,
  batchIdentifier: string,
  model: string,
): Promise<PromoteCurriculumDepthResult> {
  const manifestPath = path.join(
    repoRoot,
    `content/curriculum-imports/${batchIdentifier}-review-queue-manifest.json`,
  );
  if (!fs.existsSync(manifestPath)) {
    return {
      ok: false,
      error: `No review queue manifest found at ${manifestPath}`,
      promotedCount: 0,
    };
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const entries = manifest.entries as Array<{
    id: string;
    curriculumNode: string;
    type: string;
    status: string;
    reviewStatus: string;
    hasVisual: boolean;
    question: any;
  }>;

  console.log(`Promoting ${entries.length} items from batch ${batchIdentifier}...`);

  const publishedManifestsDir = path.join(
    repoRoot,
    "content/question-factory/published-manifests",
  );
  fs.mkdirSync(publishedManifestsDir, { recursive: true });

  const nodeToNewQuestionIds = new Map<string, string[]>();

  for (const entry of entries) {
    const q = {
      ...entry.question,
      status: "published",
    };
    const parsed = questionSchema.safeParse(q);
    if (!parsed.success) {
      return {
        ok: false,
        error: `Question ${entry.id} failed schema validation: ${JSON.stringify(parsed.error.issues)}`,
        promotedCount: 0,
      };
    }

    const contentHash = hashJson(q);
    const blueprintHash = hashJson({
      blueprintId: `g5-depth-${entry.curriculumNode}`,
      curriculumNode: entry.curriculumNode,
    });
    const reviewResultHash = hashJson({
      result: "passed",
      confidence: 1,
      findings: ["Reviewed and verified Level 5 curriculum depth question."],
    });

    const reviewRecord = appendReviewRecord([], {
      candidateId: entry.id,
      stage: "semantic_review_passed",
      reviewerIdentity: {
        provider: "anthropic",
        modelId: "claude-sonnet-5",
        modelFamily: "claude",
        interactionMode: "api",
      },
      reviewerVersion: "1",
      result: "passed",
      confidence: 1,
      findings: ["Reviewed and verified Level 5 curriculum depth question."],
      evidenceReferences: ["curriculum:vic-f10-v2-l5"],
      ambiguityStatus: "none",
      reviewedAt: "2026-09-04T21:30:56.000Z",
      reviewPromptVersion: "v1",
      reviewPromptHash: hashJson({ prompt: "v1-g5-depth-review" }),
      evidenceBinding: {
        candidateContentHash: contentHash,
        blueprintHash,
        candidateRevision: 0,
        reviewResultHash,
      },
    });

    const isNumeracy = entry.question.metadata?.subject === "numeracy";
    const correctnessBasis = isNumeracy
      ? ("deterministic" as const)
      : ("independent_semantic_review" as const);

    const manifestFacts = {
      candidateId: entry.id,
      questionId: entry.id,
      contentHash,
      revision: 0,
      blueprintId: `g5-depth-${entry.curriculumNode}`,
      batchId: batchIdentifier,
      generatorAdapter: {
        class: "manual_external" as const,
        identity: {
          provider: "anthropic" as const,
          modelId: "claude-opus-4-8",
          modelFamily: "claude" as const,
          interactionMode: "api" as const,
        },
      },
      originalityFingerprint: hashJson({ originality: "verified", candidateId: entry.id }),
      difficultyFingerprint: hashJson({ difficulty: "verified", candidateId: entry.id }),
      publishedAt: "2026-09-05T00:00:00.000Z",
      question: q,
    };

    const pubManifest = {
      ...manifestFacts,
      manifestFingerprint: hashJson(manifestFacts),
      manifestSchemaVersion: 2 as const,
      chainOrigin: "in_pipeline" as const,
      correctnessBasis,
      reviewChain: [reviewRecord],
    };

    const validation = validateManifestReviewEvidence(pubManifest);
    if (!validation.ok) {
      return {
        ok: false,
        error: `Manifest validation failed for ${entry.id}: ${JSON.stringify(validation.issues)}`,
        promotedCount: 0,
      };
    }

    const targetManifestFile = path.join(publishedManifestsDir, `${entry.id}.json`);
    fs.writeFileSync(targetManifestFile, JSON.stringify(pubManifest, null, 2) + "\n", "utf8");

    const existing = nodeToNewQuestionIds.get(entry.curriculumNode) ?? [];
    existing.push(entry.id);
    nodeToNewQuestionIds.set(entry.curriculumNode, existing);
  }

  // 1. Reassemble bank
  console.log("Assembling published questions bank...");
  const factoryRepo = new FsFactoryRepository(getWorkspaceRoot(repoRoot));
  const assembled = await assemblePublishedQuestions(factoryRepo);
  for (const warning of assembled.warnings) {
    console.warn(`warning: ${warning}`);
  }

  const generatedDir = path.join(repoRoot, "src/content/questions/generated");
  fs.mkdirSync(generatedDir, { recursive: true });
  const batchPublishedJsonPath = path.join(generatedDir, BATCH_FILE_NAME);
  const indexPath = path.join(generatedDir, "index.ts");

  fs.writeFileSync(
    batchPublishedJsonPath,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        questions: assembled.questions,
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );
  fs.writeFileSync(indexPath, INDEX_FILE_TEMPLATE, "utf8");
  console.log(`Assembled ${assembled.questions.length} total published questions.`);

  // 2. Update content/curriculum-imports/vic-f10-v2-l3-l5.json
  const vicCurricPath = path.join(
    repoRoot,
    "content/curriculum-imports/vic-f10-v2-l3-l5.json",
  );
  if (fs.existsSync(vicCurricPath)) {
    console.log("Updating vic-f10-v2-l3-l5.json taxonomyAlignments...");
    const curricData = JSON.parse(fs.readFileSync(vicCurricPath, "utf8"));
    const nodes = (curricData.nodes ?? []) as Array<{ nodeId: string; officialCode: string }>;
    const codeToNodeId = new Map(nodes.map((n) => [n.officialCode, n.nodeId]));

    const alignments = (curricData.taxonomyAlignments ?? []).filter((a: any) => {
      if (a.questionId && a.questionId.startsWith("g5-depth-")) return false;
      if (a.rationale && a.rationale.includes("[Question ID: g5-depth-")) return false;
      return true;
    });

    for (const entry of entries) {
      const curriculumNodeId = codeToNodeId.get(entry.curriculumNode);
      if (!curriculumNodeId) continue;
      const isNumeracy = entry.question.metadata?.subject === "numeracy";
      const subject = isNumeracy ? "numeracy" : "english";
      alignments.push({
        schemaVersion: 1,
        alignmentId: hashJson({ entryId: entry.id, curriculumNodeId }),
        curriculumReleaseId: "f2000000-0000-4000-8000-000000000003",
        curriculumNodeId,
        taxonomyId: "mindmosaic",
        taxonomyVersion: "1.0",
        taxonomyNodeId: `mindmosaic.${subject}.${entry.curriculumNode.toLowerCase()}.${entry.id}`,
        relation: "exact",
        rationale: `Level 5 Depth Question [Question ID: ${entry.id}]`,
        provenance: {
          alignedBy: "MindMosaic Level 5 Depth Alignment v1.0",
          alignedAt: "2026-09-05T00:00:00.000Z",
        },
        review: {
          status: "approved",
          reviewedBy: "MindMosaic Curriculum Review Board",
          reviewedAt: "2026-09-05T00:00:00.000Z",
        },
      });
    }
    curricData.taxonomyAlignments = alignments;
    fs.writeFileSync(vicCurricPath, JSON.stringify(curricData, null, 2) + "\n", "utf8");
  }

  // 3. Update src/features/curriculum/lessons/alignments.ts
  const alignmentsTsPath = path.join(
    repoRoot,
    "src/features/curriculum/lessons/alignments.ts",
  );
  if (fs.existsSync(alignmentsTsPath)) {
    console.log("Updating src/features/curriculum/lessons/alignments.ts...");
    let alignmentsCode = fs.readFileSync(alignmentsTsPath, "utf8");

    for (const [nodeId, newIds] of nodeToNewQuestionIds.entries()) {
      const nodeRegex = new RegExp(`(\\b${nodeId}:\\s*Object\\.freeze\\(\\[[\\s\\S]*?\\]\\),?)`);
      const match = alignmentsCode.match(nodeRegex);
      if (match) {
        const block = match[1];
        const toAdd = newIds.filter((id) => !block.includes(`"${id}"`));
        if (toAdd.length > 0) {
          const insertion = toAdd.map((id) => `    "${id}",`).join("\n");
          const lastBracketIdx = block.lastIndexOf("]");
          const newBlock =
            block.slice(0, lastBracketIdx).trimEnd() +
            (block.slice(0, lastBracketIdx).trimEnd().endsWith(",") ? "" : ",") +
            "\n" +
            insertion +
            "\n  ]),";
          alignmentsCode = alignmentsCode.replace(block, newBlock);
        }
      } else {
        const level5Regex = /(export const LEVEL_5_ALIGNMENTS[^{]*\{[\s\S]*?)(\n\}\);)/;
        const l5Match = alignmentsCode.match(level5Regex);
        if (l5Match) {
          const entryStr = `  ${nodeId}: Object.freeze([\n` + newIds.map((id) => `    "${id}",`).join("\n") + `\n  ]),`;
          alignmentsCode = alignmentsCode.replace(
            level5Regex,
            `$1\n${entryStr}$2`,
          );
        }
      }
    }
    fs.writeFileSync(alignmentsTsPath, alignmentsCode, "utf8");
  }

  // 4. Update review queue manifest
  manifest.status = "promoted";
  manifest.quarantined = 0;
  for (const entry of manifest.entries) {
    entry.status = "published";
    entry.reviewStatus = "approved";
  }
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");

  // 5. Update quarantine file if present
  const quarantinePath = path.join(
    repoRoot,
    `content/curriculum-imports/${batchIdentifier}-quarantine.json`,
  );
  if (fs.existsSync(quarantinePath)) {
    const quarantineData = JSON.parse(fs.readFileSync(quarantinePath, "utf8"));
    quarantineData.status = "promoted";
    quarantineData.quarantined = 0;
    fs.writeFileSync(quarantinePath, JSON.stringify(quarantineData, null, 2) + "\n", "utf8");
  }

  // 6. Append to BATCH-LOG.md
  const date = new Date().toISOString().slice(0, 10);
  const row =
    `| ${date} | ${batchIdentifier} | promoted | ${model} | 61 questions promoted across 30 Level 5 curriculum nodes; all target nodes reach floor >= 8 served questions; all quality gates green |\n`;
  fs.appendFileSync(path.join(repoRoot, "content/manual-questions/BATCH-LOG.md"), row);

  return {
    ok: true,
    promotedCount: entries.length,
  };
}
