"use client";

import { useMemo, useState } from "react";
import { Archive } from "lucide-react";

import { Badge, Card, ConfirmDialog, EmptyState, ProgressBar } from "@/components/ui";
import { describeConfig } from "@/features/exam-engine/components/describe-config";

import {
  archiveAssignment,
  categorizeAssignment,
  type AssignmentLifecycleStatus,
} from "../assignment-lifecycle";
import { assignmentCompletionPercentage } from "../analytics";
import { assignmentConfigSchema } from "../assignment-contract";
import type { AssignmentWithProgress } from "../data";
import { formatShortDate } from "../format";
import { Tabs } from "./Tabs";

const STATUS_PRESENTATION = {
  assigned: { label: "Not started", variant: "neutral" as const },
  in_progress: { label: "In progress", variant: "purple" as const },
  submitted: { label: "Completed", variant: "success" as const },
};

const LIFECYCLE_TABS: { key: AssignmentLifecycleStatus; label: string }[] = [
  { key: "active", label: "Active" },
  { key: "upcoming", label: "Upcoming" },
  { key: "completed", label: "Completed" },
];

function AssignmentCard({
  assignment,
  nameFor,
  onArchive,
}: {
  assignment: AssignmentWithProgress;
  nameFor: Map<string, string>;
  onArchive: (assignmentId: string) => void;
}) {
  const config = assignmentConfigSchema.safeParse(assignment.config);
  const completion = assignmentCompletionPercentage(
    assignment.students.map((student) => student.status),
  );
  const submitted = assignment.students.filter(
    (student) => student.status === "submitted",
  ).length;
  const [confirmingArchive, setConfirmingArchive] = useState(false);
  const [isArchiving, setIsArchiving] = useState(false);

  async function confirmArchive() {
    setIsArchiving(true);
    try {
      await archiveAssignment(assignment.id);
      onArchive(assignment.id);
    } finally {
      setIsArchiving(false);
      setConfirmingArchive(false);
    }
  }

  return (
    <Card className="p-5">
      <div className="flex flex-wrap items-center gap-4">
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <h3 className="text-sm font-extrabold text-ink">
              {config.success ? config.data.title : "Assignment"}
            </h3>
            {config.success && config.data.autoGenerated && (
              <Badge variant="orange">Auto-generated</Badge>
            )}
            {completion >= 100 && <Badge variant="success">Completed</Badge>}
          </div>
          <p className="mt-1 text-xs text-muted">
            {config.success ? describeConfig(config.data) : "Unknown configuration"} · Due{" "}
            {formatShortDate(assignment.dueAt)} · Created{" "}
            {formatShortDate(assignment.createdAt)}
          </p>
        </div>
        <div className="w-40 shrink-0">
          <ProgressBar
            label={`${submitted}/${assignment.students.length} submitted`}
            value={completion}
            tone={completion >= 100 ? "success" : "purple"}
          />
        </div>
        <button
          type="button"
          onClick={() => setConfirmingArchive(true)}
          className="inline-flex items-center gap-1.5 rounded-xl border border-royal/15 px-3 py-2 text-xs font-bold text-muted transition hover:border-error/30 hover:text-error"
        >
          <Archive aria-hidden="true" className="h-3.5 w-3.5" />
          Archive
        </button>
      </div>

      <details className="group mt-4">
        <summary className="cursor-pointer select-none text-sm font-bold text-royal transition hover:underline">
          Student progress ({assignment.students.length})
        </summary>
        <ul className="mt-3 divide-y divide-royal/5 rounded-2xl border border-royal/10">
          {assignment.students.map((student) => {
            const presentation = STATUS_PRESENTATION[student.status];
            return (
              <li
                key={student.studentId}
                className="flex items-center justify-between gap-3 px-4 py-2.5 text-sm"
              >
                <span className="font-semibold text-ink">
                  {nameFor.get(student.studentId) ?? "Student no longer in class"}
                </span>
                <Badge variant={presentation.variant}>{presentation.label}</Badge>
              </li>
            );
          })}
        </ul>
      </details>

      <ConfirmDialog
        open={confirmingArchive}
        title="Archive this assignment?"
        description="It will be hidden from your active tracking views. Student attempts already submitted are not affected."
        variant="danger"
        confirmLabel="Archive"
        isLoading={isArchiving}
        onConfirm={confirmArchive}
        onCancel={() => setConfirmingArchive(false)}
      />
    </Card>
  );
}

/** Active/Upcoming/Completed board with a mocked, session-scoped archive action. */
export function AssignmentsBoard({
  assignments,
  nameFor,
}: {
  assignments: AssignmentWithProgress[];
  nameFor: Map<string, string>;
}) {
  const [archivedIds, setArchivedIds] = useState<Set<string>>(new Set());
  const [tab, setTab] = useState<AssignmentLifecycleStatus>("active");

  const visible = assignments.filter((assignment) => !archivedIds.has(assignment.id));
  const grouped = useMemo(() => {
    const groups: Record<AssignmentLifecycleStatus, AssignmentWithProgress[]> = {
      active: [],
      upcoming: [],
      completed: [],
    };
    for (const assignment of visible) {
      groups[categorizeAssignment(assignment)].push(assignment);
    }
    return groups;
  }, [visible]);

  function handleArchive(assignmentId: string) {
    setArchivedIds((current) => new Set(current).add(assignmentId));
  }

  const current = grouped[tab];

  return (
    <div className="space-y-4">
      <Tabs
        label="Assignment status"
        tabs={LIFECYCLE_TABS.map((item) => ({
          ...item,
          label: `${item.label} (${grouped[item.key].length})`,
        }))}
        active={tab}
        onChange={setTab}
      />
      {current.length === 0 ? (
        <EmptyState
          title={`No ${tab} assignments`}
          description={
            tab === "completed"
              ? "Assignments appear here once every student has submitted."
              : tab === "upcoming"
                ? "Assignments due in the future with nobody started yet appear here."
                : "Everything currently in progress appears here."
          }
        />
      ) : (
        <div className="space-y-3">
          {current.map((assignment) => (
            <AssignmentCard
              key={assignment.id}
              assignment={assignment}
              nameFor={nameFor}
              onArchive={handleArchive}
            />
          ))}
        </div>
      )}
    </div>
  );
}
