"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, ChevronLeft, ChevronRight, Sparkles } from "lucide-react";

import { Badge, Button, Input, Select, Textarea } from "@/components/ui";
import {
  STYLE_LABELS,
  SUBJECT_LABELS,
  YEAR_LABELS,
} from "@/features/exam-engine/components/describe-config";
import {
  EXAM_STYLE_OPTIONS,
  QUESTION_COUNT_OPTIONS,
  SUBJECT_OPTIONS,
  YEAR_LEVEL_OPTIONS,
} from "@/features/exam-engine/selection";
import type {
  ExamStyleFilter,
  QuestionCountOption,
  SubjectFilter,
  TimingMode,
  YearLevelFilter,
} from "@/features/exam-engine/selection";

import type {
  AssignmentContentMode,
  AssignmentDifficulty,
  AssignmentTargetMode,
} from "../assignment-contract";
import { isKnownYearLevel } from "@/features/taxonomy/year-registry";

import type { RosterStudent, TeacherClass } from "../data";
import {
  ASSIGNMENT_DIFFICULTY_OPTIONS,
  DIFFICULTY_LABELS,
  type AssignmentBlueprint,
  type AssignmentSkill,
} from "../mock-catalogue";

type WizardStep = "target" | "content" | "review";

const STEPS: { key: WizardStep; label: string }[] = [
  { key: "target", label: "Target" },
  { key: "content", label: "Content & schedule" },
  { key: "review", label: "Review & publish" },
];

/**
 * Assignment creation wizard (individual/group/class targeting, a
 * skill-based or blueprint-based mock exam, difficulty, due date,
 * instructions, and a review step before publishing). Posts to
 * /api/teacher/assignments; the server re-validates everything and RLS
 * re-checks class ownership independently of anything chosen here.
 */
export function AssignmentCreateForm({
  activeClass,
  roster,
  skills,
  blueprints,
  initialSelectedIds = [],
}: {
  activeClass: TeacherClass;
  roster: RosterStudent[];
  skills: AssignmentSkill[];
  blueprints: AssignmentBlueprint[];
  initialSelectedIds?: string[];
}) {
  const router = useRouter();
  const [step, setStep] = useState<WizardStep>("target");

  const [targetMode, setTargetMode] = useState<AssignmentTargetMode>(
    initialSelectedIds.length === 1
      ? "individual"
      : initialSelectedIds.length > 1
        ? "group"
        : "class",
  );
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set(initialSelectedIds));

  const [title, setTitle] = useState("");
  const [yearLevel, setYearLevel] = useState<YearLevelFilter>(
    /* Any registry year, not just 3 or 5 (expansion-plan T0a). A class
       recorded at a year the schema does not know still falls back to
       "mixed" rather than pinning a value selection would reject. */
    isKnownYearLevel(activeClass.yearLevel) ? activeClass.yearLevel : "mixed",
  );
  const [examStyle, setExamStyle] = useState<ExamStyleFilter>("naplan_style");
  const [subject, setSubject] = useState<SubjectFilter>("numeracy");
  const [questionCount, setQuestionCount] = useState<QuestionCountOption>(10);
  const [timing, setTiming] = useState<TimingMode>("untimed");
  const [dueDate, setDueDate] = useState("");
  const [instructions, setInstructions] = useState("");
  const [contentMode, setContentMode] = useState<AssignmentContentMode>("practice_set");
  const [difficulty, setDifficulty] = useState<AssignmentDifficulty>("standard");
  const [skillIds, setSkillIds] = useState<Set<string>>(new Set());
  const [blueprintId, setBlueprintId] = useState<string | null>(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const recipients =
    targetMode === "class" ? roster.map((student) => student.studentId) : [...selectedIds];

  const visibleSkills = skills.filter(
    (skill) => subject === "mixed" || skill.subject === subject,
  );
  const visibleBlueprints = blueprints.filter(
    (blueprint) =>
      subject === "mixed" || blueprint.subject === subject || blueprint.subject === "mixed",
  );

  function toggleStudent(studentId: string) {
    setSelectedIds((current) => {
      const next = new Set(current);
      if (targetMode === "individual") {
        return next.has(studentId) ? new Set() : new Set([studentId]);
      }
      if (next.has(studentId)) next.delete(studentId);
      else next.add(studentId);
      return next;
    });
  }

  function toggleSkill(skillId: string) {
    setSkillIds((current) => {
      const next = new Set(current);
      if (next.has(skillId)) next.delete(skillId);
      else next.add(skillId);
      return next;
    });
  }

  function targetStepError(): string | null {
    if (targetMode !== "class" && recipients.length === 0) {
      return targetMode === "individual"
        ? "Select a student for this assignment."
        : "Select at least one student.";
    }
    return null;
  }

  function contentStepError(): string | null {
    if (title.trim().length === 0) {
      return "Give the assignment a name students will recognise.";
    }
    return null;
  }

  function goNext() {
    const stepError = step === "target" ? targetStepError() : contentStepError();
    if (stepError) {
      setError(stepError);
      return;
    }
    setError(null);
    setStep((current) => STEPS[STEPS.findIndex((item) => item.key === current) + 1].key);
  }

  function goBack() {
    setError(null);
    setStep((current) => STEPS[STEPS.findIndex((item) => item.key === current) - 1].key);
  }

  async function publish() {
    setError(null);
    const targetError = targetStepError();
    const contentError = contentStepError();
    if (targetError || contentError) {
      setError(targetError ?? contentError);
      setStep(targetError ? "target" : "content");
      return;
    }

    setIsSubmitting(true);
    try {
      const response = await fetch("/api/teacher/assignments", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          classId: activeClass.id,
          config: {
            yearLevel,
            examStyle,
            subject,
            questionCount,
            timing,
            bankId: "curated",
            title: title.trim(),
            targetMode,
            contentMode: autoGenerated ? "skill_based" : contentMode,
            difficulty,
            skillIds: autoGenerated ? [] : [...skillIds],
            blueprintId: contentMode === "blueprint_based" && !autoGenerated ? blueprintId : null,
            instructions: instructions.trim(),
            autoGenerated,
          },
          dueAt: dueDate ? new Date(`${dueDate}T23:59:59`).toISOString() : null,
          studentIds: recipients,
        }),
      });
      if (!response.ok) {
        const body = (await response.json().catch(() => null)) as {
          error?: string;
        } | null;
        setError(
          body?.error === "students_not_in_class"
            ? "One of the selected students is no longer in this class. Refresh and try again."
            : "The assignment could not be created. Please try again.",
        );
        return;
      }
      router.push(`/teacher/assignments?class=${activeClass.id}`);
      router.refresh();
    } catch {
      setError("The assignment could not be created. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  }

  const recipientNames = roster
    .filter((student) => recipients.includes(student.studentId))
    .map((student) => student.displayName ?? "Unnamed student");

  return (
    <div className="space-y-6">
      {/*
        Connected step-dot indicator (15-assignment-engine.html's wizard step
        bar): a numbered circle per step, filled + checkmarked once passed,
        joined by a line that fills in as steps complete. Replaces the
        previous flat row of same-weight pill badges, which gave no sense of
        a linear step 1-of-3 progression. State is still conveyed by shape
        (number vs. checkmark) and the `aria-current`/`aria-label` text below,
        not by fill colour alone.
      */}
      <ol aria-label="Wizard steps" className="flex items-start">
        {STEPS.map((item, index) => {
          const currentIndex = STEPS.findIndex((s) => s.key === step);
          const isDone = index < currentIndex;
          const isActive = item.key === step;
          return (
            <li
              key={item.key}
              className={`flex items-center ${index < STEPS.length - 1 ? "flex-1" : ""}`}
            >
              <div className="flex flex-col items-center">
                <span
                  aria-current={isActive ? "step" : undefined}
                  aria-label={`Step ${index + 1}: ${item.label}${isDone ? ", completed" : isActive ? ", current" : ""}`}
                  className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border-2 text-xs font-extrabold transition-colors ${
                    isDone
                      ? "border-success bg-success text-white"
                      : isActive
                        ? "border-royal bg-royal text-white"
                        : "border-royal/20 bg-white text-muted"
                  }`}
                >
                  {isDone ? <Check aria-hidden="true" className="h-4 w-4" /> : index + 1}
                </span>
                <span
                  className={`mt-1.5 text-center text-[11px] font-bold ${
                    isActive ? "text-royal" : isDone ? "text-success" : "text-muted"
                  }`}
                >
                  {item.label}
                </span>
              </div>
              {index < STEPS.length - 1 && (
                <span
                  aria-hidden="true"
                  className={`mx-2 h-0.5 flex-1 self-start mt-4 rounded-full ${
                    isDone ? "bg-success" : "bg-royal/15"
                  }`}
                />
              )}
            </li>
          );
        })}
      </ol>

      {step === "target" && (
        <fieldset className="space-y-3">
          <legend className="text-sm font-extrabold uppercase tracking-[0.06em] text-muted">
            Who is this for?
          </legend>
          <div className="space-y-2">
            {(
              [
                { mode: "class" as const, label: `Entire class (${roster.length} students)` },
                { mode: "group" as const, label: "Group of students" },
                { mode: "individual" as const, label: "One student" },
              ]
            ).map((option) => (
              <label
                key={option.mode}
                className="flex cursor-pointer items-center gap-3 rounded-xl border border-royal/15 bg-white px-4 py-3"
              >
                <input
                  type="radio"
                  name="target-mode"
                  className="h-4 w-4 accent-royal"
                  checked={targetMode === option.mode}
                  onChange={() => {
                    setTargetMode(option.mode);
                    if (option.mode === "class") setSelectedIds(new Set());
                  }}
                />
                <span className="text-sm font-bold text-ink">{option.label}</span>
              </label>
            ))}
          </div>
          {targetMode !== "class" && (
            <ul className="grid gap-2 rounded-2xl border border-royal/10 bg-white p-4 sm:grid-cols-2">
              {roster.map((student) => (
                <li key={student.studentId}>
                  <label className="flex cursor-pointer items-center gap-2.5 text-sm text-ink">
                    <input
                      type={targetMode === "individual" ? "radio" : "checkbox"}
                      name={targetMode === "individual" ? "individual-target" : undefined}
                      className="h-4 w-4 accent-royal"
                      checked={selectedIds.has(student.studentId)}
                      onChange={() => toggleStudent(student.studentId)}
                    />
                    {student.displayName ?? "Unnamed student"}
                  </label>
                </li>
              ))}
            </ul>
          )}
        </fieldset>
      )}

      {step === "content" && (
        <div className="space-y-8">
          <section aria-labelledby="assignment-basics" className="space-y-4">
            <h2
              id="assignment-basics"
              className="text-sm font-extrabold uppercase tracking-[0.06em] text-muted"
            >
              Assignment
            </h2>
            <Input
              label="Name"
              value={title}
              onChange={(event) => setTitle(event.target.value)}
              placeholder="e.g. Fractions focus week"
              maxLength={120}
              required
            />
            <Input
              label="Due date"
              type="date"
              value={dueDate}
              onChange={(event) => setDueDate(event.target.value)}
              hint="Optional — leave empty for no due date."
            />
            <Textarea
              label="Instructions"
              value={instructions}
              onChange={(event) => setInstructions(event.target.value)}
              placeholder="Optional notes shown to students before they start."
              maxLength={2000}
            />
          </section>

          <section aria-labelledby="assignment-config" className="space-y-4">
            <h2
              id="assignment-config"
              className="text-sm font-extrabold uppercase tracking-[0.06em] text-muted"
            >
              Practice set
            </h2>
            <div className="grid gap-4 sm:grid-cols-2">
              <Select
                label="Year level"
                value={String(yearLevel)}
                onChange={(event) =>
                  setYearLevel(
                    event.target.value === "mixed"
                      ? "mixed"
                      : (Number(event.target.value) as 3 | 5),
                  )
                }
              >
                {YEAR_LEVEL_OPTIONS.map((option) => (
                  <option key={String(option)} value={String(option)}>
                    {YEAR_LABELS[String(option)]}
                  </option>
                ))}
              </Select>
              <Select
                label="Style"
                value={examStyle}
                onChange={(event) => setExamStyle(event.target.value as ExamStyleFilter)}
              >
                {EXAM_STYLE_OPTIONS.map((option) => (
                  <option key={option} value={option}>
                    {STYLE_LABELS[option]}
                  </option>
                ))}
              </Select>
              <Select
                label="Subject"
                value={subject}
                onChange={(event) => setSubject(event.target.value as SubjectFilter)}
              >
                {SUBJECT_OPTIONS.map((option) => (
                  <option key={option} value={option}>
                    {SUBJECT_LABELS[option]}
                  </option>
                ))}
              </Select>
              <Select
                label="Questions"
                value={String(questionCount)}
                onChange={(event) =>
                  setQuestionCount(
                    event.target.value === "full"
                      ? "full"
                      : (Number(event.target.value) as 10 | 20 | 30),
                  )
                }
              >
                {QUESTION_COUNT_OPTIONS.map((option) => (
                  <option key={String(option)} value={String(option)}>
                    {option === "full" ? "Full set" : `${option} questions`}
                  </option>
                ))}
              </Select>
              <Select
                label="Timing"
                value={timing}
                onChange={(event) => setTiming(event.target.value as TimingMode)}
              >
                <option value="untimed">Untimed</option>
                <option value="timed">Timed</option>
              </Select>
              <Select
                label="Difficulty"
                value={difficulty}
                onChange={(event) =>
                  setDifficulty(event.target.value as AssignmentDifficulty)
                }
              >
                {ASSIGNMENT_DIFFICULTY_OPTIONS.map((option) => (
                  <option key={option} value={option}>
                    {DIFFICULTY_LABELS[option]}
                  </option>
                ))}
              </Select>
            </div>
          </section>

          <section aria-labelledby="assignment-content-mode" className="space-y-4">
            <h2
              id="assignment-content-mode"
              className="text-sm font-extrabold uppercase tracking-[0.06em] text-muted"
            >
              How should questions be chosen?
            </h2>
            <label className="flex cursor-pointer items-start gap-3 rounded-xl border border-royal-orange/25 bg-royal-orange/5 px-4 py-3">
              <input
                type="checkbox"
                className="mt-0.5 h-4 w-4 accent-royal"
                checked={autoGenerated}
                onChange={(event) => setAutoGenerated(event.target.checked)}
              />
              <span>
                <span className="flex items-center gap-1.5 text-sm font-bold text-ink">
                  <Sparkles aria-hidden="true" className="h-4 w-4 text-royal-orange" />
                  Auto-generate this assignment
                </span>
                <span className="mt-0.5 block text-xs text-muted">
                  Skills are chosen automatically based on each student&apos;s recent
                  performance gaps, instead of you picking them below.
                </span>
              </span>
            </label>

            {!autoGenerated && (
              <>
                <div className="flex flex-wrap gap-2">
                  {(
                    [
                      { mode: "practice_set" as const, label: "Practice set" },
                      { mode: "skill_based" as const, label: "Skill-based" },
                      { mode: "blueprint_based" as const, label: "Blueprint mock exam" },
                    ]
                  ).map((option) => (
                    <button
                      key={option.mode}
                      type="button"
                      onClick={() => setContentMode(option.mode)}
                      aria-pressed={contentMode === option.mode}
                      className={
                        contentMode === option.mode
                          ? "rounded-xl bg-royal px-3.5 py-2 text-sm font-bold text-white"
                          : "rounded-xl border border-royal/15 bg-white px-3.5 py-2 text-sm font-bold text-royal"
                      }
                    >
                      {option.label}
                    </button>
                  ))}
                </div>

                {contentMode === "skill_based" && (
                  <ul className="grid gap-2 rounded-2xl border border-royal/10 bg-white p-4 sm:grid-cols-2">
                    {visibleSkills.map((skill) => (
                      <li key={skill.id}>
                        <label className="flex cursor-pointer items-center gap-2.5 text-sm text-ink">
                          <input
                            type="checkbox"
                            className="h-4 w-4 accent-royal"
                            checked={skillIds.has(skill.id)}
                            onChange={() => toggleSkill(skill.id)}
                          />
                          {skill.label}
                        </label>
                      </li>
                    ))}
                  </ul>
                )}

                {contentMode === "blueprint_based" && (
                  <div className="space-y-2 rounded-2xl border border-royal/10 bg-white p-4">
                    {visibleBlueprints.map((blueprint) => (
                      <label
                        key={blueprint.id}
                        className="flex cursor-pointer items-start gap-2.5 text-sm text-ink"
                      >
                        <input
                          type="radio"
                          name="blueprint"
                          className="mt-0.5 h-4 w-4 accent-royal"
                          checked={blueprintId === blueprint.id}
                          onChange={() => setBlueprintId(blueprint.id)}
                        />
                        <span>
                          <span className="font-bold">{blueprint.label}</span>
                          <span className="block text-xs text-muted">
                            {blueprint.description}
                          </span>
                        </span>
                      </label>
                    ))}
                  </div>
                )}
              </>
            )}
          </section>
        </div>
      )}

      {step === "review" && (
        <div className="space-y-4">
          <h2 className="text-sm font-extrabold uppercase tracking-[0.06em] text-muted">
            Review before publishing
          </h2>
          <dl className="grid gap-3 rounded-2xl border border-royal/10 bg-white p-4 text-sm sm:grid-cols-2">
            <div>
              <dt className="font-semibold text-muted">Name</dt>
              <dd className="font-bold text-ink">{title || "—"}</dd>
            </div>
            <div>
              <dt className="font-semibold text-muted">Recipients</dt>
              <dd className="font-bold text-ink">
                {targetMode === "class"
                  ? `Entire class (${recipients.length})`
                  : recipientNames.join(", ") || "None selected"}
              </dd>
            </div>
            <div>
              <dt className="font-semibold text-muted">Practice set</dt>
              <dd className="font-bold text-ink">
                {YEAR_LABELS[String(yearLevel)]} · {STYLE_LABELS[examStyle]} ·{" "}
                {SUBJECT_LABELS[subject]} ·{" "}
                {questionCount === "full" ? "Full set" : `${questionCount} questions`}
              </dd>
            </div>
            <div>
              <dt className="font-semibold text-muted">Difficulty</dt>
              <dd className="font-bold text-ink">{DIFFICULTY_LABELS[difficulty]}</dd>
            </div>
            <div>
              <dt className="font-semibold text-muted">Question source</dt>
              <dd className="font-bold text-ink">
                {autoGenerated ? (
                  <Badge variant="orange">Auto-generated</Badge>
                ) : contentMode === "practice_set" ? (
                  "Standard practice set"
                ) : contentMode === "skill_based" ? (
                  `${skillIds.size} skill${skillIds.size === 1 ? "" : "s"} selected`
                ) : (
                  blueprints.find((blueprint) => blueprint.id === blueprintId)?.label ??
                  "No blueprint selected"
                )}
              </dd>
            </div>
            <div>
              <dt className="font-semibold text-muted">Due date</dt>
              <dd className="font-bold text-ink">{dueDate || "No due date"}</dd>
            </div>
            {instructions && (
              <div className="sm:col-span-2">
                <dt className="font-semibold text-muted">Instructions</dt>
                <dd className="text-ink">{instructions}</dd>
              </div>
            )}
          </dl>
        </div>
      )}

      {error && (
        <p role="alert" className="text-sm font-semibold text-error">
          {error}
        </p>
      )}

      <div className="flex items-center gap-3">
        {step !== "target" && (
          <Button type="button" variant="ghost" onClick={goBack}>
            <ChevronLeft aria-hidden="true" className="h-4 w-4" />
            Back
          </Button>
        )}
        {step !== "review" ? (
          <Button type="button" onClick={goNext}>
            Continue
            <ChevronRight aria-hidden="true" className="h-4 w-4" />
          </Button>
        ) : (
          <Button type="button" isLoading={isSubmitting} loadingLabel="Publishing" onClick={publish}>
            Publish assignment
          </Button>
        )}
        <Button
          type="button"
          variant="ghost"
          onClick={() => router.push(`/teacher/assignments?class=${activeClass.id}`)}
        >
          Cancel
        </Button>
      </div>
    </div>
  );
}
