/**
 * `questions:assemble-bank` — the production-bank assembly path's write
 * side: reads every manifest in `content/question-factory/published-manifests/`
 * (via `assemblePublishedQuestions`) and regenerates the two controlled
 * files `PUBLICATION_CONTROLLED_FILES` reserves for factory-published
 * content —
 *
 *   - `src/content/questions/generated/batch-published.json` (the raw,
 *     re-validated question data), and
 *   - `src/content/questions/generated/index.ts` (a static loader that
 *     imports that JSON and re-validates it against the live production
 *     schema via `validateQuestionBank` at module-load time, exactly the
 *     same defence-in-depth pattern `src/content/questions/practice-bank.ts`
 *     already applies to its own generated seed file).
 *
 * Both files live under `src/content/questions/generated/` alongside the
 * pre-existing, unrelated `generated-questions.ts` (the hand/generator
 * -authored practice bank) — different files, same directory, no
 * collision; this script never reads or writes that file.
 *
 * Never touches the curated 100-question bank
 * (`src/content/questions/question-bank.ts`) or any file it depends on.
 *
 * Exit codes: 0 assembled and wrote successfully (including the
 * zero-published-items case, which writes an empty array — not an
 * error), 1 internal error.
 */
import { mkdir, writeFile } from "node:fs/promises";
import * as path from "node:path";

import { GENERATED_QUESTIONS_RELATIVE_PATH, getWorkspaceRoot } from "../src/features/question-factory/config";
import { assemblePublishedQuestions } from "../src/features/question-factory/publication";
import { FsFactoryRepository } from "../src/features/question-factory/storage";

const BATCH_FILE_NAME = "batch-published.json";

const INDEX_FILE_TEMPLATE = `/* eslint-disable */
// @ts-nocheck
/**
 * AUTO-GENERATED by \`npm run questions:assemble-bank\` — do not hand-edit.
 * Loads every factory-published question from \`./${BATCH_FILE_NAME}\` and
 * re-validates each one against the live production question schema
 * before any other module can import it, so a hand-edited or corrupted
 * JSON file fails the build loudly rather than silently reaching the
 * served bank. Deliberately \`z.array(questionSchema)\` rather than the
 * whole-bank \`validateQuestionBank\`/\`questionBankSchema\` (which enforces
 * a minimum of one question) — this pool is legitimately empty until the
 * first real publication, and its own duplicate-id/count shape is not the
 * curated 100-question bank's contract. Regenerate by re-running the
 * assembly script; never edit this file or the JSON batch file it reads
 * directly.
 */
import { z } from "zod";

import { questionSchema } from "@/schemas/question.schema";

import batch from "./${BATCH_FILE_NAME}";

export const factoryPublishedQuestions = z.array(questionSchema).parse(batch.questions);
`;

async function main(): Promise<number> {
  const workspaceRoot = getWorkspaceRoot();
  const repository = new FsFactoryRepository(workspaceRoot);

  const assembled = await assemblePublishedQuestions(repository);
  for (const warning of assembled.warnings) {
    process.stderr.write(`warning: ${warning}\n`);
  }

  const generatedDir = path.join(process.cwd(), GENERATED_QUESTIONS_RELATIVE_PATH);
  await mkdir(generatedDir, { recursive: true });

  const batchPayload = { generatedAt: new Date().toISOString(), questions: assembled.questions };
  await writeFile(path.join(generatedDir, BATCH_FILE_NAME), `${JSON.stringify(batchPayload, null, 2)}\n`, "utf8");
  await writeFile(path.join(generatedDir, "index.ts"), INDEX_FILE_TEMPLATE, "utf8");

  process.stdout.write(
    `Assembled ${assembled.questions.length} factory-published question(s) into ${GENERATED_QUESTIONS_RELATIVE_PATH}.\n`,
  );
  return 0;
}

main()
  .then((code) => {
    process.exitCode = code;
  })
  .catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`internal_error: ${message}\n`);
    process.exitCode = 1;
  });
