/**
 * Curated-bank skill labels that do not yet resolve through the
 * question-factory skill taxonomy (`SKILL_TAXONOMY_ENTRIES`).
 *
 * This list was regenerated from the live bank after the 568-question
 * overnight Grade-3 ingest, and extended on 2026-08-10 when the Grade 5 ICAS
 * digital technologies and spelling batches were promoted — 46 further
 * free-text labels, none of which resolve. Curated free-text skills remain
 * recorded here until an editorial taxonomy mapping is approved.
 *
 * They are recorded rather than mapped because mapping is an editorial
 * decision, not a mechanical one. Deciding that "Soft c (c sounding like
 * s) in 'circle'" belongs under one taxonomy entry rather than another is
 * a judgement about the skill's identity, and a guessed alias would be
 * worse than an acknowledged gap: it would silently mis-attribute the
 * question's coverage and mislead blueprint planning for that entry ever
 * after.
 *
 * This list is a two-way ratchet, enforced in taxonomy.test.ts. A NEW
 * unmapped skill fails, so the debt cannot grow unnoticed; mapping one of
 * these also fails, forcing its removal here. Shrinking it to empty is the
 * goal, and at that point both the list and its assertion should go.
 */
export const UNMAPPED_CURATED_SKILL_LABELS: readonly string[] = [
  "Add 100 to a 3-digit number using place value",
  "Add 3-digit numbers with regrouping",
  "Add 3-digit numbers with two regroupings",
  "Add the prefix un- to form an opposite",
  "Add two amounts of money in cents",
  "Add two three-digit numbers involving regrouping",
  "Add two values read from a bar graph",
  "Adding '-ed' to 'smile' by dropping the silent 'e'",
  "Adding '-ing' to 'come' by dropping the silent 'e'",
  "Adding -ed to a base word with no spelling change",
  "Adding -ing to a base word with no spelling change",
  "Adding one week to a day and date",
  "Adding the -ful suffix",
  "Adding the -ly suffix",
  "Adding the prefix 'un-' to a base word (happy to unhappy)",
  "Adding the suffix '-less' to a base word",
  "Adding the suffix '-ly' to a base word (quick to quickly)",
  "Adding the suffix '-ness' to a base word",
  "Adding the suffix -er to make 'gardener'",
  "Adding three-digit numbers with two regroupings",
  "Apostrophes to show possession",
  "Apply digital technologies concepts",
  "Apply the Australian double-l rule before -ed",
  "Apply the Australian verb and noun spelling split",
  "Apply the ei-after-c pattern",
  "Applying a discovered multiplication rule",
  "Applying the -y to -ies plural rule",
  "Arranging digits to build the largest number",
  "Arranging words into a well-formed sentence",
  "Being kind and asking before sharing",
  "Being kind and polite online",
  "Build a three-digit number from hundreds, tens and ones",
  "Build meaning from the root vis and a suffix",
  "Building a three-digit number from place value clues",
  "Building a word by adding the suffix -ful",
  "Building a word with the prefix un-",
  "Building a word with the suffix -ful",
  "Calculate change from a line graph",
  "Calculate change from a purchase under $20",
  "Capital letters for months of the year",
  "Capital letters: sentence start and days of the week",
  "Capitalising proper nouns (names and places)",
  "Capitalising the pronoun I",
  "Change f to ves when forming a plural",
  "Change y to i and add -ful",
  "Change y to ies after a consonant",
  "Changing -y to -ies for plurals",
  "Check whether a sequence rule was applied correctly",
  "Checking a claim against a results table",
  "Checking statements about graph data by calculating",
  "Choose -or for an agent noun that takes it",
  "Choose all data items that fit a rule",
  "Choose between an a and e homophone pair",
  "Choose the correct conjunction to join ideas",
  "Choose the correct connective to join ideas",
  "Choose the correct end mark for a question",
  "Choose the correct end punctuation for a sentence",
  "Choose the correct spelling of a common word",
  "Choose the grammatically correct sentence",
  "Choose the homophone matching the meaning",
  "Choose the set of steps that completes a task",
  "Choosing 'me' as the object in a pair",
  "Choosing a conjunction that shows cause and reason",
  "Choosing a precise verb over a vague one",
  "Choosing a question mark to end a question",
  "Choosing a sensible digital tool for a task",
  "Choosing a sensible metric unit for a length",
  "Choosing a strong password",
  "Choosing a suitable material for a job",
  "Choosing a word with a similar meaning",
  "Choosing a word with the opposite meaning",
  "Choosing an exclamation mark for an exclamation",
  "Choosing an item that meets a condition then comparing price",
  "Choosing between 'your' and 'you're'",
  "Choosing between its and it's",
  "Choosing between the homophones 'here' and 'hear'",
  "Choosing between the homophones 'too', 'to' and 'tow'",
  "Choosing between the homophones 'won' and 'one'",
  "Choosing between the homophones 'wood' and 'would'",
  "Choosing between their, there and they're",
  "Choosing between too, to and two by meaning",
  "Choosing has or have to match the subject",
  "Choosing items that total an exact amount of money",
  "Choosing safe actions when a site asks for personal details",
  "Choosing safe and kind online actions",
  "Choosing sensible ways to sort data",
  "Choosing the best action to reduce rubbish sent to landfill",
  "Choosing the correct homophone (hear / here)",
  "Choosing the correct homophone (here / hear)",
  "Choosing the correct homophone (know / no)",
  "Choosing the correct homophone (their / there / they're)",
  "Choosing the correct homophone (there / their / they're)",
  "Choosing the correct homophone (to / too / two)",
  "Choosing the correct preposition of place",
  "Choosing the correct question word",
  "Choosing the correct short vowel in a one-syllable word",
  "Choosing the correct subject pronoun (we)",
  "Choosing the correctly spelled word (because)",
  "Choosing the possessive homophone 'their'",
  "Choosing the prefix that reverses a word's meaning",
  "Choosing variables to keep constant in a fair test",
  "Classify materials as solid, liquid or gas",
  "Close reading of a narrative ending",
  "Combine multiplying and comparing quantities",
  "Combine two roots into a single word",
  "Combining values read from a bar chart",
  "Combining values read from a bar chart to match a total",
  "Common homophones (hear and here)",
  "Comparative adjectives (-er)",
  "Comparative and superlative adjectives",
  "Compare 3-digit numbers using place value",
  "Compare and contrast details in a text",
  "Compare and order values in a data table",
  "Compare capacity using standard units and division",
  "Compare information across parts of a text",
  "Compare masses in a table and find the difference",
  "Compare masses in a table by finding the difference",
  "Compare quantities from a bar chart",
  "Compare the number of corners of 2D shapes",
  "Compare the roles of different characters",
  "Compare the size of halves and quarters of one whole",
  "Compare two characters",
  "Compare two columns of a bar graph by subtracting",
  "Compare two things in a text",
  "Compare two values on a bar chart",
  "Compare values on a bar chart",
  "Comparing capacities in millilitres and litres",
  "Comparing how two characters behave",
  "Comparing table data using subtraction across a zero",
  "Comparing two bars to find the difference",
  "Comparing two multiplication totals to judge a claim",
  "Comparing values on a bar chart",
  "Comparing values on a column graph",
  "Complete a cluster inside a multisyllabic word",
  "Complete a word beginning with wh",
  "Completing a part-to-whole analogy",
  "Completing a young-animal to grown-animal analogy",
  "Completing an opposite-word analogy",
  "Connect two parts of a text",
  "Connect two parts of a text to explain why",
  "Continue a doubling pattern",
  "Continue a growing number sequence",
  "Continue a skip-counting pattern on a number line",
  "Continue a skip-counting pattern shown on a number line",
  "Continue an increasing number pattern",
  "Continuing an on and off pattern",
  "Contractions with is and will",
  "Convert metres to centimetres",
  "Correct a word ending in ence",
  "Count and total using tally marks",
  "Count how many times a step still repeats in a loop",
  "Count lines of symmetry in a letter shape",
  "Counting lines of symmetry in a figure",
  "Counting lines of symmetry of a shape",
  "Counting on in equal steps from a marked point",
  "Counting syllables in a word",
  "Day and night, sun and shadows",
  "Debugging a sequence of instructions",
  "Decide if a statement about a pictograph is true or false",
  "Decide if items are grouped correctly by attribute",
  "Decide which consonant doubles",
  "Deciding which share is more than half",
  "Deduce a missing value in a balanced equation",
  "Determine the author's purpose",
  "Digital systems: input, process, output, storage devices",
  "Dissolving a solid in water",
  "Distinguish the possessive its from the contraction it's",
  "Distinguishing a stated fact from an implied idea",
  "Distinguishing living things from moving non-living things",
  "Divide within 10x10 in a word problem",
  "Dividing a capacity after converting litres to millilitres",
  "Dividing a length into equal parts",
  "Double consonant (bb) in 'rabbit'",
  "Double consonant (nn) in 'dinner'",
  "Double the final consonant of a stressed syllable",
  "Doubling and halving to solve problems",
  "Doubling the final consonant before -ed",
  "Doubling the final consonant before -ing",
  "Doubling the final consonant before -ing (hopping)",
  "Doubling the final consonant before adding '-ed' (stop to stopped)",
  "Doubling the final consonant before adding '-er' (big to bigger)",
  "Doubling the final consonant before adding '-ing'",
  "Doubling the final consonant before adding -ed",
  "Doubling the final consonant before adding -ing",
  "Draw a conclusion about the message",
  "Draw a conclusion from a data table",
  "Drawing a conclusion about force size from a chart",
  "Drawing a conclusion about litter harming animals from an observation",
  "Drawing a conclusion by combining two facts",
  "Drawing a conclusion from a line graph",
  "Drawing a conclusion from a stated fact",
  "Drop the final e of a le ending before -ly",
  "Drop the silent e before a vowel suffix",
  "Dropping the silent 'e' before adding -ed",
  "Dropping the silent 'e' before adding -ing",
  "Ending a question with a question mark",
  "Estimate mass using sensible standard units",
  "Explain how a writer creates a mood",
  "Explain how shadows form",
  "Explain the function of leaves",
  "Explaining animal behaviour as a response to environment",
  "Explaining day and night from Earth's rotation",
  "Explaining how a feature or behaviour helps an animal survive in its habitat",
  "Explaining how shadows are formed",
  "Explaining motion using friction",
  "Explaining why some things are kept the same",
  "Explaining why the Sun is not seen at midnight",
  "Find a fraction of a group then the remaining part",
  "Find a rule for a growing pattern and extend it",
  "Find a total from equal rows using multiplication",
  "Find a unit fraction (one third) of a whole group",
  "Find a word with an omitted letter",
  "Find the change between two points on a line graph",
  "Find the difference between points on a number line",
  "Find the largest value on a bar graph",
  "Find the missing step in an algorithm",
  "Find the perimeter of a rectangle from its length and width",
  "Find the wrong step in a set of instructions",
  "Finding a detail in a poem",
  "Finding a fact in an information text",
  "Finding a finish time after a duration",
  "Finding a later term in a subtract-constant pattern",
  "Finding a later term in an add-constant pattern",
  "Finding a quarter of a group and the remaining part",
  "Finding a stated reason in an information text",
  "Finding a step that is out of order",
  "Finding a synonym for 'chilly'",
  "Finding a term in a repeating pattern using groups",
  "Finding a total from a data table",
  "Finding change by subtracting in cents",
  "Finding elapsed time by counting on to the next hour",
  "Finding information stated directly in a text",
  "Finding the difference between the largest and smallest bar",
  "Finding the distance around a rectangle",
  "Finding the distance between two points on a number line",
  "Finding the largest category on a pie chart",
  "Finding the largest change on a line graph",
  "Finding the misplaced step in a sequence",
  "Finding the misspelled word (library) in a sentence",
  "Finding the number halfway between two points",
  "Finding the opposite of 'shrink'",
  "Finding the reason given for a rule",
  "Finding the step with a mistake in a sequence",
  "Fix a tense error in a sentence",
  "Fix an agreement error in a sentence",
  "Follow a simple 'if... then' instruction",
  "Follow a step-by-step sequence to find the result",
  "Follow and order the steps of a simple algorithm",
  "Follow cause and effect in a short text",
  "Follow sequence in a short text",
  "Follow the sequence of steps",
  "Following a menu to find the right button",
  "Following a specific step in instructions",
  "Following a yes or no decision in a flowchart",
  "Following an if-then rule to choose an action",
  "Forces and movement: push, pull, friction, gravity",
  "Form a contraction with a correctly placed apostrophe",
  "Form a plural by changing the internal vowel",
  "Form an agent noun with the suffix -ist",
  "Forming a contraction from 'we are'",
  "Forming adverbs with the suffix -ly",
  "Forming contractions with an apostrophe",
  "Forming contractions with n't (didn't)",
  "Homophones: bare vs bear",
  "Homophones: hear vs here",
  "Homophones: no vs know",
  "Homophones: their vs there",
  "Homophones: to vs too",
  "Identify a pronoun in a sentence",
  "Identify a supporting detail in a text",
  "Identify a verb in a sentence",
  "Identify cause and effect",
  "Identify cause and effect in a narrative",
  "Identify cause and effect in a text",
  "Identify evaporation and boiling",
  "Identify melting as a change of state",
  "Identify observable features",
  "Identify plant parts and their functions",
  "Identify text purpose and audience",
  "Identify the author's point of view",
  "Identify the author's purpose",
  "Identify the changed variable",
  "Identify the main idea",
  "Identify the main idea of a paragraph or whole text",
  "Identify the main idea of a passage",
  "Identify the main idea of a text",
  "Identify the main idea or overall feeling",
  "Identify the measured variable",
  "Identify the needs of plants",
  "Identify the purpose of a text",
  "Identify the purpose of a text feature",
  "Identify the purpose of an instruction",
  "Identify the theme or message of a story",
  "Identify the value of a digit in a three-digit number",
  "Identifying a 2D shape from its properties",
  "Identifying a 3D solid from the number and shape of its faces",
  "Identifying a device used to store and move files",
  "Identifying a gas among solids and liquids",
  "Identifying a season from weather clues",
  "Identifying a solid from its faces",
  "Identifying adjectives within a sentence",
  "Identifying an adverb of manner in a sentence",
  "Identifying an adverb that tells how an action is done",
  "Identifying an input device",
  "Identifying an output device",
  "Identifying camouflage as a feature that keeps an animal safe",
  "Identifying living things from their characteristics",
  "Identifying magnetic materials",
  "Identifying missing silent letters",
  "Identifying pushes and pulls",
  "Identifying the cause of an event",
  "Identifying the daily needs of a living animal",
  "Identifying the effect of an action",
  "Identifying the first stage after a butterfly egg hatches",
  "Identifying the function of a plant's roots",
  "Identifying the main idea of a text",
  "Identifying the main idea of a whole text",
  "Identifying the nouns in a sentence",
  "Identifying the purpose of a text",
  "Identifying the variable that was changed",
  "Identifying the verbs in a sentence",
  "Identifying verbs in a sentence",
  "Identifying who a text is written for",
  "Infer a cause from the text",
  "Infer a character trait from evidence in the text",
  "Infer a character's feeling",
  "Infer a character's feeling from evidence in the text",
  "Infer a character's feelings from clues",
  "Infer a character's feelings from the text",
  "Infer a character's motive",
  "Infer a character's motive from evidence in the text",
  "Infer a feeling from clues",
  "Infer a feeling from clues in the text",
  "Infer meaning from a poem",
  "Inferring character and animal behaviour from detail",
  "Inferring how a character feels",
  "Inferring how characters feel",
  "Inferring the reason behind an instruction",
  "Inferring why a character acts",
  "Inferring why a character says something",
  "Interpret a two-way or grouped table",
  "Interpret results from a simple experiment table",
  "Interpreting a data table to find what a plant needs to grow",
  "Interpreting a data table with two number columns",
  "Interpreting shadow data to infer the Sun's position",
  "Irregular past tense verbs (run - ran)",
  "Join a prefix without altering the base word",
  "Joining two short sentences with a conjunction",
  "Joining two words to form a compound word",
  "Joining two words to make a compound word",
  "Judging the past tense of an irregular verb",
  "Judging whether a sentence uses correct grammar",
  "Judging whether an investigation is fair",
  "Judging whether the verb matches a plural subject",
  "Keep both l letters when -ly follows a final l",
  "Keep the ible vowel when adding -ity",
  "Keep variables controlled",
  "Keep verb tense consistent within a sentence",
  "Keeping a password private",
  "Keeping a password safe",
  "Knowing that 'bus' is spelled with one 's'",
  "Knowing when to tell a trusted adult",
  "Knowing which materials a magnet attracts",
  "Link sound to vibration",
  "Linking a fraction of a group to a pie chart slice",
  "Linking a fraction of a group to chart data",
  "Linking a material's property to why it is chosen",
  "Linking friction to distance travelled using a chart",
  "Living things: needs, life cycles, habitats",
  "Locate and match details in a text",
  "Locate directly stated information",
  "Locate directly stated information in a text",
  "Locating a directly stated detail",
  "Locating a named weekday and date on a calendar",
  "Make a straightforward inference from the text",
  "Make and compare a money total under $20",
  "Making a plural by adding -es after x, s, sh or ch",
  "Making a plural by adding -s",
  "Making a plural by changing y to -ies",
  "Making plurals by adding '-es' to words ending in 'o'",
  "Making plurals by adding '-es' to words ending in 'ss'",
  "Making plurals by adding '-es' to words ending in 'x'",
  "Making plurals by changing 'f' to 'ves' (leaf to leaves)",
  "Making plurals by changing 'y' to 'ies' (baby to babies)",
  "Making plurals of words ending in sh by adding -es",
  "Match a plural subject to its verb",
  "Match a singular subject to its verb",
  "Match details to parts of a text",
  "Match facts to details in a text",
  "Match half past a time to its digital form",
  "Match information to details in a text",
  "Match symbols to their meanings using a key",
  "Match the le spelling to the meaning rule",
  "Matching a device to the job it does",
  "Matching a length to an appropriate unit",
  "Matching a material's property to its use",
  "Matching a plural subject to don't",
  "Matching a plural subject to its verb",
  "Matching a task to the right digital tool",
  "Matching a verb to a past-time signal word",
  "Matching a verb to a singular subject across a nearby plural",
  "Matching a verb to a singular subject across a plural phrase",
  "Matching animals to their animal group by features",
  "Matching animals to their habitats",
  "Matching conjunctions to their function",
  "Matching contractions to their full words",
  "Matching digital words to their meaning",
  "Matching each detail to what the text says about it",
  "Matching expanded form to a standard number",
  "Matching foods to the plant or animal they come from",
  "Matching hardware to its job",
  "Matching hardware to its purpose",
  "Matching hardware to the job it does",
  "Matching materials to their useful properties",
  "Matching online situations to good actions",
  "Matching online situations to safe actions",
  "Matching parts of an animal to their use",
  "Matching plant parts to their jobs",
  "Matching spoken time to digital time",
  "Matching verb tense to a past-time signal",
  "Materials and their properties (float/sink, bend, absorb)",
  "Measurement comparisons requiring unit conversion (kg/g)",
  "Measurement comparisons requiring unit conversion (m/cm)",
  "Melting: solids turning to liquid when heated",
  "Multi-step word problem with two operations",
  "Multiply within 10x10 in a word problem",
  "Name a 2D shape from its number of sides and corners",
  "Name a 2D shape from its sides and corners",
  "Name a 3D object from its faces",
  "Name the fraction of a group shown in a pie chart",
  "Name the fraction shown by one equal part of a pie chart",
  "Naming a shape from its sides and corners",
  "Order 3-digit numbers from smallest to largest",
  "Order three-digit numbers from smallest to largest",
  "Ordering a simple food chain",
  "Ordering an algorithm that uses repetition",
  "Ordering numbers written in words, digits and place-value form",
  "Ordering space objects by size",
  "Ordering the stages of a frog's life cycle",
  "Ordering the steps in a flowchart",
  "Ordering the steps of a simple algorithm",
  "Ordering the steps of an investigation",
  "Ordering the steps to use a system",
  "Ordering three-digit numbers",
  "Ordering words into a well-formed sentence",
  "Ordering words to build a complete question",
  "Ordering words to build a correct sentence",
  "Ordering words to build a statement",
  "Ordering words to build an exclamation",
  "Patterns and simple branching (if/then) in everyday instructions",
  "Place commas correctly in a list",
  "Placing speech marks around the exact spoken words",
  "Precise word choice and shades of meaning",
  "Predict a character's behaviour",
  "Predict the solid formed by folding a net",
  "Predict what will happen next",
  "Predict what will happen next using clues",
  "Predicting what happens next",
  "Proofreading: find the one misspelt word",
  "Proofreading: select the two misspelt words",
  "Punctuate direct speech correctly",
  "Punctuate items in a list",
  "Punctuate possession correctly",
  "Punctuating spoken words with speech marks",
  "Put the steps of an everyday task in order",
  "Putting everyday steps into a correct algorithm",
  "Putting the steps of a task in a sensible order",
  "Putting words in alphabetical order",
  "Read a bar graph to find the greatest capacity",
  "Read a simple table to compare values",
  "Read a table to find the largest value",
  "Read a value from a bar chart",
  "Read a value from a pictograph",
  "Read an analog clock to the nearest 5 minutes",
  "Read and interpret data in a table or pictograph a computer produced",
  "Read change from a line graph",
  "Read information from a table",
  "Read two values from a table and add them",
  "Read values on a number line and find a difference",
  "Reading a bar chart and multiplying to compare totals",
  "Reading a measurement from a number line",
  "Reading a number line and finding a difference",
  "Reading a scale and finding the difference between two points",
  "Reading a table alongside a passage",
  "Reading a two-symbol code",
  "Reading a value from a bar chart",
  "Reading a value from a rainfall bar chart",
  "Reading a value from a ramp results table",
  "Reading a value from a table then dividing equally",
  "Reading a weather data table",
  "Reading an exact value from a bar chart",
  "Reading and comparing values in a table",
  "Reading float and sink results from a table",
  "Reading masses from a bar chart and combining them",
  "Reading positions and steps on a number line",
  "Reading the correct column of a data table",
  "Reading the right column of a data table",
  "Reading totals from a pictograph key",
  "Reason about a doubling sequence",
  "Reason about cause and effect",
  "Reason about how many more are needed",
  "Reason about lines of symmetry described in words",
  "Reason backwards about rounding to the nearest 10",
  "Reasoning about why animals store fat before winter",
  "Reasoning with money and change across several purchases",
  "Reasoning with two-way data in a table",
  "Recall an irregular plural form",
  "Recall the ie order in friend",
  "Recognise French-derived ch spellings",
  "Recognising a half share on a pie chart",
  "Recognising a reversible change",
  "Recognising a strong password",
  "Recognising correctly spelled common words",
  "Recognising correctly spelt two-syllable words",
  "Recognising personal information",
  "Recognising plurals that do not add -s",
  "Recognising that solids keep their shape",
  "Recognising the suffix '-ful' is spelled with one 'l'",
  "Recognising true facts about how magnets behave",
  "Recognising true facts about the Sun",
  "Recognising unsafe requests for personal details",
  "Recover the is singular from an es plural",
  "Responding safely to an online stranger",
  "Responding safely to online strangers",
  "Retain the e before -ous after a soft g",
  "Round a 2-digit number to the nearest 10",
  "Rounding a two-digit number to the nearest ten",
  "Safe and responsible use of devices and passwords",
  "Select the ance ending for an abstract noun",
  "Select the confusable word that fits the meaning",
  "Select the possessive form of a three-way homophone",
  "Selecting a material using two properties from a table",
  "Selecting a material using two properties in a table",
  "Selecting statements that correctly compare two characters",
  "Separate the c noun from the s verb",
  "Separating items in a list with commas",
  "Sequence events in a recount",
  "Sequence events in a text",
  "Sequence events in the order they happen",
  "Sequence stages in a process",
  "Sequence steps in a process",
  "Sequence the steps in a procedure",
  "Sequencing events",
  "Sequencing events in a story",
  "Sequencing instructions so a task works correctly",
  "Sequencing stages of an animal life cycle",
  "Sequencing the stages of a frog's life cycle",
  "Share a quantity equally using a known times fact",
  "Sharing with a remainder and interpreting what is left",
  "Showing that one owner has something with an apostrophe",
  "Silent letter b in 'climb'",
  "Soft c (c sounding like s) in 'circle'",
  "Soft g (g sounding like j) in 'gentle'",
  "Solve a two-step money problem with multiplication then subtraction",
  "Solve a two-step problem using a multiplication fact then subtraction",
  "Solving for an unknown using two picture equations",
  "Sort animals by observable features",
  "Sort items into a group by an attribute",
  "Sorting devices into inputs and outputs",
  "Sorting items as hardware or software",
  "Sorting nouns, verbs and adjectives",
  "Sorting things into living and non-living",
  "Spell a reduced middle syllable",
  "Spell a word using rh and y as a vowel",
  "Spell an unclear middle vowel correctly",
  "Spell sci words ending in -ous",
  "Spell the homophone matching a given meaning",
  "Spell words with an initial silent k",
  "Spelling a long vowel with the silent 'e' (magic e) pattern",
  "Spelling frequently misspelled words",
  "Spelling irregular plurals (foot / feet)",
  "Spelling irregular plurals ending in -f",
  "Spelling plurals by adding -es after x",
  "Spelling plurals: changing y to ies",
  "Spelling regular plurals (-s, -es and -ies)",
  "Spelling the 'ch' digraph at the end of a word",
  "Spelling the -tion suffix",
  "Spelling the /air/ sound with the 'air' letter team",
  "Spelling the /ar/ sound with the 'ar' letter team",
  "Spelling the /aw/ sound with the 'aw' letter team",
  "Spelling the /ch/ sound with 'tch' after a short vowel",
  "Spelling the /er/ sound with the 'ir' letter team",
  "Spelling the /f/ sound with 'ph'",
  "Spelling the /or/ sound with the 'or' letter team",
  "Spelling the /ow/ sound with the 'ou' letter team",
  "Spelling the /oy/ sound with 'oy' at the end of a word",
  "Spelling the long 'a' sound with the 'ai' vowel team",
  "Spelling the long /a/ sound with the 'ai' letter team",
  "Spelling the long /a/ sound with the split digraph a-e",
  "Spelling the long /ee/ sound with the 'ee' letter team",
  "Spelling the long /i/ sound with the 'igh' letter team",
  "Spelling the long /oo/ sound with the 'oo' letter team",
  "Spelling the soft /j/ sound made by 'g' before 'i'",
  "Spelling the soft /s/ sound made by 'c' before 'i'",
  "Spelling the three-letter blend 'str' at the start of a word",
  "Spelling the tricky word 'because'",
  "Spelling the tricky word 'friend'",
  "Spelling the tricky word 'friend' with 'ie' in the middle",
  "Spelling the tricky word 'said'",
  "Spelling the tricky word 'they'",
  "Spelling the tricky word 'was'",
  "Spelling words that begin with a silent 'k' before 'n'",
  "Spelling words that begin with a silent 'w' before 'r'",
  "Spelling words that begin with the 'bl' blend",
  "Spelling words that begin with the 'sh' digraph",
  "Spelling words that begin with the 'th' digraph",
  "Spelling words with a silent 'b' after 'm'",
  "Spelling words with a silent 't' (castle)",
  "Spelling words with a silent k",
  "Spot a misspelled common Year 3 word",
  "Spotting a suspicious pop-up message",
  "Spotting correctly spelled common words",
  "Spotting misspelled words in a sentence",
  "Spotting where a line graph stays level",
  "Subject-verb agreement (was / were)",
  "Subtract 3-digit numbers with regrouping",
  "Subtract a three-digit number needing regrouping",
  "Subtract a two-digit number from a three-digit number with regrouping",
  "Supply a silent letter inside a word",
  "Telling hardware apart from software",
  "Telling hardware from software",
  "The prefixes re- and dis-",
  "The suffixes -ful and -er",
  "Time intervals and elapsed time problems",
  "Two-step word problems with money",
  "Understand a simile in a poem",
  "Understand cause and effect in a text",
  "Understand figurative language in a poem",
  "Understand the value of a digit in a 3-digit number",
  "Understand vocabulary in context",
  "Understanding a condition in a text",
  "Understanding that pushes and pulls are forces",
  "Understanding that vibrations make sound",
  "Understanding the effect of a particular word choice",
  "Understanding the prefix 're-' meaning 'again'",
  "Understanding what a comparison shows",
  "Understanding what software is",
  "Use a comma before a joining word in a compound sentence",
  "Use a known multiplication fact to solve a division",
  "Use a related word to fix an unstressed vowel",
  "Use an apostrophe to show singular possession",
  "Use capital letters for sentence starts and proper nouns",
  "Use clues to order items in a sequence",
  "Use the verb form passed in a past-tense sentence",
  "Using 'a' and 'an' before nouns",
  "Using 'will' for the future tense",
  "Using a comma after an introductory phrase",
  "Using a comma before a person's name when speaking to them",
  "Using a constant time interval to find a later time",
  "Using a division fact then subtracting in a two-step problem",
  "Using a double consonant after a short vowel (rabbit)",
  "Using a properties table to pick the best material",
  "Using an apostrophe to show ownership by a plural noun",
  "Using an apostrophe to show singular possession",
  "Using capital letters and full stops correctly",
  "Using capitals and full stops to separate sentences",
  "Using capitals for the sentence start, places and months",
  "Using doubling to compare heights on a chart",
  "Using headings to find the right part of a text",
  "Using superlative adjectives (-est)",
  "Using the articles a, an and the",
  "Weather and seasons",
  "Work backwards from a result to find a start number",
  "Work backwards through two changes",
  "Work out an elapsed time from a timetable",
  "Work out change from a whole dollar amount",
  "Work out the meaning of a phrase in a poem",
  "Work out the meaning of a phrase in context",
  "Work out the meaning of a word from context",
  "Work out the meaning of a word in a poem",
  "Work out the meaning of a word in context",
  "Work out the meaning of a word with more than one meaning",
  "Work out the meaning of words in context",
  "Work out the result of a repeated instruction (loop)",
  "Work out word meaning in context",
  "Working backwards to find an unknown that appears twice",
  "Working out a new direction after turns",
  "Working out a total from a pictograph key",
  "Working out a word's meaning from context",
  "Working out how a person feels",
  "Working out meaning from the suffix -less",
  "Working out the author's purpose for writing",
  "Working out the meaning of a word from its context",
  "Working out the output of a simple rule",
  "Working out the output of a two-step rule",
  "Working out the result of a repeated instruction",
  "Working out which noun a pronoun replaces",
  "Working out why an author included a comparison",
  "Working out why an author included a paragraph",
  "Working out why an event happens",
  "Working out word meaning from context",
  "Writing the irregular plural of 'foot'",
];
