/**
 * Curated-bank skill labels that do not yet resolve through the
 * question-factory skill taxonomy (`SKILL_TAXONOMY_ENTRIES`).
 *
 * Every one of these arrived with the 2026-08-08 Grade 3 ingest: 201
 * hand-authored, independently blind-reviewed questions across six ICAS
 * programmes. The bank's original 100 questions all still resolve.
 *
 * They are recorded rather than mapped because mapping is an editorial
 * decision, not a mechanical one. Deciding that "Soft c (c sounding like
 * s) in 'circle'" belongs under one taxonomy entry rather than another is
 * a judgement about the skill's identity, and a guessed alias would be
 * worse than an acknowledged gap: it would silently mis-attribute the
 * question's coverage and mislead blueprint planning for that entry ever
 * after.
 *
 * This list is a two-way ratchet, enforced in taxonomy.test.ts. A NEW
 * unmapped skill fails, so the debt cannot grow unnoticed; mapping one of
 * these also fails, forcing its removal here. Shrinking it to empty is the
 * goal, and at that point both the list and its assertion should go.
 */
export const UNMAPPED_CURATED_SKILL_LABELS: readonly string[] = [
  "Adding -ed to a base word with no spelling change",
  "Adding -ing to a base word with no spelling change",
  "Adding three-digit numbers with two regroupings",
  "Apostrophes to show possession",
  "Being kind and polite online",
  "Building a three-digit number from place value clues",
  "Checking a claim against a results table",
  "Checking statements about graph data by calculating",
  "Choose all data items that fit a rule",
  "Choose the set of steps that completes a task",
  "Choosing a precise verb over a vague one",
  "Choosing a sensible digital tool for a task",
  "Choosing a sensible metric unit for a length",
  "Choosing a suitable material for a job",
  "Choosing items that total an exact amount of money",
  "Choosing the best action to reduce rubbish sent to landfill",
  "Choosing the correct question word",
  "Choosing the correct short vowel in a one-syllable word",
  "Close reading of a narrative ending",
  "Combining values read from a bar chart to match a total",
  "Common homophones (hear and here)",
  "Comparative and superlative adjectives",
  "Comparing capacities in millilitres and litres",
  "Comparing how two characters behave",
  "Comparing table data using subtraction across a zero",
  "Comparing two multiplication totals to judge a claim",
  "Comparing values on a column graph",
  "Continuing an on and off pattern",
  "Contractions with is and will",
  "Count and total using tally marks",
  "Count how many times a step still repeats in a loop",
  "Counting lines of symmetry in a figure",
  "Counting syllables in a word",
  "Decide if a statement about a pictograph is true or false",
  "Decide if items are grouped correctly by attribute",
  "Dissolving a solid in water",
  "Distinguishing a stated fact from an implied idea",
  "Double consonant (bb) in 'rabbit'",
  "Double consonant (nn) in 'dinner'",
  "Doubling and halving to solve problems",
  "Doubling the final consonant before -ing (hopping)",
  "Doubling the final consonant before adding -ed",
  "Doubling the final consonant before adding -ing",
  "Drawing a conclusion about litter harming animals from an observation",
  "Drawing a conclusion by combining two facts",
  "Drawing a conclusion from a line graph",
  "Drawing a conclusion from a stated fact",
  "Dropping the silent 'e' before adding -ed",
  "Dropping the silent 'e' before adding -ing",
  "Explaining how a feature or behaviour helps an animal survive in its habitat",
  "Explaining how shadows are formed",
  "Explaining why some things are kept the same",
  "Explaining why the Sun is not seen at midnight",
  "Find the missing step in an algorithm",
  "Find the wrong step in a set of instructions",
  "Finding a detail in a poem",
  "Finding a fact in an information text",
  "Finding a quarter of a group and the remaining part",
  "Finding a stated reason in an information text",
  "Finding elapsed time by counting on to the next hour",
  "Finding information stated directly in a text",
  "Finding the reason given for a rule",
  "Follow a simple 'if... then' instruction",
  "Follow a step-by-step sequence to find the result",
  "Following a menu to find the right button",
  "Following a specific step in instructions",
  "Following a yes or no decision in a flowchart",
  "Homophones: bare vs bear",
  "Homophones: hear vs here",
  "Homophones: no vs know",
  "Homophones: their vs there",
  "Homophones: to vs too",
  "Identifying a 2D shape from its properties",
  "Identifying a 3D solid from the number and shape of its faces",
  "Identifying a season from weather clues",
  "Identifying an input device",
  "Identifying an output device",
  "Identifying camouflage as a feature that keeps an animal safe",
  "Identifying pushes and pulls",
  "Identifying the cause of an event",
  "Identifying the daily needs of a living animal",
  "Identifying the effect of an action",
  "Identifying the first stage after a butterfly egg hatches",
  "Identifying the main idea of a text",
  "Identifying the main idea of a whole text",
  "Identifying the purpose of a text",
  "Identifying the variable that was changed",
  "Identifying who a text is written for",
  "Inferring character and animal behaviour from detail",
  "Inferring how a character feels",
  "Inferring how characters feel",
  "Inferring the reason behind an instruction",
  "Inferring why a character acts",
  "Inferring why a character says something",
  "Interpreting a data table to find what a plant needs to grow",
  "Joining two short sentences with a conjunction",
  "Keeping a password private",
  "Knowing which materials a magnet attracts",
  "Locating a directly stated detail",
  "Locating a named weekday and date on a calendar",
  "Making a plural by adding -es after x, s, sh or ch",
  "Making a plural by adding -s",
  "Making a plural by changing y to -ies",
  "Match symbols to their meanings using a key",
  "Matching a device to the job it does",
  "Matching a task to the right digital tool",
  "Matching animals to their habitats",
  "Matching each detail to what the text says about it",
  "Matching foods to the plant or animal they come from",
  "Matching materials to their useful properties",
  "Matching parts of an animal to their use",
  "Matching plant parts to their jobs",
  "Matching spoken time to digital time",
  "Melting: solids turning to liquid when heated",
  "Ordering a simple food chain",
  "Ordering numbers written in words, digits and place-value form",
  "Ordering the stages of a frog's life cycle",
  "Ordering the steps in a flowchart",
  "Ordering the steps of an investigation",
  "Ordering three-digit numbers",
  "Predicting what happens next",
  "Proofreading: find the one misspelt word",
  "Proofreading: select the two misspelt words",
  "Put the steps of an everyday task in order",
  "Putting words in alphabetical order",
  "Read a value from a pictograph",
  "Read information from a table",
  "Reading a bar chart and multiplying to compare totals",
  "Reading a scale and finding the difference between two points",
  "Reading a table alongside a passage",
  "Reading a two-symbol code",
  "Reading a value from a bar chart",
  "Reading a value from a rainfall bar chart",
  "Reading a value from a ramp results table",
  "Reading float and sink results from a table",
  "Reading masses from a bar chart and combining them",
  "Reading positions and steps on a number line",
  "Reasoning about why animals store fat before winter",
  "Reasoning with two-way data in a table",
  "Recognising a strong password",
  "Recognising correctly spelt two-syllable words",
  "Recognising personal information",
  "Recognising that solids keep their shape",
  "Responding safely to an online stranger",
  "Rounding a two-digit number to the nearest ten",
  "Selecting statements that correctly compare two characters",
  "Sequencing events",
  "Sequencing events in a story",
  "Sharing with a remainder and interpreting what is left",
  "Silent letter b in 'climb'",
  "Soft c (c sounding like s) in 'circle'",
  "Soft g (g sounding like j) in 'gentle'",
  "Sort items into a group by an attribute",
  "Sorting items as hardware or software",
  "Sorting nouns, verbs and adjectives",
  "Sorting things into living and non-living",
  "Spelling a long vowel with the silent 'e' (magic e) pattern",
  "Spelling regular plurals (-s, -es and -ies)",
  "Spelling the 'ch' digraph at the end of a word",
  "Spelling the long 'a' sound with the 'ai' vowel team",
  "Spelling the three-letter blend 'str' at the start of a word",
  "Spelling the tricky word 'because'",
  "Spelling the tricky word 'friend'",
  "Spelling the tricky word 'said'",
  "Spelling the tricky word 'they'",
  "Spelling the tricky word 'was'",
  "Spelling words that begin with the 'bl' blend",
  "Spelling words that begin with the 'sh' digraph",
  "Spelling words that begin with the 'th' digraph",
  "Spotting a suspicious pop-up message",
  "The prefixes re- and dis-",
  "The suffixes -ful and -er",
  "Two-step word problems with money",
  "Understanding a condition in a text",
  "Understanding that vibrations make sound",
  "Understanding the effect of a particular word choice",
  "Understanding what a comparison shows",
  "Understanding what software is",
  "Using a division fact then subtracting in a two-step problem",
  "Using a properties table to pick the best material",
  "Using headings to find the right part of a text",
  "Using the articles a, an and the",
  "Work out the result of a repeated instruction (loop)",
  "Working backwards to find an unknown that appears twice",
  "Working out a word's meaning from context",
  "Working out how a person feels",
  "Working out the author's purpose for writing",
  "Working out the meaning of a word from its context",
  "Working out why an author included a comparison",
  "Working out why an author included a paragraph",
  "Working out why an event happens",
  "Working out word meaning from context",
];
